'''Miscellaneous helper functions for :mod:`asyncutils` submodules that are not meant to be seen by the user.
These are undocumented and unstable, and will remain so. This stub file exists for the convenience of development only.'''
from .types import CanClearAndCopy
from ..config import Executor
from _collections_abc import Awaitable, Callable, Generator, Iterable
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from asyncio.tasks import Task
from typing import Any, overload
def filter_out(*a: object, s: object=...) -> Generator[Any]: ...
def get_loop_and_set() -> AbstractEventLoop: ...
def check_methods(obj: object, /, *meth: str) -> bool: ...
def stop_and_closer(loop: AbstractEventLoop) -> Callable[[], None]: ...
def copy_and_clear[D: CanClearAndCopy[Any]](l: D) -> D: ...
def subscriptable[T: type](cls: T, /) -> T: ...
def check(candidate: object, against: object, /) -> bool: ...
def create_executor(obj: object, /, save: bool=...) -> Executor: ...
@overload
def coerce_callable[T: Callable[..., Any]](f: T, /) -> T: ... # type: ignore[overload-overlap]
@overload
def coerce_callable[T](o: T, /) -> type[T]: ...
def fullname(f: object, /, rmpref: bool=...) -> str: ...
def audit_fullname(f: object, /, rmpref: bool=...) -> None: ...
def verify_compat(version: str, /) -> bool: ...
class LoopMixinBase:
    @property
    def loop(self) -> AbstractEventLoop: '''The underlying event loop.'''
    def make[T](self, aw: Awaitable[T]) -> Task[T]: '''Create a :class:`~asyncio.tasks.Task` for the given awaitable that runs in the underlying loop.'''
    def make_fut(self) -> Future[Any]: '''Create a :class:`~asyncio.futures.Future` attached to the underlying loop.'''
    def make_multiple[T](self, aws: Iterable[Awaitable[T]]) -> Generator[Task[T]]: '''Return an iterator over instances of :class:`~asyncio.tasks.Task` created for each coroutine in C, in that order.'''