'''Miscellaneous helper functions for :mod:`asyncutils` submodules that are not meant to be seen by the user.'''
from .prots import CanClearAndCopy
from ..config import Executor
from asyncio import AbstractEventLoop, Future, Task
from collections.abc import Awaitable, Callable, Iterable
from ty_extensions import Not
from types import GeneratorType, ModuleType
from typing import Any, TypeGuard, overload
def filter_out(*a: object, s: object=...) -> GeneratorType[Any]: '''Yield items in the positional arguments not identical to the sentinel ``s``, or ``None`` by default.'''
def get_loop_and_set() -> AbstractEventLoop: '''Return the running event loop. If there is none, create and set one first.'''
def check_methods(obj: object, /, *meth: str) -> bool: '''Re-implement :func:`!collections.abc._check_methods`.'''
def copy_and_clear[T: CanClearAndCopy[Any]](l: T) -> T: ...
def ismodule(o: object, /) -> TypeGuard[ModuleType]: ...
def subscriptable[T: type](cls: T, /) -> T: ...
def check(candidate: object, against: object, /) -> bool: ...
def create_executor(obj: object, /, save: bool=...) -> Executor: ...
@overload
def coerce_callable[T: Callable[..., Any]](f: T, /) -> T: ...
@overload
def coerce_callable[T: Not[Callable[..., Any]]](o: T, /) -> type[T]: ...
def fullname(f: object, /, remove_prefix: bool=...) -> str: ...
def audit_fullname(f: object, /, remove_prefix: bool=...) -> None: ...
async def simple_wrap[T](aw: Awaitable[T], /) -> T: ...
class LoopMixinBase:
    @property
    def loop(self) -> AbstractEventLoop: '''The underlying event loop.'''
    def make[T](self, aw: Awaitable[T], /) -> Task[T]: '''Create a :class:`~asyncio.Task` for the given awaitable that runs in the underlying loop.'''
    def make_fut(self) -> Future[Any]: '''Create a :class:`~asyncio.Future` attached to the underlying loop.'''
    def make_multiple[T](self, aws: Iterable[Awaitable[T]], /) -> GeneratorType[Task[T]]: '''Return an iterator over instances of :class:`~asyncio.Task` created for each coroutine in C, in that order.'''
class Bag(dict[str, Any]): # noqa: FURB189
    '''A thin dictionary subclass that supports attribute access.'''
    def __getattr__(self, key: str, /) -> Any: ... # noqa: ANN401
    def __setattr__(self, key: str, value: object, /) -> None: ...
    def __delattr__(self, key: str, /) -> None: ...
