'''Miscellaneous helper functions for :mod:`asyncutils` submodules that are not meant to be seen by the user.
These are undocumented and will remain so; neither will they be stable.
The stub file exists for the convenience of development only.'''
from .types import CanClearAndCopy
from ..config import Executor
from _collections_abc import Callable, Coroutine, Generator, Iterable
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from asyncio.tasks import Task
from typing import Any, overload
def filter_out(*a: object, s: object=...) -> Generator[Any]: ...
def get_loop_and_set() -> AbstractEventLoop: ...
def check_methods(obj: object, /, *meth: str) -> bool: ...
def stop_and_closer(loop: AbstractEventLoop) -> Callable[[], None]: ...
def copy_and_clear[D: CanClearAndCopy[Any]](l: D) -> D: ...
def subscriptable[T: type](cls: T, /) -> T: ...
def check(candidate: object, against: object, /) -> bool: ...
def create_executor(obj: object, /, save: bool=...) -> Executor: ...
@overload
def coerce_callable[T: Callable[..., Any]](f: T, /) -> T: ... # type: ignore[overload-overlap]
@overload
def coerce_callable[T](o: T, /) -> type[T]: ...
def fullname(f: object, /, rmpref: bool=...) -> str: ...
def audit_fullname(f: object, /, rmpref: bool=...) -> None: ...
class LoopMixinBase:
    def make[T](self, coro: Coroutine[Any, Any, T]) -> Task[T]: '''Create a :class:`~asyncio.Task` for the given coroutine that runs in the underlying loop.'''
    def make_fut(self) -> Future[Any]: '''Create a :class:`~asyncio.Future` attached to the underlying loop.'''
    def make_multiple[T](self, C: Iterable[Coroutine[Any, Any, T]]) -> Generator[Task[T]]: '''Return an iterator over instances of Task created for each coroutine in C, in that order.'''