'''A special module used to set up the asyncutils module namespace.
**Do not modify its contents or reload it at runtime.**'''
from types import ModuleType
from typing import Self, Any, Final, final, overload
from .protocols import All, Submodule
@final
class module:
    @overload
    def __new__(cls, name: Submodule, /) -> Self: ...
    @overload
    def __new__(cls, name: str, /) -> Any: ...
    def __getattr__(self, name: str, /) -> Any: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[type[Self], tuple[str]]: ...
    def load(self) -> ModuleType: ...
    @property
    def __all__(self) -> All: ...
    def __dir__(self) -> All: ...
a: Final[All]
s: Final[dict[Submodule, module|ModuleType]]