'''A special module used to set up the asyncutils module namespace.
**Do not modify its contents or reload it at runtime.**'''
from .protocols import All, Submodule
from types import ModuleType
from typing import Any, Final, Self, final, overload
@final
class Module:
    @overload
    def __new__(cls, name: Submodule, /) -> Self: ...
    @overload
    def __new__(cls, name: str, /) -> Any: ...
    def __getattr__(self, name: str, /) -> Any: ...
    def __reduce__(self) -> tuple[type[Self], tuple[str]]: ...
    def load(self) -> ModuleType: ...
    @property
    def __all__(self) -> All: ...
    def __dir__(self) -> All: ...
a: Final[All]
s: Final[dict[Submodule, Module|ModuleType]]