from typing import Self, Any, overload
from types import ModuleType
from .protocols import All, Submodule
class module:
    @overload
    def __new__(cls, name: Submodule, /) -> Self: ...
    @overload
    def __new__(cls, name: str, /) -> Any: ...
    def __getattr__(self, name: str, /) -> Any: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[type[Self], tuple[str]]: ...
    def load(self) -> ModuleType: ...
def g() -> All: ...
a: All
s: dict[Submodule, module|ModuleType]