'''This module reexports all the attributes of the logger used by asyncutils.'''
from _collections_abc import Mapping
from logging import LogRecord, Logger, Manager, Handler, RootLogger, _ExcInfoType, _SysExcInfoType, _ArgsType, _FilterType
from typing import Final
name: str
level: int
parent: None
propagate: bool
handlers: list[Handler]
disabled: bool
root: Final[RootLogger]
manager: Final[Manager]
filters: list[_FilterType]
def addFilter(filter: _FilterType) -> None: ...
def removeFilter(filter: _FilterType) -> None: ...
def filter(record: LogRecord) -> bool|LogRecord: ...
def setLevel(level: int|str) -> None: ...
def isEnabledFor(level: int) -> bool: ...
def getEffectiveLevel() -> int: ...
def getChild(suffix: str) -> Logger: ...
def getChildren(self) -> set[Logger]: ...
def debug(msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def info(msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def warning(msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def error(msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def exception(msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def critical(msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def log(level: int, msg: object, *args: object, exc_info: _ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def addHandler(hdlr: Handler) -> None: ...
def removeHandler(hdlr: Handler) -> None: ...
def findCaller(stack_info: bool=..., stacklevel: int=1) -> tuple[str, int, str, str|None]: ...
def handle(record: LogRecord) -> None: ...
def makeRecord(name: str, level: int, fn: str, lno: int, msg: object, args: _ArgsType, exc_info: _SysExcInfoType|None, func: str|None=..., extra: Mapping[str, object]|None=..., sinfo: str|None=...) -> LogRecord: ...
def hasHandlers(self) -> bool: ...
def callHandlers(record: LogRecord) -> None: ...