'''This module reexports all the attributes of the logger used by :mod:`asyncutils`.'''
import logging as L
from _collections_abc import Mapping
from typing import Final
name: Final[str]
level: int
parent: None
propagate: bool
handlers: list[L.Handler]
disabled: bool
root: Final[L.RootLogger]
manager: Final[L.Manager]
filters: list[L._FilterType]
def addFilter(filter: L._FilterType) -> None: ...
def removeFilter(filter: L._FilterType) -> None: ...
def filter(record: L.LogRecord) -> bool|L.LogRecord: ...
def setLevel(level: int|str) -> None: ...
def isEnabledFor(level: int) -> bool: ...
def getEffectiveLevel() -> int: ...
def getChild(suffix: str) -> L.Logger: ...
def getChildren() -> set[L.Logger]: ...
def debug(msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def info(msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def warning(msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def error(msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def exception(msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def critical(msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def log(level: int, msg: object, *args: object, exc_info: L._ExcInfoType=..., stack_info: bool=..., stacklevel: int=..., extra: Mapping[str, object]|None=...) -> None: ...
def addHandler(hdlr: L.Handler) -> None: ...
def removeHandler(hdlr: L.Handler) -> None: ...
def findCaller(stack_info: bool=..., stacklevel: int=...) -> tuple[str, int, str, str|None]: ...
def handle(record: L.LogRecord) -> None: ...
def makeRecord(name: str, level: int, fn: str, lno: int, msg: object, args: L._ArgsType, exc_info: L._SysExcInfoType|None, func: str|None=..., extra: Mapping[str, object]|None=..., sinfo: str|None=...) -> L.LogRecord: ...
def hasHandlers() -> bool: ...
def callHandlers(record: L.LogRecord) -> None: ...