'''Utilities to patch various things, from function signatures to annoying warnings emitted by asyncio.'''
from .protocols import SigPatcher
def patch_asyncio_warnings() -> None: ...
def patch_unawaited_coroutine_warnings() -> None: ...
def patch_properties[T: type](cls: T, /) -> T: ...
patch_function_signatures: SigPatcher
patch_method_signatures: SigPatcher
patch_classmethod_signatures: SigPatcher