from .protocols import SigPatcher
def patch_asyncio_warnings() -> None: ...
def patch_unawaited_coroutine_warnings() -> None: ...
patch_function_signatures: SigPatcher
patch_method_signatures: SigPatcher
patch_classmethod_signatures: SigPatcher