from .protocols import PatchEntry
def patch_asyncio_warnings() -> None: ...
def patch_unawaited_coroutine_warnings() -> None: ...
def patch_function_signatures(*to_patch: PatchEntry) -> None: ...
def patch_method_signatures(*to_patch: PatchEntry) -> None: ...
def patch_classmethod_signatures(*to_patch: PatchEntry) -> None: ...