'''Defines interfaces and type aliases used in this module's stubs. Pseudo-stable (deprecation periods will span at least 2 minor versions).
This is a fake module in the sense that the names in this stub are all None at runtime, so do not inherit from its 'protocols'.
This facilitates lightweight inline type annotations.'''
from _collections_abc import Awaitable, Iterator, Iterable, AsyncIterable, Callable, Generator, Coroutine, Buffer, AsyncGenerator
from io import TextIOWrapper, _WrappedBuffer
from types import TracebackType, FunctionType
from contextlib import _AsyncGeneratorContextManager
from mmap import mmap
from typing import Protocol, Self, SupportsIndex, SupportsInt, Any, Literal, IO, NewType, overload, type_check_only, final
from ..constants import sentinel_base
from ..mixins import LoopContextMixin
import sys
@type_check_only
class SupportsLT(Protocol):
    '''An object that implements the < operator.'''
    def __lt__(self, other: Self, /) -> bool: ...
@type_check_only
class SupportsGT(Protocol):
    '''An object that implements the > operator.'''
    def __gt__(self, other: Self, /) -> bool: ...
@type_check_only
class AsyncContextManager[T](Protocol):
    '''An asynchronous context manager. Basically `contextlib.AbstractAsyncContextManager` with proper overloads, as a protocol.'''
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> bool|None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> bool|None: ...
@type_check_only
class AsyncLockLike[T](AsyncContextManager[T], Protocol):
    '''An object that behaves like an asynchronous lock.'''
    async def acquire(self) -> bool|None: ...
    def release(self) -> Awaitable[None]|None: ...
    def locked(self) -> bool: ...
@type_check_only
class GenericSized[T](Protocol):
    '''`typing.Sized` is not generic, so here is a generic version of it.'''
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
@type_check_only
class SupportsSlicing[T](GenericSized[T], Protocol):
    '''Protocol for iterables with size, and index and slice access.'''
    @overload
    def __getitem__(self, idx: ValidSlice, /) -> Self: ...
    @overload
    def __getitem__(self, idx: SupportsIndex, /) -> T: ...
    def __len__(self) -> int: ...
    def __reversed__(self) -> Iterator[T]: '''The requirements for this protocol makes its conformants automatically reversible.'''
@type_check_only
class CanClearAndCopy[T](Protocol):
    '''An iterable that supports clearing and shallow copying.'''
    def copy(self) -> Self: ...
    def clear(self) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
@type_check_only
class PathLike[T](Protocol):
    '''An object that represents a path. Basically os.PathLike, but a Protocol.'''
    def __fspath__(self) -> T: ...
@type_check_only
class SupportsPop[T](Protocol):
    '''Self-explanatory.'''
    def pop(self) -> T: ...
@type_check_only
class SupportsPopLeft[T](Protocol):
    '''Self-explanatory.'''
    def popleft(self) -> T: ...
@type_check_only
class GeneratorCoroutine[Y, S, R](Generator[Y, S, R], Coroutine[Y, S, R]):
    '''Objects such as those returned by `types.coroutine`-decorated generator functions.'''
    def send(self, val: S, /) -> Y: ...
    @overload # type: ignore[override]
    def throw(self, typ: ValidExcType, val: BaseException|None=..., tb: TracebackType|None=..., /) -> Y: ...
    @overload
    def throw(self, val: BaseException, /) -> Y: ...
    def close(self) -> None: ...
    def __await__(self) -> Generator[Any, None, R]: ...
@type_check_only
class PartialInterfaceMeta(type):
    '''Metaclass for 'partial interfaces', described below.'''
    def __getattr__(cls, name: str, /) -> Any: ...
@type_check_only
class PartialInterface(metaclass=PartialInterfaceMeta):
    '''Base class for partial interfaces.
    If it is only known that a class implements an interface (e.g. the PEP 3148 Future interface), type checkers might throw errors on unrecognized attributes
    that may actually exist on the object/class. This is a simplistic fix that assumes those attributes always exist, with type Any.'''
    def __init__(self, *a: Any, **k: Any): ...
    def __getattr__(self, name: str, /) -> Any: ...
@type_check_only
class DumpType(Protocol):
    '''Represents the type of simple json-dumping functions accepted by tools.argv_to_json and tools.argstr_to_json.'''
    def __call__(self, dct: dict[str, Any], file: TextIOWrapper[_WrappedBuffer], /) -> None: ...
@type_check_only
class CanWriteAndFlush[T](Protocol):
    '''A writable and flushable 'stream'.'''
    def flush(self) -> None: ...
    def write(self, s: T, /) -> int|None: ...
@type_check_only
class SigPatcher(Protocol):
    '''Type of functions with a specific signature in the semi-public API of this module, used to alter function signatures.'''
    def __call__(self, *to_patch: tuple[FunctionType, str]) -> None: ...
@type_check_only
class Middleware(Protocol):
    '''Represents a middleware accepted by `channels.EventBus`.
    To facilitate O(1) removal of middlewares and order preservation, it is unfortunately impossible to add the same middleware into the pipe twice.
    Therefore, it is suggested that a lightweight wrapper lambda around a function containing the main logic be used.'''
    def __call__(self, event_type: str, data: Any, /) -> Any: ...
    def __hash__(self) -> int: ...
@type_check_only
class SupportsMatMul(Protocol):
    '''A class that supports matrix multiplication.'''
    def __matmul__(self, other: Self) -> Self: ...
@type_check_only
class MemoryMappedFile(LoopContextMixin):
    '''Not exposed; calls itself `asyncutils.io.file`.'''
    if sys.platform != 'win32':
        def madvise(self, option: int, start: int=..., length: int|None=...) -> None: ...
    async def reg(self, m: mmap, /) -> None: ...
    async def unreg(self, m: mmap, /) -> None: ...
    async def read(self, offset: int=..., size: int=...) -> bytes: ...
    async def write(self, data: bytes, offset: int=...) -> None: ...
    async def readline(self, offset: int=..., size: int|None=..., incl_newline: bool=...) -> bytes: ...
    async def readlines(self, hint: int=...) -> list[bytes]: ...
    async def flush(self, offset: int=..., size: int|None=..., /) -> None: ...
    async def move(self, dest: int, src: int, count: int) -> None: ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
    async def seek(self, pos: int, whence: _Seek=...) -> None: ...
    def __new__(cls, file: IO[bytes], /) -> Self: ...
    def __iter__(self) -> Iterator[bytes]: ...
    @property
    def mmap(self) -> mmap: ...
    @property
    def closed(self) -> bool: ...
    @property
    def open_files(self) -> OpenFiles: ...
    def fileno(self) -> int: ...
    def sync(self) -> None: ...
    async def close(self) -> None: ...
    def read_byte(self) -> int: ...
    def write_byte(self, b: int, /) -> None: ...
    def resize(self, newsize: int) -> None: ...
    def find(self, sub: bytes, start: int|None=..., end: int|None=...) -> int: ...
    def rfind(self, sub: bytes, start: int|None=..., end: int|None=...) -> int: ...
    def tell(self) -> int: ...
    def size(self) -> int: ...
    def isatty(self) -> bool: ...
    def readable(self) -> Literal[True]: ...
    def writable(self) -> Literal[True]: ...
    def seekable(self) -> Literal[True]: ...
    async def writelines(self, lines: Iterable[bytes], /, *, sep: bytes=...) -> None: ...
    async def read_str(self, offset: int=..., size: int=..., encoding: str=..., errors: str=...) -> str: ...
    async def write_str(self, text: str, offset: int=..., encoding: str=..., errors: str=...) -> None: ...
    async def smart_write(self, data: str|bytes, offset: int=...) -> None: ...
    async def copy_range(self, src_offset: int, dest_offset: int, size: int) -> bool: ...
    async def fill(self, pattern: bytes, offset: int=..., count: int=...) -> None: ...
    async def compare(self, other: Self, /, size: int=..., offset_self: int=..., offset_other: int=...) -> bool: ...
    async def hamming_dist(self, other: Self, /, size: int=..., offset_self: int=..., offset_other: int=...) -> int: ...
    async def read_until(self, delim: bytes, offset: int=..., maxsize: int=...) -> tuple[bytes, int]: ...
    async def insert(self, data: bytes, offset: int) -> None: ...
    async def delete(self, offset: int, size: int) -> None: ...
    async def replace(self, old: bytes, new: bytes, offset: int=..., count: int=...) -> int: ...
    def search_lazy(self, pattern: bytes, offset: int=..., max_results: int=...) -> AsyncGenerator[int]: ...
    def search_lazy_nonoverlapping(self, pattern: bytes, offset: int=..., max_results: int=...) -> AsyncGenerator[int]: ...
    async def search(self, pattern: bytes, offset: int=..., max_results: int=...) -> list[int]: ...
    async def search_nonoverlapping(self, pattern: bytes, offset: int=..., max_result: int=...) -> list[int]: ...
    async def compact(self) -> None: ...
@final
@type_check_only
class Sentinel(sentinel_base):
    '''Common type of sentinels for this module, internal or public.'''
    def __reduce__(self) -> str: '''These sentinels are accessible in the top level of the asyncutils.constants namespace.''' # type: ignore[override]
type IntCompatible = str|SupportsInt|SupportsIndex|Buffer
'''Objects accepted by the int constructor.'''
type SupportsIteration[T] = Iterable[T]|AsyncIterable[T]
'''Objects that support (async) iteration.'''
type SupportsRichComparison = SupportsLT|SupportsGT
'''Self-explanatory.'''
type ValidExcType = type[BaseException]
'''The type of exc_typ in __exit__ and __aexit__ methods.'''
type Exceptable = ValidExcType|tuple[ValidExcType, ...]
'''Objects that may follow an except statement.'''
type Openable = int|str|bytes|PathLike[str]|PathLike[bytes]
'''Anything that can normally be passed to the built-in open function.'''
type ValidSlice = slice[SupportsIndex|None, SupportsIndex|None, SupportsIndex|None]
'''A slice with start, stop and step being integers or None, representing a slice that typical sequences supporting slicing should accept.'''
type Timer = Callable[[], float]
'''Type of functions that return the current time under some specification, such as time.monotonic, time.process_time and time.perf_counter.'''
type All = tuple[str, ...]
'''Type of the `__all__` attributes of asyncutils' submodules.'''
type Submodule = Literal['altlocks', 'base', 'buckets', 'caches', 'channels', 'cli', 'compete', 'config', 'console', 'constants', 'context', 'events', 'exceptions', 'func', 'futures', 'io', 'iterclasses', 'iters', 'locks', 'misc', 'mixins', 'networking', 'pools', 'processors', 'properties', 'queues', 'signals', 'tools', 'util', 'version']
'''Type of strings representing asyncutils submodule names.'''
type Executor = Literal['thread', 'process', 'interpreter', 'loky_noreuse', 'loky', 'dask', 'ipython', 'elib_flux_cluster', 'elib_flux_job', 'elib_slurm_cluster', 'elib_slurm_job', 'elib_single_node', 'pebble_thread', 'pebble_process']
'''Type of strings representing executors that can be passed to -e/--executor.'''
type HashAlgorithm = Literal['md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512', 'blake2b', 'blake2s', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'shake_128', 'shake_256']
'''Names of algorithms used for calculating checksums. Default is blake2s, which is fast and somewhat secure with a low probability of collision.'''
type OpenRV = _AsyncGeneratorContextManager[MemoryMappedFile, None]
'''The type of the return values of the `open`, `create` and `create_sparsef` methods of `io.MemoryMappedIOManager`.'''
type OpenFiles = dict[tuple[TextIOWrapper[_WrappedBuffer], Literal['r+b', 'w+b', 'x+b']], MemoryMappedFile]
if sys.platform == 'win32': type _Seek = Literal[0, 1, 2]
else: type _Seek = Literal[0, 1, 2, 3, 4]
ExceptionWrapper = NewType('ExceptionWrapper', object)
'''Does not exist at runtime.'''
WildcardType = NewType('WildcardType', None) # type: ignore[valid-newtype]
'''Does not exist at runtime.'''