'''Defines interfaces and type aliases that don't actually exist and are only used in this module's stubs, any of which may be removed without notice.
At runtime, accessing any name in this module returns None, so that inline type annotations are possible as well.'''
from types import TracebackType
from _collections_abc import Awaitable, Iterator, Iterable, AsyncIterable, Callable, Generator, Coroutine, Buffer
from typing import Protocol, Self, SupportsIndex, SupportsInt, Any, Literal, overload, type_check_only
from io import TextIOWrapper, _WrappedBuffer
@type_check_only
class SupportsLT(Protocol):
    def __lt__(self, other: Self, /) -> bool: ...
@type_check_only
class SupportsGT(Protocol):
    def __gt__(self, other: Self, /) -> bool: ...
@type_check_only
class AsyncContextManager[T](Protocol):
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> bool|None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> bool|None: ...
@type_check_only
class AsyncLockLike(AsyncContextManager, Protocol):
    async def acquire(self) -> bool|None: ...
    def release(self) -> None|Awaitable[None]: ...
    def locked(self) -> bool: ...
@type_check_only
class SupportsSlicing[T](Protocol):
    @overload
    def __getitem__(self, idx: ValidSlice, /) -> GenericSized[T]: ...
    @overload
    def __getitem__(self, idx: SupportsIndex, /) -> T: ...
    def __len__(self) -> int: ...
    def __reversed__(self) -> Iterator[T]: ...
@type_check_only
class GenericSized[T](Protocol):
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
@type_check_only
class CanClearAndCopy[T](Protocol):
    def copy(self) -> Self: ...
    def clear(self) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
@type_check_only
class PathLike[T](Protocol):
    def __fspath__(self) -> T: ...
@type_check_only
class SupportsPop[T](Protocol):
    def pop(self) -> T: ...
@type_check_only
class SupportsPopLeft[T](Protocol):
    def popleft(self) -> T: ...
@type_check_only
class GeneratorCoroutine[Y, S, R](Coroutine[S, R, Y], Generator[Y, S, R]): ...
@type_check_only
class PartialInterfaceMeta(type):
    def __getattr__(cls, name: str, /) -> Any: ...
@type_check_only
class PartialInterface(metaclass=PartialInterfaceMeta):
    def __init__(self, *a: Any, **k: Any): ...
    def __getattr__(self, name: str, /) -> Any: ...
@type_check_only
class DumpType(Protocol):
    def __call__(self, dct: dict[str, Any], file: TextIOWrapper[_WrappedBuffer], /) -> None: ...
@type_check_only
class CanWriteAndFlush[T](Protocol):
    def flush(self) -> None: ...
    def write(self, s: T, /) -> None: ...
type IntCompatible = str|SupportsInt|SupportsIndex|Buffer
type SupportsIteration[T] = Iterable[T]|AsyncIterable[T]
type SupportsRichComparison = SupportsLT|SupportsGT
type ValidExcType = type[BaseException]
type Exceptable = ValidExcType|tuple[ValidExcType, ...]
type Openable = int|str|bytes|PathLike[str]|PathLike[bytes]
type ValidSlice = slice[SupportsIndex|None, SupportsIndex|None, SupportsIndex|None]
type Timer = Callable[[], float]
type All = tuple[str, ...]
type Submodule = Literal['altlocks', 'base', 'buckets', 'caches', 'channels', 'cli', 'compete', 'config', 'console', 'constants', 'events', 'exceptions', 'func', 'futures', 'io', 'iterclasses', 'iters', 'locks', 'misc', 'mixins', 'networking', 'pools', 'processors', 'properties', 'queues', 'signals', 'tools', 'util', 'version']