'''Backport of :class:`asyncio.Queue` with a `shutdown` method to python 3.12 or under.'''
import sys
if sys.version_info < (3, 13):
    from asyncio.queues import Queue as BaseQueue
    __all__ = 'LifoQueue', 'PriorityQueue', 'Queue', 'QueueEmpty', 'QueueFull', 'QueueShutDown'
    class QueueEmpty(Exception): ...
    class QueueFull(Exception): ...
    class QueueShutDown(Exception): ...
    class Queue[T](BaseQueue[T]):
        def shutdown(self, immediate: bool=...) -> None: ...
    class LifoQueue[T](Queue[T]): ...
    class PriorityQueue[T](Queue[T]): ...