'''Backport of asyncio.Queue with a shutdown method to python 3.12 or under.'''
from asyncio.queues import Queue as Q
__all__ = 'Queue', 'QueueShutDown', 'QueueEmpty', 'QueueFull', 'LifoQueue', 'PriorityQueue'
class QueueEmpty(Exception): ...
class QueueFull(Exception): ...
class QueueShutDown(Exception): ...
class Queue[T](Q[T]):
    def shutdown(self, immediate: bool=...) -> None: ...
class LifoQueue[T](Queue[T]): ...
class PriorityQueue[T](Queue[T]): ...