'''Backport of :class:`functools.partial` that supports placeholders, as well as max-heap variants of :mod:`heapq` functions, to python 3.13 or under.'''
import sys
assert sys.version_info < (3, 14)
from functools import partial
from typing import Final
from .types import SupportsRichComparison
__all__ = 'Placeholder', 'heapify', 'heappop', 'heappush', 'heappushpop', 'heapreplace', 'partial'
Placeholder: Final[object]
def heapify[C: SupportsRichComparison](heap: list[C], /) -> None: ...
def heappop[C: SupportsRichComparison](heap: list[C], /) -> C: ...
def heappush[C: SupportsRichComparison](heap: list[C], item: C, /) -> None: ...
def heappushpop[C: SupportsRichComparison](heap: list[C], item: C, /) -> C: ...
def heapreplace[C: SupportsRichComparison](heap: list[C], item: C, /) -> C: ...