'''Backport of :class:`asyncio.Queue` with a :meth:`shutdown` method to python 3.12 or under.'''
from asyncio.queues import Queue as BaseQueue
__all__ = 'LifoQueue', 'PriorityQueue', 'Queue', 'QueueEmpty', 'QueueFull', 'QueueShutDown'
class QueueEmpty(Exception): ...
class QueueFull(Exception): ...
class QueueShutDown(Exception): ...
class Queue[T](BaseQueue[T]):
    def shutdown(self, immediate: bool=...) -> None: ...
class LifoQueue[T](Queue[T]): ...
class PriorityQueue[T](Queue[T]): ...