'''Submodule managing the current running :mod:`asyncutils` console. No more thread safe than is necessary.

.. caution:: These functions are internal and unstable. Do not call any of them or risk corrupting module state.'''
from ..console import AsyncUtilsConsole as Console
def getc() -> Console|None: ...
def setc(console: Console, /) -> None: ...
def unsetc() -> Console|None: ...
def should_write_load_all() -> bool: ...
def request_write_load_all() -> None: ...
