'''Manages the current running :mod:`asyncutils` console.'''
from ..console import AsyncUtilsConsole as Console
from typing import Any
def _get_() -> Console|None: ...
def _set_(console: Console, /) -> None: ...
def _unset_() -> Console|None: ...
def _should_write_load_all_() -> bool: ...
def _request_write_load_all_() -> None: ...
def __getattr__(name: str, /) -> Any: ...