'''Ugly patch to manage the current running asyncutils console.'''
from typing import Any
from ..console import AsyncUtilsConsole as Console
def _get_() -> Console|None: ...
def _set_(cons: Console, /) -> None: ...
def _unset_() -> Console|None: ...
def _should_write_load_all_() -> bool: ...
def _request_write_load_all_() -> None: ...
def __getattr__(name: str, /) -> Any: ...