#!/usr/bin/env bash
set -e
DATE=$(date -u "+%Y-%m-%d %H:%M:%S")
exec > docs/source/help.rst
echo "CLI Usage
=========

This is the contents of a file to which the help command from the command-line interface is redirected, as of $(python3 -m asyncutils -v)::
"
python3 -m asyncutils -h | sed '/^$/! s/^/  /'

if [ "$READTHEDOCS" = "True" ]; then echo "
.. note:: Generated by scripts/unix/genhelp.sh in Read the Docs $READTHEDOCS_VERSION build at $DATE UTC."
else echo "
.. note:: Preview generated by scripts/unix/genhelp.sh at $DATE UTC. DO NOT COMMIT."
fi
