#!/bin/bash
set -e
exec > docs/source/help.rst
echo "CLI Usage
=========

This is the contents of a file to which the help command from the command-line interface is redirected, as of $(python3 -m asyncutils -v)::
"
python3 -m asyncutils -h | sed '/^$/! s/^/  /'

if [ "$READTHEDOCS" = "True" ]; then echo "
.. note:: Generated by scripts/unix/genhelp.sh in Read the Docs build at $(date -u "+%Y-%m-%d %H:%M:%S") UTC."
else echo "
.. note:: Preview generated by scripts/unix/genhelp.sh at $(date -u "+%Y-%m-%d %H:%M:%S") UTC. DO NOT COMMIT."
fi
