#!/bin/bash
set -e
exec > docs/source/makefile-usage.rst
cat assets/mkpream.txt
echo "
Below is the Makefile help as of $(python3 -m asyncutils -v)::
"
cat assets/mkhelp.txt | sed '/^$/! s/^/  /'
if [ "$READTHEDOCS" = "True" ]; then echo "
.. note:: Generated by scripts/unix/genmakefileusage.sh in Read the Docs build at $(date -u "+%Y-%m-%d %H:%M:%S") UTC."
else echo "
.. note:: Preview generated by scripts/unix/genmakefileusage.sh at $(date -u "+%Y-%m-%d %H:%M:%S") UTC. DO NOT COMMIT."
fi
