repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: file-contents-sorter
        files: ^(\.github/CODEOWNERS|asyncutils/_internal/submodules\.py)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-check
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2
    hooks:
      - id: sphinx-lint
        args: [--enable, default-role]