$ErrorActionPreference = "Stop"
$v = python3 -m asyncutils -v
$h = python3 -m asyncutils -h
$d = Get-Date -AsUTC -Format "yyyy-MM-dd HH:mm:ss"
$c = @"
CLI Usage
=========

.. version-added:: 0.9.6

.. version-changed:: 0.9.9
  Removed help.rst from version control. The Read the Docs build now generates it automatically.

This is the contents of a file to which the help command from the command-line interface is redirected, as of $v::`n`n
"@
$i = foreach ($l in $h -split "`r`n") {if ($l -eq "") {""} else {"  $l"}}
$c += $i -join "`r`n"
$c += "`n`n.. note:: Preview generated by scripts/win/genhelp.ps1 at $d. DO NOT COMMIT."
$c | Out-File -FilePath "docs/source/help.rst" -Encoding utf8
