$ErrorActionPreference = "Stop"
$v = python3 -m asyncutils -v
$h = python3 -m asyncutils -h
$i = foreach ($l in $h -split "`r`n") {if ($l -eq "") {""} else {"  $l"}}
$d = Get-Date -AsUTC -Format "yyyy-MM-dd HH:mm:ss"
"CLI Usage`n=========`n`nThis is the contents of a file to which the help command from the command-line interface is redirected, as of $v::`n`n"+($i -join "`r`n")+"`n`n.. note:: Preview generated by scripts/win/genhelp.ps1 at $d UTC. DO NOT COMMIT." | Out-File "docs/source/help.rst" -Encoding utf8
