$ErrorActionPreference = "Stop"
$v = python3 -m asyncutils -v
$h = Get-Content -Path "assets\mkhelp.txt"
$d = Get-Date -AsUTC -Format "yyyy-MM-dd HH:mm:ss"
$c = Get-Content -Path "assets\mkpream.txt"
$c += "`nBelow is the Makefile help as of $v::`n"
$i = foreach ($l in $h -split "`r`n") {if ($l -eq "") {""} else {"  $l"}}
$c += $i -join "`r`n"
$c += "`n.. note:: Preview generated by scripts/win/genmakefileusage.ps1 at $d. DO NOT COMMIT."
$c | Out-File -FilePath "docs/source/makefile-usage.rst" -Encoding utf8
