$ErrorActionPreference = "Stop"
$v = python3 -m asyncutils -v
$h = Get-Content -Path "assets\mkhelp.txt"
$i = foreach ($l in $h -split "`r`n") {if ($l -eq "") {""} else {"  $l"}}
$d = Get-Date -AsUTC -Format "yyyy-MM-dd HH:mm:ss"
(Get-Content -Path "assets\mkpream.txt")+"`nBelow is the Makefile help as of $v::`n"+($i -join "`r`n")+"`n.. note:: Preview generated by scripts/win/genmakefileusage.ps1 at $d UTC. DO NOT COMMIT." | Out-File "docs/source/makefile-usage.rst" -Encoding utf8
