$ErrorActionPreference = "Stop"
$v = python3 -m asyncutils -v
$h = Get-Content -Path "make.help"
$d = Get-Date -AsUTC -Format "yyyy-MM-dd HH:mm:ss"
$c = @"
Using the Makefile
==================

.. highlight:: none

.. version-added:: 0.9.8

make.bat on Windows, or the Makefile otherwise, is often a handy companion in development. It makes development less dry, repetitive and error-prone,
and the process as a whole more smooth-sailing.

This is partly also to compensate for the lack of a setup.py after adaptation of the standardized pyproject.toml; see :pep:``621`` and ``the official
PyPA guide <https://packaging.python.org/en/latest/guides/writing-pyproject-toml>``__ for more. Note that the Makefile is not intended to be used by
end-users, but rather by developers, and it obviously requires GNU Make.

.. version-changed:: 0.9.9
  Removed help.rst and makefile-usage.rst from version control. The Read the Docs build now generates them automatically.

.. version-added:: 0.9.7
  Created make.bat at the project root, such that developers on Windows can achieve a close equivalent of using the Makefile.

.. version-changed:: 0.9.5
  Used more of uv in the Makefile.

.. version-added:: 0.9.0
  Created a Makefile to simplify development chores.

If you are in powershell, ````make```` will not work directly and you must use ````.\make.bat```` instead, which is more verbose; thus, you are strongly
advised to develop in cmd.exe, the traditional command prompt.

Below is the Makefile help as of $v::`n`n
"@
$i = foreach ($l in $h -split "`r`n") {if ($l -eq "") {""} else {"  $l"}}
$c += $i -join "`r`n"
$c += "`n`n.. note:: Preview generated by scripts/win/genmakefileusage.ps1 at $d. DO NOT COMMIT."
$c | Out-File -FilePath "docs/source/makefile-usage.rst" -Encoding utf8
