__import__('sys').path.insert(0, __import__('os').path.abspath('../..'))
project = 'asyncutils'
author = 'Jonathan Dung'
copyright = '2026-%Y Jonathan Dung'
version = '0.9'
release = '0.9.1'
need_sphinx = '9.1.0'
default_role = 'py:obj'
extensions = ['sphinx.ext.viewcode', 'autoapi.extension']
suppress_warnings = ['autoapi.python_import_resolution', 'toc.not_readable']
html_static_path = ['_static']
html_css_files = ['custom.css']
html_theme = 'furo'
pygments_style = 'sphinx'
autoapi_dirs = ['../../asyncutils']
autoapi_file_patterns = ['*.pyi']
autoapi_ignore = ['*/_internal/helpers.pyi', '*/_internal/initialize.pyi', '*/_internal/log.pyi', '*/_internal/compat.pyi', '*/_internal/py312.pyi', '*/_internal/py313.pyi', '*/_internal/log.pyi', '*/_internal/compat.pyi', '*/_internal/py312.pyi', '*/_internal/running_console.pyi', '*/_internal/submodules.pyi']
autoapi_member_order = 'groupwise'
autoapi_options = ['members', 'undoc-members', 'show-inheritance', 'show-module-summary', 'special-members']
autoapi_python_class_content = 'both'
autoapi_root = 'api'