__import__('sys').path.insert(0, __import__('os.path', fromlist=('',)).abspath('../..'))
project = 'asyncutils'
author = 'Jonathan Dung'
copyright = '2026-%Y Jonathan Dung'
version = '0.8'
release = '0.8.20'
need_sphinx = '9.1.0'
pygments_style = 'sphinx'
html_theme = 'sphinx_rtd_theme'
autodoc_typehints = 'none'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode', 'sphinx_autodoc_typehints']