#!/usr/bin/env bash
set -e
v=$(asyncutils -v)
t=$(date -u "+%Y-%m-%d %H:%M:%S")
if [ "$READTHEDOCS" = "True" ]; then m="
.. note:: Generated by scripts/generate.sh in the $READTHEDOCS_VERSION Read the Docs build at $t UTC."
else m="
.. note:: Preview generated by scripts/generate.sh at $t UTC. DO NOT COMMIT."
fi
exec > docs/source/bug-help.rst
echo "Bug Reporting
=============

.. version-added:: 1.1.3

The \`\`asyncutils bug\`\` command, which calls :func:\`~asyncutils.cli.bug\` under the hood, is used to assist ticket submission to the GitHub issue
tracker for :mod:\`asyncutils\`. It utilizes the GitHub issue form schema to grab environment information the bug report needs, such that you need
not enter them manually, making for better UX and easier debugging.

This is the help output for the bug report subcommand, as of $v::
"
asyncutils bug -h | sed '/^$/! s/^/  /'
echo "$m"
exec > docs/source/help.rst
echo "CLI Usage
=========

This is the output of ``asyncutils --help``, as of $v::
"
asyncutils -h | sed '/^$/! s/^/  /'
echo "$m"
exec > docs/source/makefile-usage.rst
cat assets/mkpream.txt
echo "
Below is the Makefile help as of $v::
"
cat assets/mkhelp.txt | sed '/^$/! s/^/  /'
echo "$m"
curl -Z -o docs/source/ai-use.md https://raw.githubusercontent.com/jonathandung/.github/main/AI_USAGE_POLICY.md -o docs/source/conduct.md https://raw.githubusercontent.com/jonathandung/.github/main/CODE_OF_CONDUCT.md -o docs/source/contributing.md https://raw.githubusercontent.com/jonathandung/.github/main/CONTRIBUTING.md
for p in CHANGELOG.md:changelog.md COMPATIBILITY.rst:compat.rst EXAMPLES.rst:examples.rst ROADMAP.md:roadmap.md SECURITY.md:security.md SUPPORT.md:support.md;
  do cp "${p%:*}" "docs/source/${p#*:}"; done
