$ErrorActionPreference = "Stop"
if ($PSVersionTable.PSVersion -ge [version]'7.4.0') {$PSNativeCommandUseErrorActionPreference = $true}
function Indent {
    [CmdletBinding()]
    param([Parameter(Mandatory, ValueFromPipeline)][AllowEmptyString()][string]$s)
    process {if ($s -eq "") {""} else {"  $s"}}
}
$v = asyncutils -v
$m = "`n.. note:: Preview generated by scripts\generate.ps1 at $([datetime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss")) UTC. DO NOT COMMIT."
"Bug Reporting`n=============`n`n.. version-added:: 1.1.3`n`nThe ````asyncutils bug```` command, which calls :func:``~asyncutils.cli.bug`` under the hood, is used to assist ticket submission to the GitHub issue tracker for :mod:``asyncutils``. It utilizes the GitHub issue form schema to grab environment information the bug report needs, such that you need not enter them manually, making for better UX and easier debugging.`n`nThis is the help output for the bug report subcommand, as of $v::`n`n$(asyncutils bug -h | Indent | Out-String)$m" | Out-File "docs/source/bug-help.rst" -Encoding utf8
"CLI Usage`n=========`n`nThis is the output of ````asyncutils --help````, as of $v::`n`n$(asyncutils -h | Indent | Out-String)$m" | Out-File "docs/source/help.rst" -Encoding utf8
"$(Get-Content -Path "assets\mkpream.txt" | Out-String)`nBelow is the Makefile help as of $v::`n`n$(Get-Content -Path "assets\mkhelp.txt" | Indent | Out-String)$m" | Out-File "docs/source/makefile-usage.rst" -Encoding utf8
@("AI_USAGE_POLICY.md:ai-use.md","CHANGELOG.md:changelog.md","CODE_OF_CONDUCT.md:conduct.md","COMPATIBILITY.rst:compat.rst","CONTRIBUTING.md:contributing.md","EXAMPLES.rst:examples.rst","ROADMAP.md:roadmap.md","SECURITY.md:security.md","SUPPORT.md:support.md") | ForEach-Object { $s,$d = $_ -split ':',2; Copy-Item $s "docs/source/$d" }
