#!/bin/bash
set -e
echo "CLI Usage
=========

.. version-added:: 0.9.6

.. version-changed:: 0.9.9
  Removed help.rst from version control. The Read the Docs build now generates it automatically.

This is the contents of a file to which the help command from the command-line interface is redirected, as of $(python3 -m asyncutils -v).

.. note:: Generated by scripts/genhelp.sh at $(date -u "+%Y-%m-%d %H:%M:%S") UTC.

::

$(python3 -m asyncutils -h | sed '/^$/! s/^/  /')" > docs/source/help.rst
