#!/bin/bash
set -e
echo "Using the Makefile
==================

.. version-added:: 0.9.8

make.bat on Windows, or the Makefile otherwise, is often a handy companion in development. It makes development less dry, repetitive and error-prone,
and the process as a whole more smooth-sailing.

This is partly also to compensate for the lack of a setup.py after adaptation of the standardized pyproject.toml; see :pep:\`621\` and \`the official
PyPA guide <https://packaging.python.org/en/latest/guides/writing-pyproject-toml>\`__ for more. Note that the Makefile is not intended to be used by
end-users, but rather by developers.

.. version-changed:: 0.9.9
  Removed makefile-usage.rst from version control. The Read the Docs build now generates it automatically.

.. version-added:: 0.9.7
  Created make.bat at the project root, such that developers on Windows can achieve a close equivalent of using the Makefile.

.. version-changed:: 0.9.5
  Used more of uv in the Makefile.

.. version-added:: 0.9.0
  Created a Makefile to simplify development chores.

If you are in powershell, \`\`make\`\` will not work directly and you must use \`\`.\make.bat\`\` instead, which is more verbose; thus, you are strongly
advised to develop in cmd.exe, the traditional command prompt.

Below is the Makefile help as of $(python3 -m asyncutils -v).

.. note:: Generated by scripts/genmakefileusage.sh at $(date -u "+%Y-%m-%d %H:%M:%S") UTC.

::

$(make help | sed '/^$/! s/^/  /')" > docs/source/makefile-usage.rst
