from .mixins import AsyncContextMixin, AwaitableMixin
from ._internal.protocols import Exceptable, SupportsIteration, Timer, ValidExcType
from types import TracebackType
from _collections_abc import Awaitable, Coroutine, Callable
from typing import Any, Literal, Self, overload
from collections import deque
from asyncio.locks import BoundedSemaphore
__all__ = 'CircuitBreaker', 'DynamicBoundedSemaphore', 'DynamicThrottle', 'ResourceGuard', 'StatefulBarrier', 'UniqueResourceGuard'
class DynamicBoundedSemaphore(BoundedSemaphore):
    def __init__(self, value: int=...): ...
    @property
    def bound(self) -> int: ...
    @bound.setter
    def bound(self, value: int, /) -> None: ...
class ResourceGuard(RuntimeError, AsyncContextMixin):
    @property
    def guarded(self) -> bool: ...
    def __init__(self, action: str=..., rname: Any=...): ...
    async def __aenter__(self) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    @classmethod
    def guard(cls, obj: Any, /, *, action: str=...) -> Self: ...
class UniqueResourceGuard(ResourceGuard): _cache: dict[int, Self]
class CircuitBreaker:
    @property
    def name(self) -> str: ...
    @property
    def fails(self) -> int: ...
    def _init_lock(self) -> None: ...
    def _set(self, state: Literal[0, 1, 2], /) -> None: ...
    @overload
    def __new__(cls, name: str, /, max_fails: int=..., reset: float|None=..., exc: Exceptable=..., max_half_open_calls: int|None=...) -> Self: ...
    @overload
    def __new__[T, **P](cls, f: Callable[P, Awaitable[T]], /, max_fails: int=..., reset: float|None=..., exc: Exceptable=..., max_half_open_calls: int|None=...) -> Callable[P, Coroutine[Any, Any, T]]: ...
    def __call__[T, **P](self, f: Callable[P, Awaitable[T]], /, timer: Timer=..., default: T=...) -> Callable[P, Coroutine[Any, Any, T]]: ...
class StatefulBarrier[T=Any](AwaitableMixin):
    def __init__(self, parties: int, name: str=..., initstate: SupportsIteration[T]=..., maxstate: int|None=...): ...
    async def wait(self, state: T=..., timeout: float|None=...) -> tuple[int, deque[T]]: ...
    def _reset(self) -> None: ...
    def abort(self) -> None: ...
    def raise_for_abort(self) -> None: ...
    @property
    def parties(self) -> int: ...
    @property
    def broken(self) -> bool: ...
    @property
    def remaining_parties(self) -> int: ...
class DynamicThrottle:
    def __init__(self, init_rate: float, min_rate: float=..., max_rate: float=..., window: int|None=..., *, ubound: float|None=..., lbound: float|None=..., ufactor: float|None=..., lfactor: float|None=..., jitter: float|None=..., timer: Timer=..., rand: Callable[[float], float]=...): ...
    @property
    def rate(self) -> float: ...
    @rate.setter
    def rate(self, rate: float, /) -> None: ...
    @property
    def jitter(self) -> float: ...
    @jitter.setter
    def jitter(self, jitter, /) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def window(self) -> int: ...
    @property
    def successes(self) -> int: ...
    @property
    def fails(self) -> int: ...
    @property
    def ubound(self) -> float: ...
    @property
    def lbound(self) -> float: ...
    @property
    def ufactor(self) -> float: ...
    @property
    def lfactor(self) -> float: ...
    async def __aenter__(self) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    def reset(self) -> None: ...