from typing import ClassVar, Self, Literal, Awaitable, Any, overload
from _collections_abc import Callable, AsyncGenerator, AsyncIterator, AsyncIterable, Generator, Iterator, Iterable
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from types import TracebackType
from .config import _sentinel
from ._internal.protocols import ValidExcType, SupportsPop, SupportsPopLeft, SupportsIteration, GeneratorCoroutine
__all__ = 'event_loop', 'iter_to_aiter', 'aiter_to_iter', 'adisembowel', 'adisembowelleft', 'safe_cancel_batch', 'collect', 'take', 'drop', 'aenumerate', 'yield_to_event_loop', 'dummy_task'
class event_loop:
    '''A context manager to manage lifecycles of asyncio-native event loops. Initialization arguments are self-explanatory.'''
    _ENTERED: ClassVar[int]
    _SHOULD_CLOSE: ClassVar[int]
    _INNER_EXIT: ClassVar[int]
    _INNER_AEXIT: ClassVar[int]
    _INTERNAL_MASK: ClassVar[int]
    _reusable: list[AbstractEventLoop]
    def _get_unclosed_loop(self, factory: Callable[[], AbstractEventLoop]) -> AbstractEventLoop: ...
    def clear_flags(self, mask_to_keep: int=...) -> None: ...
    def copy_flags(self) -> Self: ...
    @classmethod
    def from_flags(cls, flags: int, /) -> Self: ...
    def __new__(cls, *, dont_release_loop_on_finalization: bool=..., silent_on_finalize: bool=..., check_running: bool=..., dont_always_stop_on_exit: bool=..., close_existing_on_exit: bool=..., dont_close_created_on_exit: bool=..., cancel_all_tasks: bool=..., keep_loop: bool=..., suppress_runtime_errors: bool=..., fail_silent: bool=..., dont_allow_reuse: bool=..., dont_reuse: bool=..., dont_attempt_enter: bool=..., attempt_aenter: bool=..., suppress_inner_exit_on_runtime_error: bool=..., suppress_inner_aexit_on_runtime_error: bool=...) -> Self: ...
    def __enter__(self) -> AbstractEventLoop: ...
    @overload
    def __exit__(self, t: None, v: None, b: None, /) -> Literal[False]: ...
    @overload
    def __exit__(self, t: ValidExcType, v: BaseException, b: TracebackType|None, /) -> bool: ...
    def __del__(self) -> None: ...
    def __reduce__(self) -> tuple[Callable[[int], Self], tuple[int]]: ...
@overload
def iter_to_aiter[T, R](it: AsyncGenerator[T, R]) -> AsyncGenerator[T, R]: ...
@overload
def iter_to_aiter[T, R](it: AsyncGenerator[T, R], sentinel: T) -> AsyncGenerator[T, R]: ...
@overload
def iter_to_aiter[T](it: AsyncIterator[T]) -> AsyncIterator[T]: ...
@overload
def iter_to_aiter[T](it: AsyncIterator[T], sentinel: T) -> AsyncIterator[T]: ...
@overload
def iter_to_aiter[T](it: AsyncIterable[T]) -> AsyncGenerator[T, None]: ...
@overload
def iter_to_aiter[T](it: AsyncIterable[T], sentinel: T) -> AsyncGenerator[T, None]: ...
@overload
def iter_to_aiter[T](it: Iterable[T]) -> AsyncGenerator[T, None]: ...
@overload
def iter_to_aiter[T](it: Iterable[T], sentinel: T) -> AsyncGenerator[T, None]: ...
@overload
def aiter_to_iter[T, R](ait: AsyncGenerator[T, R]) -> Generator[T, R, None]: ...
@overload
def aiter_to_iter[T](ait: AsyncIterable[T]) -> Generator[T, None, None]: ...
@overload
def aiter_to_iter[T](ait: Iterable[T]) -> Generator[T, None, None]: ...
@overload
def aiter_to_iter[T](ait: Iterator[T]) -> Iterator[T]: ...
def adisembowel[T](it: SupportsPop[T], /) -> AsyncGenerator[T, None]: ...
def adisembowelleft[T](it: SupportsPopLeft[T], /) -> AsyncGenerator[T, None]: ...
@overload
async def safe_cancel_batch(t: Iterable[Future], disembowel: Literal[False]=...) -> None: ...
@overload
async def safe_cancel_batch(t: SupportsPop[Future], disembowel: Literal[True]) -> None: ...
@overload
async def collect[T](it: SupportsIteration[T], n: int, default: T) -> list[T]: ...
@overload
async def collect[T](it: SupportsIteration[T], *, default: T) -> list[T]: ...
@overload
async def collect[T](it: SupportsIteration[T], n: int, default: object) -> list[T]: ...
@overload
async def collect[T](it: SupportsIteration[T], *, default: object) -> list[T]: ...
@overload
async def collect[T](it: SupportsIteration[T], n: int) -> list[T]: ...
@overload
async def collect[T](it: SupportsIteration[T]) -> list[T]: ...
@overload
def take[T](it: SupportsIteration[T], n: int, *, default: _sentinel) -> AsyncGenerator[T, None]: ...
@overload
def take[T](it: SupportsIteration[T], n: int, *, default: T) -> AsyncGenerator[T, None]: ...
@overload
def take[T](it: SupportsIteration[T], n: int|None) -> AsyncGenerator[T, None]: ...
def drop[T](it: AsyncIterable[T], n: int, raising: bool=...) -> AsyncGenerator[T, None]: ...
def aenumerate[T](it: SupportsIteration[T], start: int=..., *, step: int=...) -> AsyncGenerator[tuple[int, T], None]: ...
yield_to_event_loop: Awaitable[None]
dummy_task: GeneratorCoroutine[None, Any, Any]