from ._internal.protocols import Timer, ValidExcType
from types import TracebackType
from typing import Self, overload
from .mixins import AsyncContextMixin, EventualLoopMixin
__all__ = 'TokenBucket', 'LeakyBucket'
class TokenBucket:
    def __init__(self, rate: float, capacity: float, timer: Timer=...): ...
    async def consume(self, tokens: float=...) -> None: ...
    @property
    def capacity(self) -> float: ...
class LeakyBucket(AsyncContextMixin, EventualLoopMixin):
    def __init__(self, capacity: float, leak: float, min_factor: float=..., max_factor: float=..., external_factor_settable: bool=..., timer: Timer=...): ...
    async def acquire(self, amount: float=...) -> bool: ...
    async def wait_for_tokens(self, amount: float=...) -> None: ...
    @property
    def factor(self) -> float: ...
    @factor.setter
    def factor(self, value: float, /) -> None: ...
    @factor.deleter
    def factor(self) -> None: ...
    def adjust(self) -> None: ...
    def __enter__(self) -> Self: ...
    @overload
    async def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> None: ...
    @overload
    async def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...