from .mixins import LoopContextMixin
from _collections_abc import Callable
__all__ = 'AsyncLRUCache', 'CacheWithBackgroundRefresh'
class CacheWithBackgroundRefresh(LoopContextMixin):
    def __init__(self, ttl: float|None=..., refresh: float|None=..., processor: Callable[[BaseException, bool]]|None=..., default_loader: Callable|None=...): ...
    def __contains__(self, key) -> bool: ...
    def register_loader(self, key, loader) -> None: ...
    def expired(self, key) -> bool: ...
    def should_refresh(self, key) -> bool: ...
    def time_past(self, key) -> float: ...
    def configure(self, ttl: float, refresh: float, processor: Callable|None=...) -> None: ...
    def get_loader(self, key) -> Callable: ...
    async def get(self, key, loader: Callable|None=None): ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
    async def load_item(self, key) -> None: ...
    async def refresh_item(self, key) -> None: ...
    async def refresh_loop(self) -> None: ...
    async def invalidate(self, key): ...
    async def clear(self) -> None: ...
class AsyncLRUCache:
    def __init__(self, maxsize: int|None=..., ttl: float|None=..., typed: bool=...): ...
    def __call__(self, f: Callable): ...
    def cache_clear(self) -> None: ...