from .mixins import LoopContextMixin
from _collections_abc import Callable, Generator, AsyncGenerator, Mapping, Awaitable, Iterable
from _weakrefset import WeakSet
from collections import defaultdict
from contextlib import _GeneratorContextManager
from typing import Protocol, TypeGuard, Self, Any, Literal, NoReturn, type_check_only, overload
from asyncio.futures import Future
from asyncio.tasks import Task
from asyncio.events import AbstractEventLoop
from asyncio.locks import Lock
from asyncio.queues import Queue
__all__ = 'EventBus', 'Observable', 'Rendezvous'
class Observable[**P](LoopContextMixin):
    @type_check_only
    class _Observer(Protocol):
        async def __call__(self, *a: P.args, **k: P.kwargs) -> Any: ...
    @type_check_only
    class _SubscriptionReturnType(Protocol):
        def __call__(self, strict: bool=...) -> None: ...
    @property
    def idle(self) -> bool: ...
    @property
    def notifying(self) -> bool: ...
    @overload
    async def notify(self, *a: P.args, **k: P.kwargs) -> None: ...
    @overload
    async def notify(self, *a: Any, _ret_exc_: bool=..., **k: Any) -> None: ...
    @overload
    def notify_sequential(self, *a: P.args, **k: P.kwargs) -> AsyncGenerator[Any, None]: ...
    @overload
    def notify_sequential(self, *a: Any, _silent_: bool=..., _persistent_: bool=..., **k: Any) -> AsyncGenerator[Any, None]: ...
    async def wait_for_next(self, timeout: float|None=..., strict: bool=...) -> tuple[tuple[Any, ...], dict[str, Any]]: ...
    async def wait_until_idle(self, timeout: float|None=...) -> None: ...
    async def subscribe(self, observer) -> _SubscriptionReturnType: ...
    async def unsubscribe(self, observer, strict: bool=...) -> None: ...
    async def handle_notifications(self) -> None: ...
    async def handle_unsubscriptions(self) -> None: ...
    def __init__(self, init_observers: Iterable[_Observer]=..., maxsize: int|None=...): ...
    def __iter__(self) -> Generator[_Observer, None, None]: ...
    def __aiter__(self) -> AsyncGenerator[_Observer, None]: ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
    def start_accumulation(self) -> bool: ...
    def restart_accumulation(self, flush: bool=...) -> None: ...
    def flush_notifications(self, timeout: float|None=...) -> None: ...
    def flush_unsubscriptions(self, timeout: float|None=...) -> None: ...
    def subscribe_nowait(self, observer: _Observer) -> _SubscriptionReturnType: ...
    def unsubscribe_eventually(self, observer, asap: bool=...) -> None: ...
    def unsubscribe_nowait(self, observer, strict: bool=...) -> None: ...
    def subscribe_syncf(self, observer: Callable[P]) -> _SubscriptionReturnType: ...
    def ntimes(self, observer: _Observer, n: int=...) -> _SubscriptionReturnType: ...
    def filter(self, pred: Callable[P, bool], ret_exc: bool=...) -> Self: ...
    def map(self, transform: Callable[P, tuple[Iterable[Any], Mapping[str, Any]]], ret_exc: bool=...) -> Observable: ...
    def debounce(self, delay: float, ret_exc: bool=...) -> Self: ...
    def throttle(self, interval: float, ret_exc: bool=...) -> Self: ...
    def buffer(self, count: int, ret_exc: bool=...) -> Self: ...
    def at_change(self, key: Callable[P, Any]|None=..., ret_exc: bool=...) -> Self: ...
    def fork(self, ret_exc: bool=...) -> Self: ...
    def merge(*obs: Self, ret_exc: bool=...) -> Self: ...
class EventBus(LoopContextMixin):
    '''Wildcard subscribers should take the event type as the first argument, and the event data as the next; while specific subscribers should take the event data as the only argument.'''
    @type_check_only
    class _WildcardType:
        def __bool__(self) -> Literal[False]: ...
    WILDCARD: _WildcardType
    def __init__(self, name: str|None=..., *, handler: Callable[[BaseException], None]|None=..., max_concurrent: int=..., bounded: bool=..., tracking_stats: bool=...): ...
    def raise_for_shutdown(self) -> None: ...
    def get_event_stats(self) -> defaultdict[str, int]: ...
    @overload
    def subscribers_for(self, event_type: str) -> WeakSet[Callable[[Any], Awaitable]]: ...
    @overload
    def subscribers_for(self, event_type: _WildcardType) -> WeakSet[Callable[[str, Any], Awaitable]]: ...
    def event_names(self) -> set[str]: ...
    def has_subscribers(self, event_type: str|_WildcardType) -> bool: ...
    @staticmethod
    def is_valid_event_type(event_type: object) -> TypeGuard[str|_WildcardType]: ...
    @overload
    def is_subscribed(self, callback: Callable[[Any], Awaitable], event_type: str) -> bool: ...
    @overload
    def is_subscribed(self, callback: Callable[[str, Any], Awaitable], event_type: _WildcardType) -> bool: ...
    @overload
    def is_subscribed(self, callback: Callable[..., Awaitable]) -> bool: ...
    @overload
    def is_subscribed(self, callback: object, event_type: object) -> Literal[False]: ...
    @property
    def total_subscribers(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def wildcards(self) -> WeakSet[Callable[[str, Any], Awaitable]]: ...
    @property
    def wildcard_count(self) -> int: ...
    @property
    def active_tasks(self) -> int: ...
    @property
    def stream_queue(self) -> Queue[Any]: ...
    @stream_queue.setter
    def stream_queue(self, val: Queue[Any], /) -> None: ...
    @property
    def dummy_task(self) -> Task[None]: ...
    def is_auditing(self) -> bool: ...
    @property
    def auditing(self) -> bool: ...
    @auditing.setter
    def auditing(self, val: bool, /) -> None: ...
    def auditor(self, event: str, args: tuple[Any, ...], /) -> None: ...
    def start_audit(self) -> None: ...
    def stop_audit(self) -> None: ...
    def add_middleware(self, middleware: Callable[[str, Any], Any]) -> None: ...
    def remove_middleware(self, middleware: Callable[[str, Any], Any], *, result: Any=..., strict: bool=...) -> Any: ...
    def add_middleware_once(self, middleware: Callable[[str, Any], Any], until: Future[Any]) -> None: ...
    def audit_context(self) -> _GeneratorContextManager[None, None, None]: ...
    def tracking_context(self, stats_receiver: Future[Mapping[str, int]]|None=...) -> _GeneratorContextManager[None, None, None]: ...
    def start_tracking(self) -> None: ...
    @overload
    def stop_tracking(self, ret_stats: Literal[False]=...) -> None: ...
    @overload
    def stop_tracking(self, ret_stats: Literal[True]) -> defaultdict[str, int]: ...
    @overload
    async def subscribe[C: Callable[[Any], Awaitable]](self, callback: C, /, event_type: str) -> C: ...
    @overload
    async def subscribe[C: Callable[[str, Any], Awaitable]](self, callback: C, /, event_type: _WildcardType=...) -> C: ...
    @overload
    async def unsubscribe(self, callback: Callable[[Any], Awaitable], /, event_type: str) -> bool: ...
    @overload
    async def unsubscribe(self, callback: Callable[[str, Any], Awaitable], /, event_type: _WildcardType=...) -> bool: ...
    @overload
    def subscribe_to[C: Callable[[Any], Awaitable]](self, event_type: str) -> Callable[[C], C]: ...
    @overload
    def subscribe_to[C: Callable[[str, Any], Awaitable]](self, event_type: _WildcardType) -> Callable[[C], C]: ...
    async def publish(self, event_type: str, data: Any=..., *, wait: bool=..., safe: bool=..., timeout: float|None=..., chaperone: Callable[[ExceptionGroup|Exception]]|None=...) -> None: ...
    async def wait_for_event(self, event_type: str, *, timeout: bool|None=..., condition: Callable[[Any], Any]=...) -> Task[Any]: ...
    async def subscribe_until[T](self, fut: Future[T], callback: Callable[..., Awaitable], event_type: str|_WildcardType=..., till_permanent: float|None=...) -> Task[T]: ...
    async def feed_event(self, *d: Any, timeout: float|None=...) -> None: ...
    @overload
    def event_stream(self, event_type: str, *, timeout: float|None=..., item_timeout: float|None=..., bufsize: int=...) -> AsyncGenerator[Any, None]: ...
    @overload
    def event_stream(self, *, timeout: float|None=..., item_timeout: float|None=..., bufsize: int=...) -> AsyncGenerator[tuple[str, Any], None]: ...
    async def shutdown(self, immediate: bool=..., timeout: float|None=..., preserve_stats: bool=...) -> None: ...
    async def handle_exception(self, e: BaseException) -> None: ...
    @overload
    def clear(self, event_type: str) -> WeakSet[Callable[..., Awaitable]]|None: ...
    @overload
    def clear(self, event_type: _WildcardType) -> WeakSet[Callable[..., Awaitable]]|None: ...
    @overload
    def clear(self) -> None: ...
    def clear_all(self) -> None: ...
    def subscriber_count(self, event_type: str|_WildcardType) -> int: ...
    def clear_wildcards(self) -> WeakSet[Callable[..., Awaitable]]|None: ...
    def clear_stats(self) -> None: ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
class Rendezvous[T]:
    '''A rendezvous object, emulating Go's unbuffered channels. Usage:
    >>> rdv = Rendezvous()
    >>> await asyncio.gather(*map(rdv.put, range(5, 10)), rdv.exchange(10), *map(rdv.exchange, range(1, 5)), *(rdv.get() for _ in range(5)))
    [True, True, True, True, True, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    >>> task = rdv._loop.create_task(rdv.put(0))
    >>> await rdv.state_snapshot()
    StateSnapshot(num_getters=0, num_putters=1, num_ops=1, idle=False)
    >>> await rdv.get()
    0
    >>> await rdv.get('default')
    'default'
    >>> await task
    True
    >>> task = rdv._loop.create_task(rdv.get())
    >>> await rdv.reset()
    >>> task.cancelled()
    True'''
    def __init__(self, *, loop: AbstractEventLoop=..., lock: Lock=...): '''If loop is not passed, the running event loop is used. If there is no running event loop, one is created and set.'''
    async def raising_put(self, value: T, /, *, timeout: float) -> None:
        '''Put in a value to the rendezvous, blocking until it is gotten or timeout is reached, at which point TimeoutError is raised and the put cancelled.
        Also be prepared to intercept or reraise CancelledError resulting from reset.'''
    async def put(self, value: T, /, *, timeout: float|None=...) -> bool:
        '''Like raising_put, but returns a boolean representing if the put succeeded. The recommended interface.
        May still raise CancelledError when the Rendezvous is reset, which should be allowed to propagate.'''
    async def get(self, default: T|None=..., *, timeout: float|None=...) -> T:
        '''Get a value from the rendezvous, blocking until available unless default is passed and timeout is not, in which case the default is returned if a value is not immediately available.
        If default is not passed and the timeout is reached, the TimeoutError is propagated. In any case, the get is cancelled at timeout.'''
    async def cleanup(self) -> None: '''Clean up the internal getter and putter stacks.'''
    async def reset(self) -> None:
        '''Reset the Rendezvous. Call from a monitoring task when a deadlock appears to have occurred.
        This cancels all pending gets, puts and exchanges; their callers will see CancelledError.'''
    @type_check_only
    class StateSnapshot(tuple[int, int, int, bool]):
        '''Does not exist at runtime.'''
        @property
        def num_getters(self) -> int: ...
        @property
        def num_putters(self) -> int: ...
        @property
        def num_ops(self) -> int: ...
        @property
        def idle(self) -> bool: ...
        def __repr__(self) -> str: ...
    def __length_hint__(self) -> int: '''Approximate number of operations pending; for operator.length_hint.'''
    async def state_snapshot(self) -> StateSnapshot: '''Return a snapshot of the current state of the object at the earliest convenience.'''
    async def exchange(self, put_val: T, /, *, timeout: float|None=..., asap: bool=...) -> T:
        '''Put in a value to the rendezvous and get a different one back, not necessarily in that order.
        If asap is True, don't wait for the put to complete.'''
    async def _put_helper(self, value: T, /) -> Future[None]: '''Request a value be put into the rendezvous, returning an asyncio.Future. When cancelled, the put is cancelled as well. When done, the value has been handed off to a getter.'''
    async def _maintainer(self) -> NoReturn: '''Periodically clean up done getters and putters.'''