'''Contextual configuration system, inspired by the `decimal` module.'''
from ._internal.types import ValidExcType
from _collections_abc import Sequence
from types import TracebackType
from typing import Any, Final, NamedTuple, final, overload
__all__ = 'Context', 'all_contextual_consts', 'getcontext', 'localcontext', 'setcontext'
@final
class Context(NamedTuple):
    '''A `collections.namedtuple` storing configuration for various functions and patterns in this library, for immutability and performance; that is,
    not loading `dataclasses`, which loads `inspect` and triggers a cascade of imports.
    This class can technically be instantiated with positional arguments, but since the order of the fields are kept in alphabetical order of submodule
    and new fields may be added in the future, only keyword arguments should be used to avoid subtle bugs.
    For consistency, each field is named in all caps with words separated by underscores, and prefixed by the name of the utility it is used in, followed
    by a concise description of what it configures.
    Of course, this class is not related to instantiating a certain class, as in the `decimal` module, but rather a convenient way to store configuration
    for the various utilities and patterns this library bundles, especially to dynamically get default values in function signatures.
    The behaviour of this class as a tuple at runtime is an implementation detail.'''
    CIRCUIT_BREAKER_DEFAULT_RESET: float = ...
    CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS: int = ...
    CIRCUIT_BREAKER_DEFAULT_MAX_FAILS: int = ...
    DYNAMIC_BOUNDED_SEMAPHORE_DEFAULT_VALUE: int = ...
    DYNAMIC_THROTTLE_DEFAULT_MIN_RATE: float = ...
    DYNAMIC_THROTTLE_DEFAULT_MAX_RATE: float = ...
    DYNAMIC_THROTTLE_DEFAULT_WINDOW: int = ...
    DYNAMIC_THROTTLE_DEFAULT_UBOUND: float = ...
    DYNAMIC_THROTTLE_DEFAULT_LBOUND: float = ...
    DYNAMIC_THROTTLE_DEFAULT_UFACTOR: float = ...
    DYNAMIC_THROTTLE_DEFAULT_LFACTOR: float = ...
    DYNAMIC_THROTTLE_DEFAULT_JITTER: float = ...
    ITER_TO_AITER_DEFAULT_USE_EXISTING_EXECUTOR: bool = ...
    ITER_TO_AITER_DEFAULT_MAY_CREATE_EXECUTOR: bool = ...
    AITER_TO_ITER_DEFAULT_ALLOW_FUTURES: bool = ...
    TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS: float = ...
    LEAKY_BUCKET_DEFAULT_MIN_FACTOR: float = ...
    LEAKY_BUCKET_DEFAULT_MAX_FACTOR: float = ...
    LEAKY_BUCKET_DEFAULT_ACQUIRE_TOKENS: float = ...
    LEAKY_BUCKET_DEFAULT_WAIT_FOR_TOKENS_TOKENS: float = ...
    LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK: float = ...
    LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR: bool = ...
    LEAKY_BUCKET_ADJMAP: Sequence[tuple[float, tuple[float, float, float, float]]] = ...
    BACKGROUND_REFRESH_CACHE_DEFAULT_TTL: float = ...
    BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH: float = ...
    ASYNC_LRU_CACHE_DEFAULT_MAX_SIZE: int = ...
    OBSERVABLE_DEFAULT_NTIMES_N: int = ...
    EVENT_BUS_DEFAULT_MAX_CONCURRENT: int = ...
    EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE: int = ...
    EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT: float|None = ...
    EVENT_BUS_STREAM_DEFAULT_TIMEOUT: float|None = ...
    RENDEZVOUS_MAINTENANCE_INTERVAL: float = ...
    CONVERT_TO_CORO_ITER_DEFAULT_SKIP_INVALID: bool = ...
    EVENT_WITH_VALUE_DEFAULT_MAX_HIST: int = ...
    EVENT_WITH_VALUE_DEFAULT_RECENT: float = ...
    TIMER_DEFAULT_PRECISION: int = ...
    RETRY_DEFAULT_TRIES: int = ...
    RETRY_DEFAULT_DELAY: float = ...
    RETRY_DEFAULT_MAX_DELAY: float = ...
    RETRY_DEFAULT_BACKOFF: float = ...
    RETRY_DEFAULT_JITTER: float = ...
    BENCHMARK_DEFAULT_TIMES: int = ...
    BENCHMARK_DEFAULT_WARMUP: int = ...
    AUNZIP_DEFAULT_PUT_BATCH: int = ...
    AFRIEVALDS_DEFAULT_K: int = ...
    ADVANCED_RATE_LIMIT_DEFAULT_TOKENS: float = ...
    PRIORITY_SEMAPHORE_DEFAULT_VALUE: int = ...
    RWLOCK_DEFAULT_PREFER_WRITERS: bool = ...
    LOCKSMITH_DEFAULT_TIMEOUTS: tuple[float|None, float|None, float|None] = ...
    GATHER_WITH_LIMITED_CONCURRENCY_DEFAULT_MAX_CONCURRENT: int = ...
    LINE_PROTOCOL_DEFAULT_BUFFER_SIZE: int = ...
    SOCKET_TRANSPORT_LIMITS: tuple[int, int] = ...
    POOL_DEFAULT_WORKERS: int = ...
    ADVANCED_POOL_DEFAULT_MAX_WORKERS: int = ...
    ADVANCED_POOL_DEFAULT_MIN_WORKERS: int = ...
    ADVANCED_POOL_THRESHOLD_HI: float = ...
    ADVANCED_POOL_THRESHOLD_LO: float = ...
    ADVANCED_POOL_FACTOR: float = ...
    CONNECTION_POOL_DEFAULT_MAX_SIZE: int = ...
    CONNECTION_POOL_DEFAULT_MIN_SIZE: int = ...
    CONNECTION_POOL_DEFAULT_MAX_LIFE: float = ...
    CONNECTION_POOL_MAINTENANCE_INTERVAL: float = ...
    BOUNDED_BATCH_PROCESSOR_DEFAULT_BATCH_SIZE: int = ...
    BOUNDED_BATCH_PROCESSOR_DEFAULT_MAX_CONCURRENT: int = ...
    BATCH_PROCESSOR_DEFAULT_MAX_SIZE: int = ...
    BATCH_PROCESSOR_DEFAULT_MAX_TIME: float = ...
    BULKHEAD_DEFAULT_MAX_QUEUE: int = ...
    BULKHEAD_DEFAULT_MAX_REJ: int = ...
    WAIT_FOR_SIGNAL_DEFAULT_SIGNALS: Sequence[int] = ...
    SEMAPHORE_DEFAULT_VALUE: int = ...
class localcontext:
    '''Context manager for temporarily setting the context to a modified version of the provided context. Not reentrant.'''
    def __init__(self, ctx: Context=..., **k: Any): '''Note that the context of the current thread is to be set to `ctx`.'''
    @property
    def new_ctx(self) -> Context: '''The new context to be set on context manager entry.'''
    @property
    def saved_ctx(self) -> Context: '''The previous context to be restored on context manager exit.'''
    def __enter__(self) -> Context: '''Return the new context after setting it.'''
    @overload
    def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
def getcontext() -> Context: '''Return the current context for the active thread.'''
def setcontext(ctx: Context, /) -> None: '''Set the current context to for the active thread to `ctx`.'''
all_contextual_consts: frozenset[str]
'''A `frozenset` of all contextual constant names, for use in validating that only valid contextual constants are accessed or modified.
These names will not be listed in the `__dir__` function of this submodule, since there are so many of them (currently 60) and more may be added in the future.'''
CIRCUIT_BREAKER_DEFAULT_RESET: Final[float]
CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS: Final[int]
CIRCUIT_BREAKER_DEFAULT_MAX_FAILS: Final[int]
DYNAMIC_BOUNDED_SEMAPHORE_DEFAULT_VALUE: Final[int]
DYNAMIC_THROTTLE_DEFAULT_MIN_RATE: Final[float]
DYNAMIC_THROTTLE_DEFAULT_MAX_RATE: Final[float]
DYNAMIC_THROTTLE_DEFAULT_WINDOW: Final[int]
DYNAMIC_THROTTLE_DEFAULT_UBOUND: Final[float]
DYNAMIC_THROTTLE_DEFAULT_LBOUND: Final[float]
DYNAMIC_THROTTLE_DEFAULT_UFACTOR: Final[float]
DYNAMIC_THROTTLE_DEFAULT_LFACTOR: Final[float]
DYNAMIC_THROTTLE_DEFAULT_JITTER: Final[float]
ITER_TO_AITER_DEFAULT_USE_EXISTING_EXECUTOR: Final[bool]
ITER_TO_AITER_DEFAULT_MAY_CREATE_EXECUTOR: Final[bool]
AITER_TO_ITER_DEFAULT_ALLOW_FUTURES: Final[bool]
TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS: Final[float]
LEAKY_BUCKET_DEFAULT_MIN_FACTOR: Final[float]
LEAKY_BUCKET_DEFAULT_MAX_FACTOR: Final[float]
LEAKY_BUCKET_DEFAULT_ACQUIRE_TOKENS: Final[float]
LEAKY_BUCKET_DEFAULT_WAIT_FOR_TOKENS_TOKENS: Final[float]
LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK: Final[float]
LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR: Final[bool]
LEAKY_BUCKET_ADJMAP: Final[Sequence[tuple[float, tuple[float, float, float, float]]]]
BACKGROUND_REFRESH_CACHE_DEFAULT_TTL: Final[float]
BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH: Final[float]
ASYNC_LRU_CACHE_DEFAULT_MAX_SIZE: Final[int]
OBSERVABLE_DEFAULT_NTIMES_N: Final[int]
EVENT_BUS_DEFAULT_MAX_CONCURRENT: Final[int]
EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE: Final[int]
EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT: Final[float|None]
EVENT_BUS_STREAM_DEFAULT_TIMEOUT: Final[float|None]
RENDEZVOUS_MAINTENANCE_INTERVAL: Final[float]
CONVERT_TO_CORO_ITER_DEFAULT_SKIP_INVALID: Final[bool]
EVENT_WITH_VALUE_DEFAULT_MAX_HIST: Final[int]
EVENT_WITH_VALUE_DEFAULT_RECENT: Final[float]
TIMER_DEFAULT_PRECISION: Final[int]
RETRY_DEFAULT_TRIES: Final[int]
RETRY_DEFAULT_DELAY: Final[float]
RETRY_DEFAULT_MAX_DELAY: Final[float]
RETRY_DEFAULT_BACKOFF: Final[float]
RETRY_DEFAULT_JITTER: Final[float]
BENCHMARK_DEFAULT_TIMES: Final[int]
BENCHMARK_DEFAULT_WARMUP: Final[int]
AUNZIP_DEFAULT_PUT_BATCH: Final[int]
AFRIEVALDS_DEFAULT_K: Final[int]
ADVANCED_RATE_LIMIT_DEFAULT_TOKENS: Final[float]
PRIORITY_SEMAPHORE_DEFAULT_VALUE: Final[int]
RWLOCK_DEFAULT_PREFER_WRITERS: Final[bool]
LOCKSMITH_DEFAULT_TIMEOUTS: Final[tuple[float|None, float|None, float|None]]
GATHER_WITH_LIMITED_CONCURRENCY_DEFAULT_MAX_CONCURRENT: Final[int]
LINE_PROTOCOL_DEFAULT_BUFFER_SIZE: Final[int]
SOCKET_TRANSPORT_LIMITS: Final[tuple[int, int]]
POOL_DEFAULT_WORKERS: Final[int]
ADVANCED_POOL_DEFAULT_MAX_WORKERS: Final[int]
ADVANCED_POOL_DEFAULT_MIN_WORKERS: Final[int]
ADVANCED_POOL_THRESHOLD_HI: Final[float]
ADVANCED_POOL_THRESHOLD_LO: Final[float]
ADVANCED_POOL_FACTOR: Final[float]
CONNECTION_POOL_DEFAULT_MAX_SIZE: Final[int]
CONNECTION_POOL_DEFAULT_MIN_SIZE: Final[int]
CONNECTION_POOL_DEFAULT_MAX_LIFE: Final[float]
CONNECTION_POOL_MAINTENANCE_INTERVAL: Final[float]
BOUNDED_BATCH_PROCESSOR_DEFAULT_BATCH_SIZE: Final[int]
BOUNDED_BATCH_PROCESSOR_DEFAULT_MAX_CONCURRENT: Final[int]
BATCH_PROCESSOR_DEFAULT_MAX_SIZE: Final[int]
BATCH_PROCESSOR_DEFAULT_MAX_TIME: Final[float]
BULKHEAD_DEFAULT_MAX_QUEUE: Final[int]
BULKHEAD_DEFAULT_MAX_REJ: Final[int]
WAIT_FOR_SIGNAL_DEFAULT_SIGNALS: Final[Sequence[int]]
SEMAPHORE_DEFAULT_VALUE: Final[int]