'''Miscellaneous context and context system.'''
from ._internal.types import ValidExcType
from _collections_abc import Sequence
from dataclasses import dataclass
from types import TracebackType
from typing import Any, Final, Self, final, overload
__all__ = 'Context', 'getcontext', 'localcontext', 'setcontext'
@final
@dataclass(kw_only=True, match_args=False, slots=True)
class Context:
    CIRCUIT_BREAKER_DEFAULT_RESET: float = ...
    CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS: int = ...
    CIRCUIT_BREAKER_DEFAULT_MAX_FAILS: int = ...
    DYNAMIC_BOUNDED_SEMAPHORE_DEFAULT_VALUE: int = ...
    DYNAMIC_THROTTLE_DEFAULT_MIN_RATE: float = ...
    DYNAMIC_THROTTLE_DEFAULT_MAX_RATE: float = ...
    DYNAMIC_THROTTLE_DEFAULT_WINDOW: int = ...
    DYNAMIC_THROTTLE_DEFAULT_UBOUND: float = ...
    DYNAMIC_THROTTLE_DEFAULT_LBOUND: float = ...
    DYNAMIC_THROTTLE_DEFAULT_UFACTOR: float = ...
    DYNAMIC_THROTTLE_DEFAULT_LFACTOR: float = ...
    DYNAMIC_THROTTLE_DEFAULT_JITTER: float = ...
    ITER_TO_AITER_DEFAULT_USE_EXISTING_EXECUTOR: bool = ...
    ITER_TO_AITER_DEFAULT_MAY_CREATE_EXECUTOR: bool = ...
    TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS: float = ...
    LEAKY_BUCKET_DEFAULT_MINFACTOR: float = ...
    LEAKY_BUCKET_DEFAULT_MAXFACTOR: float = ...
    LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK: float = ...
    LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR: bool = ...
    LEAKY_BUCKET_ADJMAP: Sequence[tuple[float, tuple[float, float, float, float]]] = ...
    BACKGROUND_REFRESH_CACHE_DEFAULT_TTL: float = ...
    BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH: float = ...
    ASYNC_LRU_CACHE_DEFAULT_MAX_SIZE: int = ...
    EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE: int = ...
    EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT: float|None = ...
    EVENT_BUS_STREAM_DEFAULT_TIMEOUT: float|None = ...
    EVENT_WITH_VALUE_DEFAULT_MAX_HIST: int = ...
    EVENT_WITH_VALUE_DEFAULT_RECENT: float = ...
    RETRY_DEFAULT_TRIES: int = ...
    RETRY_DEFAULT_DELAY: float = ...
    RETRY_DEFAULT_MAX_DELAY: float = ...
    RETRY_DEFAULT_BACKOFF: float = ...
    RETRY_DEFAULT_JITTER: float = ...
    ADVANCED_RATE_LIMIT_DEFAULT_TOKENS: float = ...
    PRIORITY_SEMAPHORE_DEFAULT_VALUE: int = ...
    RWLOCK_DEFAULT_PREFER_WRITERS: bool = ...
    LOCKSMITH_DEFAULT_TIMEOUTS: tuple[float|None, float|None, float|None] = ...
    GATHER_WITH_LIMITED_CONCURRENCY_DEFAULT_MAX_CONCURRENT: int = ...
    LINE_PROTOCOL_DEFAULT_BUFFER_SIZE: int = ...
    SOCKET_TRANSPORT_LIMITS: tuple[int, int] = ...
    ADVANCED_POOL_THRESHOLD_HI: float = ...
    ADVANCED_POOL_THRESHOLD_LO: float = ...
    ADVANCED_POOL_FACTOR: float = ...
    CONNECTION_POOL_DEFAULT_MAX_SIZE: int = ...
    CONNECTION_POOL_DEFAULT_MIN_SIZE: int = ...
    CONNECTION_POOL_DEFAULT_MAX_LIFE: float = ...
    CONNECTION_POOL_MAINTENANCE_INTERVAL: float = ...
    BOUNDED_BATCH_PROCESSOR_DEFAULT_BATCH_SIZE: int = ...
    BOUNDED_BATCH_PROCESSOR_DEFAULT_MAX_CONCURRENT: int = ...
    BATCH_PROCESSOR_DEFAULT_MAX_SIZE: int = ...
    BATCH_PROCESSOR_DEFAULT_MAX_TIME: float = ...
    BULKHEAD_DEFAULT_MAX_QUEUE: int = ...
    BULKHEAD_DEFAULT_MAX_REJ: int = ...
    WAIT_FOR_SIGNAL_DEFAULT_SIGNALS: Sequence[int] = ...
    SEMAPHORE_DEFAULT_VALUE: int = ...
    def __post_init__(self) -> None: ...
    def copy(self, /, **changes: Any) -> Self: ...
class localcontext:
    def __init__(self, new_ctx: Context): '''Set the context to new_ctx upon entry of the context manager.'''
    @property
    def new_ctx(self) -> Context: ...
    @property
    def saved_ctx(self) -> Context: '''The previous context to be restored on exit.'''
    def __enter__(self) -> None: ...
    @overload
    def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
def getcontext() -> Context: '''Return the current context.'''
def setcontext(ctx: Context, /) -> None: '''Set the current context to ctx.'''
# The following are not included in __all__ and cannot be accessed by shortened name; more may be added in the future.
CIRCUIT_BREAKER_DEFAULT_RESET: Final[float]
CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS: Final[int]
CIRCUIT_BREAKER_DEFAULT_MAX_FAILS: Final[int]
DYNAMIC_BOUNDED_SEMAPHORE_DEFAULT_VALUE: Final[int]
DYNAMIC_THROTTLE_DEFAULT_MIN_RATE: Final[float]
DYNAMIC_THROTTLE_DEFAULT_MAX_RATE: Final[float]
DYNAMIC_THROTTLE_DEFAULT_WINDOW: Final[int]
DYNAMIC_THROTTLE_DEFAULT_UBOUND: Final[float]
DYNAMIC_THROTTLE_DEFAULT_LBOUND: Final[float]
DYNAMIC_THROTTLE_DEFAULT_UFACTOR: Final[float]
DYNAMIC_THROTTLE_DEFAULT_LFACTOR: Final[float]
DYNAMIC_THROTTLE_DEFAULT_JITTER: Final[float]
ITER_TO_AITER_DEFAULT_USE_EXISTING_EXECUTOR: Final[bool]
ITER_TO_AITER_DEFAULT_MAY_CREATE_EXECUTOR: Final[bool]
TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS: Final[float]
LEAKY_BUCKET_DEFAULT_MINFACTOR: Final[float]
LEAKY_BUCKET_DEFAULT_MAXFACTOR: Final[float]
LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK: Final[float]
LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR: Final[bool]
LEAKY_BUCKET_ADJMAP: Final[Sequence[tuple[float, tuple[float, float, float, float]]]]
BACKGROUND_REFRESH_CACHE_DEFAULT_TTL: Final[float]
BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH: Final[float]
ASYNC_LRU_CACHE_DEFAULT_MAX_SIZE: Final[int]
EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE: Final[int]
EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT: Final[float|None]
EVENT_BUS_STREAM_DEFAULT_TIMEOUT: Final[float|None]
EVENT_WITH_VALUE_DEFAULT_MAX_HIST: Final[int]
EVENT_WITH_VALUE_DEFAULT_RECENT: Final[float]
RETRY_DEFAULT_TRIES: Final[int]
RETRY_DEFAULT_DELAY: Final[float]
RETRY_DEFAULT_MAX_DELAY: Final[float]
RETRY_DEFAULT_BACKOFF: Final[float]
RETRY_DEFAULT_JITTER: Final[float]
ADVANCED_RATE_LIMIT_DEFAULT_TOKENS: Final[float]
PRIORITY_SEMAPHORE_DEFAULT_VALUE: Final[int]
RWLOCK_DEFAULT_PREFER_WRITERS: Final[bool]
LOCKSMITH_DEFAULT_TIMEOUTS: Final[tuple[float|None, float|None, float|None]]
GATHER_WITH_LIMITED_CONCURRENCY_DEFAULT_MAX_CONCURRENT: Final[int]
LINE_PROTOCOL_DEFAULT_BUFFER_SIZE: Final[int]
SOCKET_TRANSPORT_LIMITS: Final[tuple[int, int]]
ADVANCED_POOL_THRESHOLD_HI: Final[float]
ADVANCED_POOL_THRESHOLD_LO: Final[float]
ADVANCED_POOL_FACTOR: Final[float]
CONNECTION_POOL_DEFAULT_MAX_SIZE: Final[int]
CONNECTION_POOL_DEFAULT_MIN_SIZE: Final[int]
CONNECTION_POOL_DEFAULT_MAX_LIFE: Final[float]
CONNECTION_POOL_MAINTENANCE_INTERVAL: Final[float]
BOUNDED_BATCH_PROCESSOR_DEFAULT_BATCH_SIZE: Final[int]
BOUNDED_BATCH_PROCESSOR_DEFAULT_MAX_CONCURRENT: Final[int]
BATCH_PROCESSOR_DEFAULT_MAX_SIZE: Final[int]
BATCH_PROCESSOR_DEFAULT_MAX_TIME: Final[float]
BULKHEAD_DEFAULT_MAX_QUEUE: Final[int]
BULKHEAD_DEFAULT_MAX_REJ: Final[int]
WAIT_FOR_SIGNAL_DEFAULT_SIGNALS: Final[Sequence[int]]
SEMAPHORE_DEFAULT_VALUE: Final[int]