from ._internal.patch import patch_function_signatures as f
from ._internal.submodules import context_all as __all__
Context = __import__('collections').namedtuple('Context', 'CIRCUIT_BREAKER_DEFAULT_RESET CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS CIRCUIT_BREAKER_DEFAULT_MAX_FAILS DYNAMIC_BOUNDED_SEMAPHORE_DEFAULT_VALUE DYNAMIC_THROTTLE_DEFAULT_MIN_RATE DYNAMIC_THROTTLE_DEFAULT_MAX_RATE DYNAMIC_THROTTLE_DEFAULT_WINDOW DYNAMIC_THROTTLE_DEFAULT_UBOUND DYNAMIC_THROTTLE_DEFAULT_LBOUND DYNAMIC_THROTTLE_DEFAULT_UFACTOR DYNAMIC_THROTTLE_DEFAULT_LFACTOR DYNAMIC_THROTTLE_DEFAULT_JITTER ITER_TO_AITER_DEFAULT_USE_EXISTING_EXECUTOR ITER_TO_AITER_DEFAULT_MAY_CREATE_EXECUTOR AITER_TO_ITER_DEFAULT_ALLOW_FUTURES TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS LEAKY_BUCKET_DEFAULT_MIN_FACTOR LEAKY_BUCKET_DEFAULT_MAX_FACTOR LEAKY_BUCKET_DEFAULT_ACQUIRE_TOKENS LEAKY_BUCKET_DEFAULT_WAIT_FOR_TOKENS_TOKENS LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR LEAKY_BUCKET_ADJMAP BACKGROUND_REFRESH_CACHE_DEFAULT_TTL BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH ASYNC_LRU_CACHE_DEFAULT_MAX_SIZE OBSERVABLE_DEFAULT_NTIMES_N EVENT_BUS_DEFAULT_MAX_CONCURRENT EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT EVENT_BUS_STREAM_DEFAULT_TIMEOUT RENDEZVOUS_MAINTENANCE_INTERVAL CONVERT_TO_CORO_ITER_DEFAULT_SKIP_INVALID EVENT_WITH_VALUE_DEFAULT_MAX_HIST EVENT_WITH_VALUE_DEFAULT_RECENT TIMER_DEFAULT_PRECISION RETRY_DEFAULT_TRIES RETRY_DEFAULT_DELAY RETRY_DEFAULT_MAX_DELAY RETRY_DEFAULT_BACKOFF RETRY_DEFAULT_JITTER BENCHMARK_DEFAULT_TIMES BENCHMARK_DEFAULT_WARMUP AUNZIP_DEFAULT_PUT_BATCH AFRIEVALDS_DEFAULT_K ADVANCED_RATE_LIMIT_DEFAULT_TOKENS PRIORITY_SEMAPHORE_DEFAULT_VALUE RWLOCK_DEFAULT_PREFER_WRITERS LOCKSMITH_DEFAULT_TIMEOUTS GATHER_WITH_LIMITED_CONCURRENCY_DEFAULT_MAX_CONCURRENT LINE_PROTOCOL_DEFAULT_BUFFER_SIZE SOCKET_TRANSPORT_LIMITS POOL_DEFAULT_WORKERS ADVANCED_POOL_DEFAULT_MAX_WORKERS ADVANCED_POOL_DEFAULT_MIN_WORKERS ADVANCED_POOL_THRESHOLD_HI ADVANCED_POOL_THRESHOLD_LO ADVANCED_POOL_FACTOR CONNECTION_POOL_DEFAULT_MAX_SIZE CONNECTION_POOL_DEFAULT_MIN_SIZE CONNECTION_POOL_DEFAULT_MAX_LIFE CONNECTION_POOL_MAINTENANCE_INTERVAL BOUNDED_BATCH_PROCESSOR_DEFAULT_BATCH_SIZE BOUNDED_BATCH_PROCESSOR_DEFAULT_MAX_CONCURRENT BATCH_PROCESSOR_DEFAULT_MAX_SIZE BATCH_PROCESSOR_DEFAULT_MAX_TIME BULKHEAD_DEFAULT_MAX_QUEUE BULKHEAD_DEFAULT_MAX_REJ WAIT_FOR_SIGNAL_DEFAULT_SIGNALS SEMAPHORE_DEFAULT_VALUE', defaults=(30.0, 5, 3, 1, 1e2, 100.0, 100, 0.75, 0.25, 1.25, 0.75, 0.2, False, False, True, 1.0, 0.1, 10.0, 1.0, 1.0, 0.1, True, ((0x100, (0.15, 1.1, 0.85, 0.9)), (0x80, (0.23, 1.2, 0.77, 0.81)), (0, (0.3, 1.4, 0.7, 0.73))), 60.0, 15.0, 128, 1, 64, 100, 3.0, 5.0, 30.0, True, 128, 5.0, 7, 3, 0.5, 30.0, 2.0, 0.2, 3, 0, 16, 2, 1.0, 1, True, (1.0, 0.1, None), 8, 0x1000, (0x800, 0x2000), 4, 5, 1, 1.5, 0.5, 0.3, 10, 1, 3600.0, 30.0, 10, 5, 128, 1.0, 0, -1, (2, 15), 8))
_ = __import__('_contextvars').ContextVar('asyncutils_contextvar')
def getcontext(_=_, d=Context()): # noqa: B008
    try: return _.get()
    except LookupError: _.set(d); return d
def setcontext(c, /, _=_):
    if not isinstance(c, Context): raise TypeError('setcontext: ctx must be an instance of asyncutils.context.Context')
    _.set(c)
f((getcontext, ''), (setcontext, 'ctx, /'))
class localcontext:
    __slots__ = 'new_ctx', 'saved_ctx'
    def __init__(self, ctx=None, **k):
        if ctx is None: ctx = getcontext()
        if type(ctx) is not Context: raise TypeError('localcontext: ctx must be an instance of asyncutils.context.Context')
        self.new_ctx = ctx._replace(**k)
    def __enter__(self): self.saved_ctx = getcontext(); setcontext(c := self.new_ctx); return c
    def __exit__(self, /, *_): setcontext(self.saved_ctx); del self.new_ctx, self.saved_ctx
all_contextual_consts = frozenset(Context._fields)
def __getattr__(name, /):
    if name in all_contextual_consts: return getattr(getcontext(), name)
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
del _, f