'''Miscellaneous context and context system.'''
from ._internal.protocols import ValidExcType
from dataclasses import dataclass
from types import TracebackType
from typing import Final, Self, Any, final, overload
__all__ = 'Context', 'getcontext', 'localcontext', 'setcontext'
@final
@dataclass(kw_only=True, match_args=False, slots=True)
class Context:
    CIRCUIT_BREAKER_DEFAULT_RESET: float = ...
    CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS: int = ...
    DYNAMIC_THROTTLE_DEFAULT_WINDOW: int = ...
    DYNAMIC_THROTTLE_DEFAULT_UBOUND: float = ...
    DYNAMIC_THROTTLE_DEFAULT_LBOUND: float = ...
    DYNAMIC_THROTTLE_DEFAULT_UFACTOR: float = ...
    DYNAMIC_THROTTLE_DEFAULT_LFACTOR: float = ...
    DYNAMIC_THROTTLE_DEFAULT_JITTER: float = ...
    TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS: float = ...
    LEAKY_BUCKET_DEFAULT_MINFACTOR: float = ...
    LEAKY_BUCKET_DEFAULT_MAXFACTOR: float = ...
    LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK: float = ...
    LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR: bool = ...
    BACKGROUND_REFRESH_CACHE_DEFAULT_TTL: float = ...
    BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH: float = ...
    ASYNC_LRU_CACHE_DEFAULT_MAXSIZE: int = ...
    EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE: int = ...
    EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT: float|None = ...
    EVENT_BUS_STREAM_DEFAULT_TIMEOUT: float|None = ...
    EVENT_WITH_VALUE_DEFAULT_MAXHIST: int = ...
    EVENT_WITH_VALUE_DEFAULT_RECENT: float = ...
    RETRY_DEFAULT_TRIES: int = ...
    RETRY_DEFAULT_DELAY: float = ...
    RETRY_DEFAULT_MAX_DELAY: float = ...
    RETRY_DEFAULT_BACKOFF: float = ...
    RETRY_DEFAULT_JITTER: float = ...
    def __post_init__(self) -> None: ...
    def copy(self, /, **changes: Any) -> Self: ...
class localcontext:
    def __init__(self, new_ctx: Context): '''Set the context to new_ctx upon entry of the context manager.'''
    @property
    def new_ctx(self) -> Context: ...
    @property
    def saved_ctx(self) -> Context: '''The previous context to be restored on exit.'''
    def __enter__(self) -> None: ...
    @overload
    def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
def getcontext() -> Context: '''Return the current context.'''
def setcontext(ctx: Context, /) -> None: '''Set the current context to ctx.'''
# The following are not included in __all__ and cannot be accessed by shortened name; more may be added in the future.
CIRCUIT_BREAKER_DEFAULT_RESET: Final[float]
CIRCUIT_BREAKER_DEFAULT_MAX_HALF_OPEN_CALLS: Final[int]
DYNAMIC_THROTTLE_DEFAULT_WINDOW: Final[int]
DYNAMIC_THROTTLE_DEFAULT_UBOUND: Final[float]
DYNAMIC_THROTTLE_DEFAULT_LBOUND: Final[float]
DYNAMIC_THROTTLE_DEFAULT_UFACTOR: Final[float]
DYNAMIC_THROTTLE_DEFAULT_LFACTOR: Final[float]
DYNAMIC_THROTTLE_DEFAULT_JITTER: Final[float]
TOKEN_BUCKET_DEFAULT_CONSUME_TOKENS: Final[float]
LEAKY_BUCKET_DEFAULT_MINFACTOR: Final[float]
LEAKY_BUCKET_DEFAULT_MAXFACTOR: Final[float]
LEAKY_BUCKET_WAIT_FOR_TOKENS_TICK: Final[float]
LEAKY_BUCKET_DEFAULT_EXT_CAN_SET_FACTOR: Final[bool]
BACKGROUND_REFRESH_CACHE_DEFAULT_TTL: Final[float]
BACKGROUND_REFRESH_CACHE_DEFAULT_REFRESH: Final[float]
ASYNC_LRU_CACHE_DEFAULT_MAXSIZE: Final[int]
EVENT_BUS_STREAM_DEFAULT_BUFFER_SIZE: Final[int]
EVENT_BUS_STREAM_DEFAULT_ITEM_TIMEOUT: Final[float|None]
EVENT_BUS_STREAM_DEFAULT_TIMEOUT: Final[float|None]
EVENT_WITH_VALUE_DEFAULT_MAXHIST: Final[int]
EVENT_WITH_VALUE_DEFAULT_RECENT: Final[float]
RETRY_DEFAULT_TRIES: Final[int]
RETRY_DEFAULT_DELAY: Final[float]
RETRY_DEFAULT_MAX_DELAY: Final[float]
RETRY_DEFAULT_BACKOFF: Final[float]
RETRY_DEFAULT_JITTER: Final[float]