from .mixins import EventMixin
from _collections_abc import Generator
from typing import Literal, overload
from asyncio.events import AbstractEventLoop
__all__ = 'SingleWaiterEventWithValue', 'EventWithValue'
class SingleWaiterEventWithValue[T](EventMixin):
    def __init__(self): ...
    def set(self, value: T) -> None: '''Set the result of the event, awakening the waiters.'''
    def clear(self) -> None: '''Unset the result of the event.'''
    def is_set(self) -> bool: '''Whether the result has been set.'''
    async def wait_for_next(self, timeout: float|None=..., *, strict: bool=...) -> T: '''Wait for the next value of the event to be set.'''
    def get(self) -> T: '''Get the value of the event immediately.'''
class EventWithValue[T](EventMixin):
    def __init__(self, *, maxhist: int|None=...): ...
    @overload
    def set(self, value: None, strict: Literal[False]=...) -> None: ...
    @overload
    def set(self, value: T, strict: bool=...) -> None: ...
    def remove_done_waiters(self) -> None: ...
    def set_once(self, value: T) -> None: ...
    def clear(self) -> None: ...
    @overload
    def get(self, strict: Literal[False]) -> T|None: ...
    @overload
    def get(self, strict: Literal[True]=...) -> T: ...
    async def wait_for_next(self, timeout: float|None=...) -> T: ...
    def is_set(self) -> bool: ...
    @property
    def history(self) -> list[tuple[float, T]]: ...
    @property
    def history_asdict(self) -> dict[float, T]: ...
    def recent_history(self, duration: float|None=...) -> Generator[tuple[float, T], None, None]: ...
    async def wait_for_transition(self, old: T, new: T, timeout: float|None=..., *, force_transition: bool=...) -> bool: ...
    async def wait_for_transition_unordered(self, a: T, b: T, timeout: float|None=..., *, force_transition: bool=..., loop: AbstractEventLoop|None=...) -> bool: ...