from asyncio.futures import Future
from asyncio.tasks import Task
from asyncio.events import AbstractEventLoop
from _collections_abc import Callable, Coroutine
from contextvars import Context
from typing import Self, Any
__all__ = 'AsyncCallbacksFuture', 'AsyncCallbacksTask'
class AsyncCallbacksFuture(Future):
    '''A subclass of asyncio.Future that supports calling asynchronous callbacks and callbacks with no arguments on completion.
    To hook into the callbacks mechanism, subclassing _asyncio.Future is infeasible; i.e., this future is noticeably slower than the C-accelerated version.'''
    def __init__(self, *, loop: AbstractEventLoop|None=...): ...
    def add_async_callback(self, fn: Callable[[Self], Coroutine], *, context: Context|None=...) -> None: ...
    def add_noargs_callback(self, fn: Callable[[], Any], *, context: Context|None=...) -> None: ...
    def add_noargs_async_callback(self, fn: Callable[[], Coroutine], *, context: Context|None=...) -> None: ...
    def remove_async_callback(self, fn: Callable[[Self], Coroutine], /) -> int: ...
    def smart_add_callback(self, fn: Callable[[Self], Any], *, context: Context|None=...) -> None: ...
    def smart_remove_callback(self, fn: Callable[[Self], Any]) -> int: ...
class AsyncCallbacksTask(Task, AsyncCallbacksFuture): '''The above, but a task.'''