from asyncio.futures import Future
from asyncio.tasks import Task
from asyncio.events import AbstractEventLoop
from typing import Self, Any
from contextvars import Context
from _collections_abc import Callable, Coroutine
__all__ = 'AsyncCallbacksFuture', 'AsyncCallbacksTask'
class AsyncCallbacksFuture(Future):
    def __init__(self, *, loop: AbstractEventLoop|None=...): ...
    def add_async_callback(self, fn: Callable[[Self], Coroutine], *, context: Context|None=...) -> None: ...
    def add_noargs_callback(self, fn: Callable[[]], *, context: Context|None=None) -> None: ...
    def add_noargs_async_callback(self, fn: Callable[[], Coroutine], *, context: Context|None=None) -> None: ...
    def remove_async_callback(self, fn: Callable[[Self], Coroutine], /) -> int: ...
    def smart_add_callback(self, fn: Callable[[Self], Any], *, context: Context|None=None) -> None: ...
    def smart_remove_callback(self, fn: Callable[[Self], Any]) -> int: ...
class AsyncCallbacksTask(Task, AsyncCallbacksFuture): ...