import sys
from .config import Executor
from ._internal.protocols import Openable
from .mixins import LoopContextMixin
from _collections_abc import Iterable, Iterator, AsyncGenerator, Mapping
from contextlib import _AsyncGeneratorContextManager
from io import TextIOWrapper, _WrappedBuffer
from mmap import mmap
from typing import IO, Literal, Any, Self, Protocol, type_check_only
from weakref import WeakSet
__all__ = 'double_ended_text_pipe', 'double_ended_binary_pipe', 'AsyncReadWriteCouple', 'MemoryMappedIOManager'
def double_ended_text_pipe(pipe_impl: _PipeFactory=...) -> tuple[AsyncReadWriteCouple[str, str], AsyncReadWriteCouple[str, str]]:
    '''Return a tuple of two `AsyncReadWriteCouple`s, such that each can read what the other writes. Two os-level pipes must be created.
    Pass a function that returns a tuple of two integer file descriptors for `pipe_impl` (default os.pipe) to customize this behaviour.'''
def double_ended_binary_pipe(pipe_impl: _PipeFactory=...) -> tuple[AsyncReadWriteCouple[bytes, bytes], AsyncReadWriteCouple[bytes, bytes]]: ...
class AsyncReadWriteCouple[T: (str, bytes), R: (str, bytes)](LoopContextMixin):
    '''An asynchronous file-like interface to a readable and writable object, which really just delegates its methods to the underlying reader and writer.
    The methods are made truly async using an executor and event loop, the type of which is determined from the module configuration.'''
    @property
    def reader(self) -> IO[T]: '''The underlying reader.'''
    @property
    def writer(self) -> IO[R]: '''The underlying writer.'''
    def __init__(self, reader: IO[T], writer: IO[R], /): ...
    def __getattr__(self, name: str, /) -> Any: ...
    async def __cleanup__(self) -> None: ...
    async def aclose(self) -> None: '''Close the reader and writer asynchronously and shut down the underlying executor. It is safe to close a file multiple times, but no other methods should be called after closing.'''
    async def flush(self) -> None: '''Asynchronously flush the writer.'''
    async def read(self, n: int=..., /) -> T: '''Read `n` characters from the reader.'''
    async def readline(self, limit: int=..., /) -> T: '''Read a line, of length at most `limit`, from the reader.'''
    async def readlines(self, hint: int=..., /) -> list[T]: '''Collect lines of the file into a list until `hint` characters are read.'''
    async def truncate(self, size: int|None=..., /) -> int: '''Truncate the file at `size` or the current position if not passed, and return the new file size.'''
    async def write(self, s: R, /) -> int: '''Write `s` into the writer, returning the number of characters written.'''
    async def writelines(self, lines: Iterable[R], /) -> None: '''Write the lines from the iterable into the writer without adding newline as separators.'''
    def fileno(self) -> int: '''Raise OSError.'''
    def isatty(self) -> bool: '''Whether at least one of the reader or the writer is connected to a terminal.'''
    def readable(self) -> bool: '''Whether the reader can be read from.'''
    def seek(self, offset: int, whence: int=..., /) -> int: '''Raise OSError.'''
    def seekable(self) -> bool: '''Whether both streams support random access.'''
    def tell(self) -> int: '''Raise OSError.'''
    def writable(self) -> bool: '''Whether the writer can be written into.'''
    @property
    def closed(self) -> bool: '''Whether the file has been closed.'''
class MemoryMappedIOManager(LoopContextMixin):
    '''An asynchronous object-oriented manager interface to memory-mapped I/O, that optimizes batch operations using an event loop.
    You probably only need one instance of this.
    In the docstrings below, `mgr` will be an instance of this class.'''
    def __init__(self, executor: Executor|None=...): ...
    @property
    def open_mmaps(self) -> WeakSet[mmap]: '''Instance of `weakref.WeakSet` containing the maps managed by this manager.'''
    @property
    def currently_open(self) -> int: ...
    @property
    def open_paths(self) -> dict[Openable, Literal['r+b', 'w+b']]: '''Dictionary mapping file paths as passed to `mgr.open` or `mgr.create` to the mode the file was opened with.'''
    @property
    def open_files(self) -> _OpenFiles: '''Dictionary'''
    @open_files.deleter
    def open_files(self) -> None: ...
    def open(self, path: Openable, init_size: int=...) -> _OpenRV: ...
    def create(self, path: Openable, init_size: int=...) -> _OpenRV: ...
    def create_sparsef(self, path: Openable, total_size: int, chunks: Mapping[int, bytes|str]) -> _OpenRV: ...
    def prefetch_files(self, *paths: Openable, init_size: int=...) -> _AsyncGeneratorContextManager[list[_file], None]: ...
    async def __cleanup__(self) -> None: ...
    def __del__(self) -> None: ...
    async def copy_file(self, srcp: Openable, destp: Openable) -> None: ...
    async def checksum(self, path: Openable, alg: _Algorithm=...) -> str: ...
    async def approx_memory_usage(self) -> int: ...
    async def bulk_read(self, file_offsets: Mapping[Openable, list[tuple[int, int]]]) -> dict[Openable, list[bytes]]: ...
    async def bulk_write(self, file_data: Mapping[Openable, list[tuple[bytes, int]]]) -> None: ...
    async def bulk_checksum(self, paths: Iterable[Openable], alg: _Algorithm=...) -> dict[Openable, str]: ...
    async def bulk_copy(self, pairs: Iterable[tuple[Openable, Openable]]) -> None: ...
    async def bulk_resize(self, sizes: Mapping[Openable, int]) -> None: ...
    async def compact_files(self, paths: Iterable[Openable]) -> None: ...
    async def find_in_files(self, pattern: bytes, paths: Mapping[Openable, int], max_per_file: int=..., *, allow_overlapping: bool=...) -> dict[Openable, list[int]]: ...
'''Below are for type checking only.'''
type _Algorithm = Literal['md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512', 'blake2b', 'blake2s', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'shake_128', 'shake_256']
'''Hardcoded values for algorithms used for calculating checksums.'''
type _OpenRV = _AsyncGeneratorContextManager[_file, None]
'''The type of the return values of open, create and create_sparsef.'''
type _OpenFiles = dict[tuple[TextIOWrapper[_WrappedBuffer], Literal['r+b', 'w+b']], _file]
'''The type of the property open_files.'''
if sys.platform == 'win32': type _Seek = Literal[0, 1, 2]
else: type _Seek = Literal[0, 1, 2, 3, 4]
@type_check_only
class _PipeFactory(Protocol):
    '''Not exported.'''
    def __call__(self) -> tuple[int, int]: ...
@type_check_only
class _file(LoopContextMixin):
    '''Not exposed. Calls itself asyncutils.io.file.'''
    if sys.platform != 'win32':
        def madvise(self, option: int, start: int=..., length: int|None=...) -> None: ...
    async def reg(self, m: mmap, /) -> None: ...
    async def unreg(self, m: mmap, /) -> None: ...
    async def read(self, offset: int=..., size: int=...) -> bytes: ...
    async def write(self, data: bytes, offset: int=...) -> None: ...
    async def readline(self, offset: int=..., size: int|None=..., incl_newline: bool=...) -> bytes: ...
    async def readlines(self, hint: int=...) -> list[bytes]: ...
    async def flush(self, offset: int=..., size: int|None=..., /) -> None: ...
    async def move(self, dest: int, src: int, count: int) -> None: ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
    async def seek(self, pos: int, whence: _Seek=...) -> None: ...
    def __new__(cls, file: IO[bytes], /) -> Self: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __del__(self) -> None: ...
    @property
    def mmap(self) -> mmap: ...
    @property
    def closed(self) -> bool: ...
    @property
    def open_files(self) -> _OpenFiles: ...
    def fileno(self) -> int: ...
    def sync(self) -> None: ...
    async def close(self) -> None: ...
    def read_byte(self) -> int: ...
    def write_byte(self, b: int, /) -> None: ...
    def resize(self, newsize: int) -> None: ...
    def find(self, sub: bytes, start: int|None=..., end: int|None=...) -> int: ...
    def rfind(self, sub: bytes, start: int|None=..., end: int|None=...) -> int: ...
    def tell(self) -> int: ...
    def size(self) -> int: ...
    def isatty(self) -> bool: ...
    def readable(self) -> Literal[True]: ...
    def writable(self) -> Literal[True]: ...
    def seekable(self) -> Literal[True]: ...
    async def writelines(self, lines: Iterable[bytes], /, *, sep: bytes=...) -> None: ...
    async def read_str(self, offset: int=..., size: int=..., encoding: str=..., errors: str=...) -> str: ...
    async def write_str(self, text: str, offset: int=..., encoding: str=..., errors: str=...) -> None: ...
    async def smart_write(self, data: str|bytes, offset: int=...) -> None: ...
    async def copy_range(self, src_offset: int, dest_offset: int, size: int) -> bool: ...
    async def fill(self, pattern: bytes, offset: int=..., count: int=...) -> None: ...
    async def compare(self, other: Self, /, size: int=..., offset_self: int=..., offset_other: int=...) -> bool: ...
    async def hamming_dist(self, other: Self, /, size: int=..., offset_self: int=..., offset_other: int=...) -> int: ...
    async def read_until(self, delim: bytes, offset: int=..., maxsize: int=...) -> tuple[bytes, int]: ...
    async def insert(self, data: bytes, offset: int) -> None: ...
    async def delete(self, offset: int, size: int) -> None: ...
    async def replace(self, old: bytes, new: bytes, offset: int=..., count: int=...) -> int: ...
    def search_lazy(self, pattern: bytes, offset: int=..., max_results: int=...) -> AsyncGenerator[int, None]: ...
    def search_lazy_nonoverlapping(self, pattern: bytes, offset: int=..., max_results: int=...) -> AsyncGenerator[int, None]: ...
    async def search(self, pattern: bytes, offset: int=..., max_results: int=...) -> list[int]: ...
    async def search_nonoverlapping(self, pattern: bytes, offset: int=..., max_result: int=...) -> list[int]: ...
    async def compact(self) -> None: ...