'''Functional and chainable interface to get async generators from (async) iterables.'''
from ._internal.types import AsyncContextManager, Exceptable, SupportsIteration, SupportsMatMul, SupportsRichComparison, SupportsSlicing, AUnzipConsumer
from _collections_abc import AsyncGenerator, AsyncIterable, Awaitable, Callable, Hashable, Iterable, Reversible
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from asyncio.locks import Event
from collections import deque
from typing import Any, Literal, SupportsIndex, overload
__all__ = 'aaccumulate', 'aall', 'aallequal', 'aany', 'aargmax', 'aargmin', 'abeforeandafter', 'acanonical', 'acat', 'achunked', 'acollapse', 'acombinations', 'acombinations_with_replacement', 'acompress', 'aconsume', 'aconvolve', 'acount', 'acycle', 'aderangements', 'adft', 'adistinctpermutations', 'adropwhile', 'afactor', 'afilter', 'afilterfalse', 'afirst', 'afirsttrue', 'aflatten', 'aforever', 'afrievalds', 'agetitems_from_indices', 'agroupby', 'agrouper', 'aguessmax', 'aguessmin', 'aidft', 'ailen', 'ainterleave', 'ainterleave_stopearly', 'ainterleaveevenly', 'ainterleaverandomly', 'aintersend', 'aintersperse', 'aislice', 'aisprime', 'aiterate', 'aiterexcept', 'aiterindex', 'alast', 'amap', 'amapif', 'amatmul', 'amatprod', 'amax', 'amin', 'amultimapif', 'amultinomial', 'ancycles', 'anth', 'anthcombination', 'anthorlast', 'apadnone', 'apairwise', 'apartition', 'apermutations', 'apolynomialderivative', 'apolynomialeval', 'apolynomialfromroots', 'apowers', 'apowerset', 'apowersetofsets', 'apowersoftwo', 'aprepend', 'aprod', 'aproduct', 'aquantify', 'arandom_combination_with_replacement', 'arandomcombination', 'arandomderangement', 'arandompermutation', 'arandomproduct', 'arange', 'arepeat', 'arepeatfunc', 'areshape', 'areversed', 'aroundrobin', 'aroundrobin2', 'arunlengthdecode', 'arunlengthencode', 'arunningmean', 'arunningmedian', 'asendstream', 'aserialize', 'asideeffect', 'asieve', 'asliced', 'asorted', 'asplitat', 'aspy', 'asquaresum', 'astarmap', 'asubslices', 'asubstrindices', 'asubstrings', 'asum', 'asumprod', 'atabulate', 'atail', 'atakewhile', 'atotient', 'atranspose', 'atriplewise', 'aunique', 'aunique_everseen', 'aunique_justseen', 'auniquetoeach', 'aunzip', 'azip', 'aziplongest', 'basic_collect', 'batch', 'batch_buffer', 'batch_process', 'buffer', 'fmap', 'fmap_parallel', 'fmap_sequential', 'iter_future', 'map_on_map', 'mat_vec_mul', 'merge', 'tee', 'to_list', 'to_tuple', 'vecs_eq', 'window', 'with_aiter'
async def fmap[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs) -> list[T]: '''Return a list of the results of calling each async function in the first argument (an (async) iterable of functions), with the provided arguments.'''
def fmap_sequential[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs) -> AsyncGenerator[T]: '''Like `fmap`, but only call a function after the last completes and the result is gotten.'''
def fmap_parallel[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs) -> AsyncGenerator[T]: '''Like `fmap_sequential`, but starts background tasks for each call.'''
@overload
def map_on_map[T, R, V](outer: Callable[[R], V], inner: Callable[[T], SupportsIteration[R]], it: SupportsIteration[T], *, inner_await: Literal[False]=..., outer_await: Literal[False]=...) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], Awaitable[V]], inner: Callable[[T], SupportsIteration[R]], it: SupportsIteration[T], *, inner_await: Literal[False]=..., outer_await: Literal[True]) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], V], inner: Callable[[T], Awaitable[SupportsIteration[R]]], it: SupportsIteration[T], *, inner_await: Literal[True], outer_await: Literal[False]=...) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], Awaitable[V]], inner: Callable[[T], Awaitable[SupportsIteration[R]]], it: SupportsIteration[T], *, inner_await: Literal[True], outer_await: Literal[True]) -> AsyncGenerator[tuple[V, ...], None]: '''Apply a transformation on an (async) iterable on top of another.'''
def tee[T](it: SupportsIteration[T], n: int=..., *, maxqsize: int=..., put_exc: bool=..., loop: AbstractEventLoop|None=...) -> tuple[AsyncGenerator[T], ...]: '''Create concurrent iterators over a single (async) iterable. Generally, if one iterator is expected to complete much sooner than others, it is not advisable to use this function, which uses more space in that case.'''
@overload
async def aunzip[T](ait: SupportsIteration[tuple[T]], put_batch: int=...) -> tuple[AUnzipConsumer[T]]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T]]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T]]: ...
@overload
async def aunzip[T, S](ait: SupportsIteration[tuple[T, S]], put_batch: int=...) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S]]: ...
@overload
async def aunzip[T, S, R](ait: SupportsIteration[tuple[T|R, S|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S]]: ...
@overload
async def aunzip[T, S, R](ait: SupportsIteration[tuple[T|R, S|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S]]: ...
@overload
async def aunzip[T, S, V](ait: SupportsIteration[tuple[T, S, V]], put_batch: int=...) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V]]: ...
@overload
async def aunzip[T, S, V, R](ait: SupportsIteration[tuple[T|R, S|R, V|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V]]: ...
@overload
async def aunzip[T, S, V, R](ait: SupportsIteration[tuple[T|R, S|R, V|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V]]: ...
@overload
async def aunzip[T, S, V, U](ait: SupportsIteration[tuple[T, S, V, U]], put_batch: int=...) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V], AUnzipConsumer[U]]: ...
@overload
async def aunzip[T, S, V, U, R](ait: SupportsIteration[tuple[T|R, S|R, V|R, U|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V], AUnzipConsumer[U]]: ...
@overload
async def aunzip[T, S, V, U, R](ait: SupportsIteration[tuple[T|R, S|R, V|R, U|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V], AUnzipConsumer[U]]: ...
@overload
async def aunzip[T](ait: SupportsIteration[tuple[T, ...]], put_batch: int=...) -> tuple[AUnzipConsumer[T], ...]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R, ...]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], ...]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R, ...]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], ...]: ...
@overload
async def aunzip(ait: SupportsIteration[tuple[Any, ...]], put_batch: int=..., fillvalue: Any=...) -> tuple[AUnzipConsumer[Any], ...]: ...
def merge[T](*I: SupportsIteration[T], reverse: bool=...) -> AsyncGenerator[T]: ...
def aflatten[T](it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[T]: ...
def batch[T](it: SupportsIteration[T], size: int, max_concurrent_batches: int|None=..., timeout: float|None=..., strict: bool=...) -> AsyncGenerator[list[T]]: ...
@overload
def achunked[T](it: SupportsIteration[T], n: int, strict: Literal[True]) -> AsyncGenerator[list[T]]: ...
@overload
def achunked[T](it: SupportsIteration[T], n: int|None, strict: Literal[False]=...) -> AsyncGenerator[list[T]]: ...
@overload
def asideeffect[T](f: Callable[[list[T]], object], it: SupportsIteration[T], /, *, size: int, before: Callable[[], object]|None=..., after: Callable[[], object]|None=...) -> AsyncGenerator[T]: ...
@overload
def asideeffect[T](f: Callable[[T], object], it: SupportsIteration[T], /, *, size: None=..., before: Callable[[], object]|None=..., after: Callable[[], object]|None=...) -> AsyncGenerator[T]: ...
def asliced[T: SupportsSlicing[Any]](seq: T, n: int, strict: bool=...) -> AsyncGenerator[T]: ...
def batch_buffer[T](items: SupportsIteration[T], batch_size: int, buffer_size: int, *, loop: AbstractEventLoop|None=...) -> deque[T]: ...
def buffer[T](it: AsyncIterable[T], maxsize: int=..., timeout: float|None=..., cooldown: float=..., *, loop: AbstractEventLoop|None=...) -> AsyncGenerator[T]: ...
def asplitat[T](it: SupportsIteration[T], pred: Callable[[T], bool], maxsplit: int=..., keep_sep: bool=...) -> AsyncGenerator[list[T]]: ...
def batch_process[T, R](items: SupportsIteration[T], size: int, processor: Callable[[list[T]], Awaitable[R]]) -> AsyncGenerator[R]: ...
def window[T](it: AsyncIterable[T], size: int, step: int=...) -> AsyncGenerator[tuple[T, ...], tuple[int, int]|None]: ...
async def aall(it: SupportsIteration[Any]) -> bool: ...
async def aany(it: SupportsIteration[Any]) -> bool: ...
@overload
async def amax[C: SupportsRichComparison](it: SupportsIteration[C], *, default: C=...) -> C: ...
@overload
async def amax[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], default: T=...) -> T: ...
@overload
async def amin[C: SupportsRichComparison](it: SupportsIteration[C], *, default: C=...) -> C: ...
@overload
async def amin[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], default: T=...) -> T: ...
@overload
def azip[T](i1: SupportsIteration[T], /) -> AsyncGenerator[tuple[T]]: ...
@overload
def azip[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def azip[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def azip[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def azip[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def azip[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def azip[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def azip[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def azip[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def azip[T](*I: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def azip(*I: SupportsIteration[Any], strict: bool=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
@overload
def amap[T, R](f: Callable[[T], Awaitable[R]], it: SupportsIteration[T], /, *, await_: Literal[True], strict: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, R](f: Callable[[T], R], it: SupportsIteration[T], /, *, await_: Literal[False]=..., strict: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, R](f: Callable[[T, S], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, R](f: Callable[[T, S], R], i1: SupportsIteration[T], i2: SupportsIteration[S], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, R](f: Callable[[T, S, V], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, R](f: Callable[[T, S, V], R], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, U, R](f: Callable[[T, S, V, U], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, U, R](f: Callable[[T, S, V, U], R], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, R](f: Callable[[*tuple[T, ...]], Awaitable[R]], /, *its: SupportsIteration[T], await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, R](f: Callable[[*tuple[T, ...]], R], /, *its: SupportsIteration[T], await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[R](f: Callable[..., Awaitable[R]], /, *its: SupportsIteration[Any], await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[R](f: Callable[..., R], /, *its: SupportsIteration[Any], await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
def afilter[T](f: Callable[[T], object]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
@overload
def amapif[T, R](f: Callable[[T], R], pred: Callable[[T], object]|None, it: SupportsIteration[T], /, await_: Literal[False]=...) -> AsyncGenerator[R]: '''Essentially the restriction of `amultimapif` to one (async) iterable, which allows for more flexibility.'''
@overload
def amapif[T, R](f: Callable[[T], Awaitable[R]], pred: Callable[[T], object]|None, it: SupportsIteration[T], /, await_: Literal[True]) -> AsyncGenerator[R]: ...
@overload
def amultimapif[*Ts, R](f: Callable[[*Ts], R], pred: Callable[[tuple[*Ts]], bool], /, *its: SupportsIteration[Any], await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amultimapif[*Ts, R](f: Callable[[*Ts], Awaitable[R]], pred: Callable[[tuple[*Ts]], bool], /, *its: SupportsIteration[Any], await_: Literal[True]) -> AsyncGenerator[R]: ...
@overload
def arange(stop: int, /) -> AsyncGenerator[int]: ...
@overload
def arange(start: int, stop: int, /) -> AsyncGenerator[int]: ...
@overload
def arange(start: int, stop: int, step: int, /) -> AsyncGenerator[int]: ...
@overload
def acount(start: int=..., step: int=...) -> AsyncGenerator[int]: ...
@overload
def acount(start: float, step: int=...) -> AsyncGenerator[float]: ...
@overload
def acount(start: float, step: float) -> AsyncGenerator[float]: ...
@overload
def acount(*, step: float) -> AsyncGenerator[float]: ...
def acycle[T](it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def arepeat[T](elem: T, n: int=...) -> AsyncGenerator[T]: ...
def aaccumulate[T](it: SupportsIteration[T], func: Callable[[T, T], T]=..., *, initial: T|None=...) -> AsyncGenerator[T]: ...
def acompress[T](data: SupportsIteration[T], selectors: SupportsIteration[Any]) -> AsyncGenerator[T]: ...
def adropwhile[T](pred: Callable[[T], bool], it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def afilterfalse[T](f: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
@overload
def agroupby[T](it: SupportsIteration[T], key: Callable[[T], T]=...) -> AsyncGenerator[tuple[T, AsyncGenerator[T]]]: ...
@overload
def agroupby[T, R](it: SupportsIteration[T], key: Callable[[T], R]) -> AsyncGenerator[tuple[R, AsyncGenerator[T]]]: ...
@overload
def aislice[T](it: SupportsIteration[T], stop: SupportsIndex|None=..., /) -> AsyncGenerator[T]: ...
@overload
def aislice[T](it: SupportsIteration[T], start: SupportsIndex|None, stop: SupportsIndex|None, step: SupportsIndex|None=..., /) -> AsyncGenerator[T]: ...
def aiterindex[T](it: SupportsIteration[T], value: T, start: int=..., stop: int|None=...) -> AsyncGenerator[int]: ...
def asieve(n: int) -> AsyncGenerator[int]: ...
def apairwise[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, T], None]: ...
def atriplewise[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, T, T], None]: ...
@overload
def aproduct[T](i1: SupportsIteration[T], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T]]: ...
@overload
def aproduct[T](i1: SupportsIteration[T], /, *, repeat: int) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aproduct[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def aproduct[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, repeat: int) -> AsyncGenerator[tuple[T|R, ...], None]: ...
@overload
def aproduct[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def aproduct[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V, ...], None]: ...
@overload
def aproduct[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def aproduct[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V|U, ...], None]: ...
@overload
def aproduct[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def aproduct[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V|U|S, ...], None]: ...
@overload
def aproduct[T](*its: SupportsIteration[T], repeat: int=...) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aproduct(i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], repeat: int=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
@overload
def astarmap[*Ts, R](f: Callable[[*Ts], R], it: SupportsIteration[tuple[*Ts]], /, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def astarmap[*Ts, R](f: Callable[[*Ts], Awaitable[R]], it: SupportsIteration[tuple[*Ts]], /, await_: Literal[True]) -> AsyncGenerator[R]: ...
def atakewhile[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
async def atotient(n: int) -> int: ...
async def asquaresum[X: (int, float, complex)](it: SupportsIteration[X]) -> X: ...
@overload
def aziplongest[T](i1: SupportsIteration[T], /) -> AsyncGenerator[tuple[T]]: ...
@overload
def aziplongest[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def aziplongest[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def aziplongest[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def aziplongest[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def aziplongest[T](*its: SupportsIteration[T], fillvalue: Any=...) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aziplongest(*its: SupportsIteration[Any], fillvalue: Any=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
async def asumprod[X: (int, float, complex)](p: SupportsIteration[X], q: SupportsIteration[X], /) -> X: ...
def aconvolve[X: (int, float, complex)](signal: SupportsIteration[X], kernel: SupportsIteration[X]) -> AsyncGenerator[X]: ...
@overload
def atabulate[T](f: Callable[[int], T], start: int=..., step: int=..., /, *, await_: Literal[False]=...) -> AsyncGenerator[T]: ...
@overload
def atabulate[T](f: Callable[[int], Awaitable[T]], start: int=..., step: int=..., /, *, await_: Literal[True]) -> AsyncGenerator[T]: ...
async def asum[X: (int, float, complex)](it: SupportsIteration[X], start: X=...) -> X: ...
async def aprod[X: (int, float, complex)](it: SupportsIteration[X], start: X=...) -> X: ...
async def amatprod[M: SupportsMatMul](it: SupportsIteration[M], start: M) -> M: ...
def atail[T](n: int, it: SupportsIteration[T], /) -> AsyncGenerator[T]: ...
async def amultinomial(*coeff: int) -> int: ...
async def to_tuple[T](it: SupportsIteration[T], /) -> tuple[T, ...]: ...
async def aconsume[T](it: SupportsIteration[T], n: int|None=...) -> T|None: ...
async def anth[T](it: SupportsIteration[T], n: int, default: T=...) -> T: ...
async def aallequal[T](it: SupportsIteration[T], key: Callable[[T], Any]=..., strict: bool=...) -> bool: ...
def acombinations[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[tuple[T, ...], None]: ...
def acombinations_with_replacement[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[tuple[T, ...], None]: ...
def apermutations[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[tuple[T, ...], None]: ...
def apowerset[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
async def aquantify[T](it: SupportsIteration[T], pred: Callable[[T], bool]=...) -> int: ...
def apadnone[T](it: SupportsIteration[T]) -> AsyncGenerator[T|None]: ...
def agrouper[T](it: SupportsIteration[T], n: int, fillvalue: T=...) -> AsyncGenerator[tuple[T|None, ...], None]: ...
def aroundrobin[T](*its: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def aroundrobin2[T](*its: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def aunique_everseen[T](it: SupportsIteration[T], key: Callable[[T], Any]=...) -> AsyncGenerator[T]: ...
def aunique_justseen[T](it: SupportsIteration[T], key: Callable[[T], Any]=...) -> AsyncGenerator[T]: ...
def aunique[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison]|None=..., reverse: bool=...) -> AsyncGenerator[T]: ...
def ancycles[T](it: SupportsIteration[T], n: int) -> AsyncGenerator[T]: ...
def apartition[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> tuple[AsyncGenerator[T], AsyncGenerator[T]]: ...
def aiterexcept[T](f: Callable[[], Awaitable[T]], exc: Exceptable, first: Callable[[], Awaitable[T]]=...) -> AsyncGenerator[T]: ...
async def ailen(it: SupportsIteration[Any]) -> int: ...
def aiterate[T](f: Callable[[T], Awaitable[T]], start: T) -> AsyncGenerator[T]: ...
def with_aiter[T](actxmgr: AsyncContextManager[SupportsIteration[T]]) -> AsyncGenerator[T]: ...
@overload
def asorted[C: SupportsRichComparison](it: SupportsIteration[C], *, reverse: bool=...) -> list[C]: ...
@overload
def asorted[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], reverse: bool=...) -> list[T]: ...
def acanonical[T](it: SupportsIteration[T]) -> list[T]: ...
def adistinctpermutations[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[tuple[T, ...], None]: ...
def auniquetoeach[H: Hashable](*its: SupportsIteration[H]) -> AsyncGenerator[AsyncGenerator[H]]: ...
def aderangements[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[T]: ...
def aintersperse[T](e: T, it: SupportsIteration[T], n: int=...) -> AsyncGenerator[T]: ...
def ainterleave_stopearly[T](*it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def ainterleave[T](*it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def aspy[T](it: SupportsIteration[T], n: int=...) -> tuple[AsyncGenerator[T], AsyncGenerator[T]]: ...
def ainterleaveevenly[T](its: SupportsIteration[SupportsIteration[T]], lengths: SupportsIteration[int]|None=...) -> AsyncGenerator[T]: ...
def ainterleaverandomly[T](its: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[T]: ...
def acollapse(it: SupportsIteration[Any], base_typ: tuple[type, ...]|type=..., levels: int|None=...) -> AsyncGenerator[Any]: ...
async def afirsttrue[T](it: SupportsIteration[T], default: T=..., pred: Callable[[T], Any]=...) -> T: ...
def aprepend[T](val: T, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def arandomproduct[T](*a: SupportsIteration[T], n: int=...) -> AsyncGenerator[T]: ...
def arandomcombination[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[T]: ...
def arandom_combination_with_replacement[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[T]: ...
def arandompermutation[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[T]: ...
async def afirst[T](it: SupportsIteration[T], default: T=...) -> T: ...
async def alast[T](it: SupportsIteration[T], default: T=...) -> T: ...
async def anthorlast[T](it: SupportsIteration[T], n: int, default: T=...) -> T: ...
def abeforeandafter[T](pred: Callable[[T], bool], it: SupportsIteration[T]) -> tuple[AsyncGenerator[T], AsyncGenerator[T]]: ...
def anthcombination[T](it: SupportsIteration[T], r: int, idx: int) -> AsyncGenerator[T]: ...
def asubslices[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
def arepeatfunc[T, *Ts](f: Callable[[*Ts], Awaitable[T]], times: int|None=..., *a: *Ts) -> AsyncGenerator[T]: ...
def apolynomialfromroots[X: (int, float, complex)](roots: SupportsIteration[X]) -> AsyncGenerator[X]: ...
def atranspose[T](it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[tuple[T, ...], None]: ...
def aflattentensor(tensor: SupportsIteration[Any], base_typ: tuple[type, ...]|type=...) -> AsyncGenerator[Any]: ...
def apolynomialderivative[X: (int, float, complex)](coeff: SupportsIteration[X]) -> AsyncGenerator[X]: ...
async def apolynomialeval[X: (int, float, complex)](coeff: SupportsIteration[X], x: X) -> X: ...
@overload
def areshape[T](mat: SupportsIteration[SupportsIteration[T]], shape: int) -> AsyncGenerator[list[T]]: ...
@overload
def areshape(mat: SupportsIteration[Any], shape: SupportsIteration[int]) -> AsyncGenerator[list[Any]]: ...
def afactor(n: int) -> AsyncGenerator[int]: ...
@overload
def arunningmedian(it: SupportsIteration[int], *, maxlen: SupportsIndex|None=...) -> AsyncGenerator[int]: ...
@overload
def arunningmedian(it: SupportsIteration[float], *, maxlen: SupportsIndex|None=...) -> AsyncGenerator[float]: ...
async def arandomderangement[T](it: SupportsIteration[T]) -> tuple[T, ...]: ...
def amatmul[X: (int, float, complex)](M: SupportsIteration[SupportsIteration[X]], N: SupportsIteration[SupportsIteration[X]]) -> AsyncGenerator[tuple[X, ...], None]: ...
def mat_vec_mul(M: SupportsIteration[SupportsIteration[int]], V: SupportsIteration[int]) -> AsyncGenerator[int]: ...
async def vecs_eq[T](u: SupportsIteration[T], v: SupportsIteration[T], cmpeq: Callable[[T, T], bool]=..., *, strict: bool=...) -> bool: ...
async def afrievalds(A: SupportsIteration[SupportsIteration[int]], B: SupportsIteration[SupportsIteration[int]], C: SupportsIteration[SupportsIteration[int]], k: int=...) -> bool: ...
async def basic_collect[T](it: SupportsIteration[T], n: int) -> list[T]: ...
def asubstrings[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def asubstrindices[S: (str, bytes, bytearray)](seq: S, reverse: bool=...) -> AsyncGenerator[tuple[S, int, int], None]: ...
@overload
def asubstrindices[T](seq: SupportsSlicing[T], reverse: bool=...) -> AsyncGenerator[tuple[Iterable[T], int, int], None]: ...
def iter_future[T](it: SupportsIteration[T], summaryf: Callable[[SupportsIteration[T]], Awaitable[Any]]=...) -> Future[float]: ...
def agetitems_from_indices[T](it: SupportsIteration[T], indices: SupportsIteration[SupportsIndex], setatend: Future[float]|None=..., finish: bool=...) -> list[Future[T]]:
    '''Takes an (async) iterable and an (async) iterable of integers interpreted as indices, and immediately returns a list of futures whose eventual results represent
    the items of that iterable at the index, beginning consumption of the iterable in the background. Exceptions will be set in the futures that are not done if results
    are encountered during iteration or if the index is out of bounds. Supports negative indices. Do not set the result of any returned future; instead, if the result
    is no longer relevant, cancel the future. The consumption stops as soon as all the required results are pushed into the respective futures. Pass in a Future for the
    setatend parameter, which cancels the background consumption of the async iterable once it is done and cancels the undone futures.'''
def aintersend[T, R](i1: AsyncGenerator[T, R], i2: AsyncGenerator[R, T]) -> AsyncGenerator[tuple[T, R], None]: ...
def asendstream[T, R](i1: AsyncGenerator[T, R], i2: SupportsIteration[R]) -> AsyncGenerator[T]: ...
@overload
def acat[T](first: T) -> AsyncGenerator[T, T]: ...
@overload
def acat[T](first: None=...) -> AsyncGenerator[T|None, T|None]: ...
def aforever() -> AsyncGenerator[None]: ...
async def aguessmax[T](it: SupportsIteration[T], estlen: int, *, key: Callable[[T], SupportsRichComparison]=..., default: T=..., finish_event: Event|None=...) -> T: ...
async def aguessmin[T](it: SupportsIteration[T], estlen: int, *, key: Callable[[T], SupportsRichComparison]=..., default: T=..., finish_event: Event|None=...) -> T: ...
def apowersoftwo(*, init: int=..., init_shift: int=...) -> AsyncGenerator[int]: ...
def areversed[T](it: SupportsIteration[T]|Reversible[T], /) -> AsyncGenerator[T]: ...
async def to_list[T](it: SupportsIteration[T], /) -> list[T]: ...
async def aisprime(n: int) -> bool: ...
def adft(xarr: SupportsIteration[complex], /) -> AsyncGenerator[complex]: ...
def aidft(Xarr: SupportsIteration[complex], /) -> AsyncGenerator[complex]: ...
def apowers[X: (int, float, complex)](base: X, start: X=...) -> AsyncGenerator[X]: ...
def arunlengthencode[T](it: SupportsIteration[T], /) -> AsyncGenerator[tuple[T, int], None]: ...
def arunlengthdecode[T](it: SupportsIteration[tuple[T, int]], /) -> AsyncGenerator[T]: ...
@overload
async def aargmin[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison], default: int=...) -> int: ...
@overload
async def aargmin[C: SupportsRichComparison](it: SupportsIteration[C], *, default: int=...) -> int: ...
@overload
async def aargmax[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison], default: int=...) -> int: ...
@overload
async def aargmax[C: SupportsRichComparison](it: SupportsIteration[C], *, default: int=...) -> int: ...
def arunningmean[X: (int|float, complex)](it: SupportsIteration[X]) -> AsyncGenerator[X]: ...
@overload
def apowersetofsets[T](it: SupportsIteration[T], *, frozen: Literal[True]=...) -> AsyncGenerator[frozenset[T]]: ...
@overload
def apowersetofsets[T](it: SupportsIteration[T], *, frozen: Literal[False]) -> AsyncGenerator[set[T]]: ...
def aserialize[T](it: SupportsIteration[T]) -> AsyncGenerator[T]: ...