from ._internal.protocols import SupportsIteration, ValidExcType
from .mixins import EventualLoopMixin, LoopContextMixin
from types import TracebackType
from typing import Self, Any, overload
from asyncio.futures import Future
from _collections_abc import AsyncGenerator, Callable
__all__ = 'anullcontext', 'apeekable', 'achain', 'abucket', 'OnlineSorter'
class anullcontext:
    async def __aenter__(self) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
class achain[T]:
    @classmethod
    def from_iterable(cls, it: SupportsIteration[SupportsIteration[T]]) -> Self: ...
    def __init__(self, *its: SupportsIteration[T]): ...
    def __aiter__(self) -> AsyncGenerator[T, None]: ...
class apeekable[T=Any](EventualLoopMixin):
    def __init__(self, it: SupportsIteration[T]): ...
    def __aiter__(self) -> Self: ...
    def __bool__(self) -> bool: ...
    async def peek(self, default: T=...) -> T: ...
    def prepend(self, /, *items: T) -> None: ...
    async def __anext__(self) -> T: ...
    @overload
    def __getitem__(self, idx: slice, /) -> tuple[T, ...]: ...
    @overload
    def __getitem__(self, idx: int, /) -> T: ...
class abucket[T, R](LoopContextMixin):
    def __init__(self, it: SupportsIteration[T], key: Callable[[T], R], validator: Callable[[R], bool]): ...
    def __contains__(self, v: R) -> bool: ...
    def __aiter__(self) -> AsyncGenerator[T, None]: ...
    def __getitem__(self, val: R, /) -> AsyncGenerator[T, None]: ...
class OnlineSorter[T]:
    def __init__(self, it: SupportsIteration[T]): ...
    def __aiter__(self) -> Self: ...
    def __anext__(self) -> T: ...
    def asend(self, item: T) -> Future[None]: ...
    def athrow(self, typ, val=None, tb=None) -> Future[Any]: ...
    def aclose(self) -> Future[None]: ...