from collections import deque
from asyncio.locks import Event
from typing import SupportsIndex, Self, Any, Literal, Reversible, overload, type_check_only
from _collections_abc import Awaitable, Iterable, AsyncIterable, AsyncGenerator, Callable, Hashable
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from ._internal.protocols import SupportsIteration, Exceptable, SupportsRichComparison, AsyncContextManager, SupportsSlicing
__all__ = 'tee', 'aunzip', 'merge_async_iters', 'aflatten', 'batch', 'achunked', 'asideeffect', 'asliced', 'batch_buffer', 'buffer', 'asplitat', 'batch_process', 'window', 'aall', 'aany', 'amax', 'amin', 'azip', 'amap', 'afilter', 'arange', 'acount', 'acycle', 'arepeat', 'aaccumulate', 'acompress', 'adropwhile', 'afilterfalse', 'agroupby', 'aislice', 'aiterindex', 'asieve', 'apairwise', 'atriplewise', 'aproduct', 'astarmap', 'atakewhile', 'atotient', 'asquaresum', 'aziplongest', 'asumprod', 'aconvolve', 'atabulate', 'asum', 'aprod', 'atail', 'amultinomial', 'to_tuple', 'anth', 'aconsume', 'aallequal', 'acombinations', 'acombinations_with_replacement', 'apermutations', 'apowerset', 'aquantify', 'apadnone', 'agrouper', 'aroundrobin', 'aroundrobin2', 'aunique_everseen', 'aunique_justseen', 'aunique', 'ancycles', 'apartition', 'aiterexcept', 'ailen', 'aiterate', 'with_aiter', 'asorted', 'acanonical', 'adistinctpermutations', 'auniquetoeach', 'aderangements', 'aintersperse', 'ainterleave_stopearly', 'ainterleave', 'ainterleaveevenly', 'ainterleaverandomly', 'aspy', 'acollapse', 'afirsttrue', 'aprepend', 'arandomproduct', 'arandomcombination', 'arandom_combination_with_replacement', 'arandompermutation', 'afirst', 'alast', 'anthorlast', 'abeforeandafter', 'anthcombination', 'arepeatfunc', 'asubslices', 'atranspose', 'apolynomialfromroots', 'apolynomialeval', 'apolynomialderivative', 'areshape', 'afactor', 'arunningmedian', 'arandomderangement', 'amatmul', 'mat_vec_mul', 'vecs_eq', 'afrievalds', 'basic_collect', 'asubstrings', 'asubstrindices', 'iter_future', 'agetitems_from_indices', 'aintersend', 'asendstream', 'acat', 'aforever', 'aguessmax', 'aguessmin', 'apowersoftwo', 'amapif', 'amultimapif', 'fmap', 'fmap_sequential', 'map_on_map', 'amatprod', 'areversed', 'to_list'
async def fmap[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs): ...
async def fmap_sequential[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs): ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], V], inner: Callable[[T], SupportsIteration[R]], it: SupportsIteration[T], *, inner_await: Literal[False]=..., outer_await: Literal[False]=...) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], Awaitable[V]], inner: Callable[[T], SupportsIteration[R]], it: SupportsIteration[T], *, inner_await: Literal[False]=..., outer_await: Literal[True]) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], V], inner: Callable[[T], Awaitable[SupportsIteration[R]]], it: SupportsIteration[T], *, inner_await: Literal[True], outer_await: Literal[False]=...) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], Awaitable[V]], inner: Callable[[T], Awaitable[SupportsIteration[R]]], it: SupportsIteration[T], *, inner_await: Literal[True], outer_await: Literal[True]) -> AsyncGenerator[tuple[V, ...], None]: ...
def tee[T](it: SupportsIteration[T], n: int=2, *, maxqsize: int=..., put_exc: bool=True, loop: AbstractEventLoop|None=...) -> tuple[AsyncGenerator[T], ...]: ...
@type_check_only
class _aunzip_consumer[T]:
    '''Not exposed.'''
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> T: ...
    def close(self) -> None: ...
@overload
async def aunzip[T](ait: SupportsIteration[tuple[T]], put_batch: int=...) -> tuple[_aunzip_consumer[T]]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R]], put_batch: int, fillvalue: R) -> tuple[_aunzip_consumer[T]]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R]], *, fillvalue: R) -> tuple[_aunzip_consumer[T]]: ...
@overload
async def aunzip[T, S](ait: SupportsIteration[tuple[T, S]], put_batch: int=...) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S]]: ...
@overload
async def aunzip[T, S, R](ait: SupportsIteration[tuple[T|R, S|R]], put_batch: int, fillvalue: R) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S]]: ...
@overload
async def aunzip[T, S, R](ait: SupportsIteration[tuple[T|R, S|R]], *, fillvalue: R) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S]]: ...
@overload
async def aunzip[T, S, V](ait: SupportsIteration[tuple[T, S, V]], put_batch: int=...) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S], _aunzip_consumer[V]]: ...
@overload
async def aunzip[T, S, V, R](ait: SupportsIteration[tuple[T|R, S|R, V|R]], put_batch: int, fillvalue: R) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S], _aunzip_consumer[V]]: ...
@overload
async def aunzip[T, S, V, R](ait: SupportsIteration[tuple[T|R, S|R, V|R]], *, fillvalue: R) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S], _aunzip_consumer[V]]: ...
@overload
async def aunzip[T, S, V, U](ait: SupportsIteration[tuple[T, S, V, U]], put_batch: int=...) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S], _aunzip_consumer[V], _aunzip_consumer[U]]: ...
@overload
async def aunzip[T, S, V, U, R](ait: SupportsIteration[tuple[T|R, S|R, V|R, U|R]], put_batch: int, fillvalue: R) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S], _aunzip_consumer[V], _aunzip_consumer[U]]: ...
@overload
async def aunzip[T, S, V, U, R](ait: SupportsIteration[tuple[T|R, S|R, V|R, U|R]], *, fillvalue: R) -> tuple[_aunzip_consumer[T], _aunzip_consumer[S], _aunzip_consumer[V], _aunzip_consumer[U]]: ...
@overload
async def aunzip[T](ait: SupportsIteration[tuple[T, ...]], put_batch: int=...) -> tuple[_aunzip_consumer[T], ...]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R, ...]], put_batch: int, fillvalue: R) -> tuple[_aunzip_consumer[T], ...]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R, ...]], *, fillvalue: R) -> tuple[_aunzip_consumer[T], ...]: ...
@overload
async def aunzip(ait: SupportsIteration[tuple[Any, ...]], put_batch: int=..., fillvalue: Any=...) -> tuple[_aunzip_consumer[Any], ...]: ...
def merge_async_iters[T](*I: SupportsIteration[T], reverse: bool=...) -> AsyncGenerator[T, None]: ...
def aflatten[T](it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[T, None]: ...
def batch[T](it: SupportsIteration[T], size: int, max_concurrent_batches: int|None=..., timeout: float|None=..., strict: bool=...) -> AsyncGenerator[list[T], None]: ...
@overload
def achunked[T](it: SupportsIteration[T], n: int, strict: Literal[True]) -> AsyncGenerator[list[T], None]: ...
@overload
def achunked[T](it: SupportsIteration[T], n: int|None, strict: Literal[False]=...) -> AsyncGenerator[list[T], None]: ...
@overload
def asideeffect[T](f: Callable[[list[T]]], it: SupportsIteration[T], /, *, size: int, before: Callable[[]]|None=..., after: Callable[[]]|None=...) -> AsyncGenerator[T, None]: ...
@overload
def asideeffect[T](f: Callable[[T]], it: SupportsIteration[T], /, *, size: None=..., before: Callable[[]]|None=..., after: Callable[[]]|None=...) -> AsyncGenerator[T, None]: ...
def asliced[T](seq: SupportsSlicing[T], n: int, strict: bool=...): ...
def batch_buffer[T](items: SupportsIteration[T], batch_size: int, buffer_size: int, *, loop: AbstractEventLoop|None=...) -> deque[T]: ...
def buffer[T](it: AsyncIterable[T], maxsize: int=..., timeout: float|None=..., cooldown: float=..., *, loop: AbstractEventLoop|None=...) -> AsyncGenerator[T, None]: ...
def asplitat[T](it: SupportsIteration[T], pred: Callable[[T], bool], maxsplit: int=..., keep_sep: bool=...) -> AsyncGenerator[list[T], None]: ...
def batch_process[T, R](items: SupportsIteration[T], size: int, processor: Callable[[list[T]], Awaitable[R]]) -> AsyncGenerator[R, None]: ...
def window[T](it: AsyncIterable[T], size: int, step: int=...) -> AsyncGenerator[tuple[T, ...], tuple[int, int]|None]: ...
async def aall(it: SupportsIteration[Any]) -> bool: ...
async def aany(it: SupportsIteration[Any]) -> bool: ...
@overload
async def amax[C: SupportsRichComparison](it: SupportsIteration[C]) -> C: ...
@overload
async def amax[T](it: SupportsIteration[T], *, cmp: Callable[[T, T], bool]) -> T: ...
@overload
async def amax[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison]) -> T: ...
@overload
async def amax[C: SupportsRichComparison](it: SupportsIteration[C], *, default: C) -> C: ...
@overload
async def amax[T](it: SupportsIteration[T], *, cmp: Callable[[T, T], bool], default: T) -> T: ...
@overload
async def amax[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], default: T) -> T: ...
@overload
async def amin[C: SupportsRichComparison](it: SupportsIteration[C]) -> C: ...
@overload
async def amin[T](it: SupportsIteration[T], *, cmp: Callable[[T, T], bool]) -> T: ...
@overload
async def amin[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison]) -> T: ...
@overload
async def amin[C: SupportsRichComparison](it: SupportsIteration[C], *, default: C) -> C: ...
@overload
async def amin[T](it: SupportsIteration[T], *, cmp: Callable[[T, T], bool], default: T) -> T: ...
@overload
async def amin[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], default: T) -> T: ...
@overload
def azip[T](i1: SupportsIteration[T], /) -> AsyncGenerator[tuple[T], None]: ...
@overload
def azip[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def azip[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def azip[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def azip[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def azip[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def azip[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def azip[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def azip[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def azip[T](*I: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def azip(*I: SupportsIteration[Any], strict: bool=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
@overload
def amap[T, R](f: Callable[[T], Awaitable[R]], it: SupportsIteration[T], /, *, await_: Literal[True], strict: Literal[False]=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, R](f: Callable[[T], R], it: SupportsIteration[T], /, *, await_: Literal[False]=..., strict: Literal[False]=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, S, R](f: Callable[[T, S], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, S, R](f: Callable[[T, S], R], i1: SupportsIteration[T], i2: SupportsIteration[S], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, S, V, R](f: Callable[[T, S, V], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, S, V, R](f: Callable[[T, S, V], R], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, S, V, U, R](f: Callable[[T, S, V, U], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, S, V, U, R](f: Callable[[T, S, V, U], R], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, R](f: Callable[[*tuple[T, ...]], Awaitable[R]], /, *its: SupportsIteration[T], await_: Literal[True], strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[T, R](f: Callable[[*tuple[T, ...]], R], /, *its: SupportsIteration[T], await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[R](f: Callable[..., Awaitable[R]], /, *its: SupportsIteration[Any], await_: Literal[True], strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def amap[R](f: Callable[..., R], /, *its: SupportsIteration[Any], await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R, None]: ...
@overload
def afilter[T](f: Callable[[T]], it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
@overload
def afilter[T](f: None, it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
@overload
def amapif[T, R](f: Callable[[T], R], pred: Callable[[T]]|None, it: SupportsIteration[T], /, await_: Literal[False]=...) -> AsyncGenerator[R, None]: '''Essentially the restriction of `amultimapif` to one (async) iterable, which allows for more flexibility.'''
@overload
def amapif[T, R](f: Callable[[T], Awaitable[R]], pred: Callable[[T]]|None, it: SupportsIteration[T], /, await_: Literal[True]) -> AsyncGenerator[R, None]: ...
@overload
def amultimapif[*Ts, R](f: Callable[[*Ts], R], pred: Callable[[tuple[*Ts]], bool], /, *its: SupportsIteration, await_: Literal[False]=...) -> AsyncGenerator[R, None]: ...
@overload
def amultimapif[*Ts, R](f: Callable[[*Ts], Awaitable[R]], pred: Callable[[tuple[*Ts]], bool], /, *its: SupportsIteration, await_: Literal[True]) -> AsyncGenerator[R, None]: ...
@overload
def arange(stop: int, /) -> AsyncGenerator[int, None]: ...
@overload
def arange(start: int, stop: int, /) -> AsyncGenerator[int, None]: ...
@overload
def arange(start: int, stop: int, step: int, /) -> AsyncGenerator[int, None]: ...
@overload
def acount(start: int=..., step: int=...) -> AsyncGenerator[int, None]: ...
@overload
def acount(start: float, step: int=...) -> AsyncGenerator[float, None]: ...
@overload
def acount(start: float, step: float) -> AsyncGenerator[float, None]: ...
@overload
def acount(start: int, step: float) -> AsyncGenerator[float, None]: ...
@overload
def acount(*, step: float) -> AsyncGenerator[float, None]: ...
def acycle[T](it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def arepeat[T](elem: T, n: int=...) -> AsyncGenerator[T, None]: ...
def aaccumulate[T](it: SupportsIteration[T], func: Callable[[T, T], T]=..., *, initial: T|None=...) -> AsyncGenerator[T, None]: ...
def acompress[T](data: SupportsIteration[T], selectors: SupportsIteration[Any]) -> AsyncGenerator[T, None]: ...
def adropwhile[T](pred: Callable[[T], bool], it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def afilterfalse[T](f: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
@overload
def agroupby[T](it: SupportsIteration[T], key: Callable[[T], T]=...) -> AsyncGenerator[tuple[T, AsyncGenerator[T, None]], None]: ...
@overload
def agroupby[T, R](it: SupportsIteration[T], key: Callable[[T], R]) -> AsyncGenerator[tuple[R, AsyncGenerator[T, None]], None]: ...
@overload
def aislice[T](it: SupportsIteration[T], stop: SupportsIndex|None=..., /) -> AsyncGenerator[T, None]: ...
@overload
def aislice[T](it: SupportsIteration[T], start: SupportsIndex|None, stop: SupportsIndex|None, step: SupportsIndex|None=..., /) -> AsyncGenerator[T, None]: ...
def aiterindex[T](it: SupportsIteration[T], value: T, start: int=..., stop: int|None=...) -> AsyncGenerator[int, None]: ...
def asieve(n: int) -> AsyncGenerator[int, None]: ...
def apairwise[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, T], None]: ...
def atriplewise[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, T, T], None]: ...
@overload
def aproduct[T](i1: SupportsIteration[T], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T], None]: ...
@overload
def aproduct[T](i1: SupportsIteration[T], /, *, repeat: int) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aproduct[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def aproduct[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, repeat: int) -> AsyncGenerator[tuple[T|R, ...], None]: ...
@overload
def aproduct[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def aproduct[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V, ...], None]: ...
@overload
def aproduct[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def aproduct[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V|U, ...], None]: ...
@overload
def aproduct[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def aproduct[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V|U|S, ...], None]: ...
@overload
def aproduct[T](*its: SupportsIteration[T], repeat: int=...) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aproduct(i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], repeat: int=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
@overload
def astarmap[*Ts, R](f: Callable[[*Ts], R], it: SupportsIteration[tuple[*Ts]], /, await_: Literal[False]=...) -> AsyncGenerator[R, None]: ...
@overload
def astarmap[*Ts, R](f: Callable[[*Ts], Awaitable[R]], it: SupportsIteration[tuple[*Ts]], /, await_: Literal[True]) -> AsyncGenerator[R, None]: ...
def atakewhile[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
async def atotient(n: int) -> int: ...
async def asquaresum[X: (int, float, complex)](it: SupportsIteration[X]) -> X: ...
@overload
def aziplongest[T](i1: SupportsIteration[T], /) -> AsyncGenerator[tuple[T], None]: ...
@overload
def aziplongest[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def aziplongest[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def aziplongest[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def aziplongest[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def aziplongest[T](*its: SupportsIteration[T], fillvalue: Any=...) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aziplongest(*its: SupportsIteration[Any], fillvalue: Any=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
async def asumprod[X: (int, float, complex)](p: SupportsIteration[X], q: SupportsIteration[X], /) -> X: ...
def aconvolve[X: (int, float, complex)](signal: SupportsIteration[X], kernel: SupportsIteration[X]) -> AsyncGenerator[X, None]: ...
@overload
def atabulate[T](f: Callable[[int], T], start: int=..., step: int=..., /, *, await_: Literal[False]=...) -> AsyncGenerator[T, None]: ...
@overload
def atabulate[T](f: Callable[[int], Awaitable[T]], start: int=..., step: int=..., /, *, await_: Literal[True]) -> AsyncGenerator[T, None]: ...
async def asum[X: (int, float, complex)](it: SupportsIteration[X], start: X=...) -> X: ...
async def aprod[X: (int, float, complex)](it: SupportsIteration[X], start: X=...) -> X: ...
async def amatprod(it: SupportsIteration, start: Any) -> Any: ...
def atail[T](n: int, it: SupportsIteration[T], /) -> AsyncGenerator[T, None]: ...
async def amultinomial(*c: int) -> int: ...
async def to_tuple[T](it: SupportsIteration[T], /) -> tuple[T, ...]: ...
async def aconsume[T](it: SupportsIteration[T], n: int|None=...) -> T|None: ...
async def anth[T](it: SupportsIteration[T], n: int, default: T=...) -> T: ...
async def aallequal[T](it: SupportsIteration[T], key: Callable[[T], Any]=..., strict: bool=...) -> bool: ...
def acombinations[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[tuple[T, ...], None]: ...
def acombinations_with_replacement[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[tuple[T, ...], None]: ...
def apermutations[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[tuple[T, ...], None]: ...
def apowerset[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
async def aquantify[T](it: SupportsIteration[T], pred: Callable[[T], bool]=...) -> int: ...
def apadnone[T](it: SupportsIteration[T]) -> AsyncGenerator[T|None, None]: ...
def agrouper[T](it: SupportsIteration[T], n: int, fillvalue: T=...) -> AsyncGenerator[tuple[T|None, ...], None]: ...
def aroundrobin[T](*its: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def aroundrobin2[T](*its: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def aunique_everseen[T](it: SupportsIteration[T], key: Callable[[T]]=...) -> AsyncGenerator[T, None]: ...
def aunique_justseen[T](it: SupportsIteration[T], key: Callable[[T]]=...) -> AsyncGenerator[T, None]: ...
def aunique[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison]|None=..., reverse: bool=...) -> AsyncGenerator[T, None]: ...
def ancycles[T](it: SupportsIteration[T], n: int) -> AsyncGenerator[T, None]: ...
def apartition[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> tuple[AsyncGenerator[T, None], AsyncGenerator[T, None]]: ...
def aiterexcept[T](f: Callable[[], Awaitable[T]], exc: Exceptable) -> AsyncGenerator[T, None]: ...
async def ailen(it: SupportsIteration) -> int: ...
def aiterate[T](f: Callable[[T], Awaitable[T]], start: T) -> AsyncGenerator[T, None]: ...
def with_aiter[T](actxmgr: AsyncContextManager[SupportsIteration[T]]) -> AsyncGenerator[T, None]: ...
@overload
def asorted[C: SupportsRichComparison](it: SupportsIteration[C], *, reverse: bool=...) -> list[C]: ...
@overload
def asorted[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], reverse: bool=...) -> list[T]: ...
def acanonical[T](it: SupportsIteration[T]) -> list[T]: return asorted(it, key=id, reverse=True)
def adistinctpermutations[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[tuple[T, ...], None]: ...
def auniquetoeach[H: Hashable](*its: SupportsIteration[H]) -> AsyncGenerator[AsyncGenerator[H, None], None]: ...
def aderangements[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[T, None]: ...
def aintersperse[T](e: T, it: SupportsIteration[T], n: int=...) -> AsyncGenerator[T, None]: ...
def ainterleave_stopearly[T](*it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def ainterleave[T](*it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def aspy[T](it: SupportsIteration[T], n: int=...) -> tuple[AsyncGenerator[T, None], AsyncGenerator[T, None]]: ...
def ainterleaveevenly[T](its: SupportsIteration[SupportsIteration[T]], lengths: SupportsIteration[int]|None=...) -> AsyncGenerator[T, None]: ...
def ainterleaverandomly[T](its: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[T, None]: ...
def acollapse(it: SupportsIteration[Any], base_typ: tuple[type, ...]|type, levels=...) -> AsyncGenerator[Any, None]: ...
@overload
async def afirsttrue[T](it: Iterable[T], default: T, pred: Callable[[T]]) -> T: ...
@overload
async def afirsttrue[T](it: Iterable[T], *, pred: Callable[[T]]) -> T: ...
@overload
async def afirsttrue[T](it: Iterable[T], default: T) -> T: ...
@overload
async def afirsttrue[T](it: Iterable[T]) -> T: ...
@overload
async def afirsttrue[T](it: AsyncIterable[T], default: T, pred: Callable[[T]]) -> T: ...
@overload
async def afirsttrue[T](it: AsyncIterable[T], *, pred: Callable[[T]]) -> T: ...
@overload
async def afirsttrue[T](it: AsyncIterable[T], default: T) -> T: ...
@overload
async def afirsttrue[T](it: AsyncIterable[T]) -> T: ...
def aprepend[T](val: T, it: SupportsIteration[T]) -> AsyncGenerator[T, None]: ...
def arandomproduct[T](*a: SupportsIteration[T], n: int=...) -> AsyncGenerator[T, None]: ...
def arandomcombination[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[T, None]: ...
def arandom_combination_with_replacement[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[T, None]: ...
def arandompermutation[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[T, None]: ...
@overload
async def afirst[T](it: SupportsIteration[T]) -> T: ...
@overload
async def afirst[T](it: SupportsIteration[T], default: T) -> T: ...
async def alast[T](it: SupportsIteration[T], default: T=...) -> T: ...
async def anthorlast[T](it: SupportsIteration[T], n: int, default: T=...) -> T: ...
def abeforeandafter[T](pred: Callable[[T], bool], it: SupportsIteration[T]) -> tuple[AsyncGenerator[T, None], AsyncGenerator[T, None]]: ...
def anthcombination[T](it: SupportsIteration[T], r: int, idx: int) -> AsyncGenerator[T, None]: ...
def asubslices[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
def arepeatfunc[T, *Ts](f: Callable[[*Ts], Awaitable[T]], times: int|None=..., *a: *Ts) -> AsyncGenerator[T, None]: ...
def apolynomialfromroots[X: (int, float, complex)](roots: SupportsIteration[X]) -> AsyncGenerator[X, None]: ...
def atranspose[T](it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[tuple[T, ...], None]: ...
def aflattentensor(tensor: SupportsIteration[Any], base: tuple[type, ...]|type) -> AsyncGenerator[Any, None]: ...
def apolynomialderivative[X: (int, float, complex)](coeff: SupportsIteration[X]) -> AsyncGenerator[X, None]: ...
async def apolynomialeval[X: (int, float, complex)](coeff: SupportsIteration[X], x: X) -> X: ...
@overload
def areshape(mat: SupportsIteration[SupportsIteration], shape: int) -> AsyncGenerator[list, None]: ...
@overload
def areshape(mat: SupportsIteration, shape: SupportsIteration[int]) -> AsyncGenerator[list, None]: ...
def afactor(n: int) -> AsyncGenerator[int, None]: ...
@overload
def arunningmedian(it: SupportsIteration[float], *, maxlen: SupportsIndex|None=...) -> AsyncGenerator[float, None]: ...
@overload
def arunningmedian(it: SupportsIteration[int], *, maxlen: SupportsIndex|None=...) -> AsyncGenerator[int, None]: ...
async def arandomderangement[T](it: SupportsIteration[T]) -> tuple[T, ...]: ...
def amatmul[X: (int, float, complex)](M: SupportsIteration[SupportsIteration[X]], N: SupportsIteration[SupportsIteration[X]]) -> AsyncGenerator[tuple[X, ...]]: ...
def mat_vec_mul(M: SupportsIteration[SupportsIteration[int]], V: SupportsIteration[int]) -> AsyncGenerator[int, None]: ...
async def vecs_eq(u: SupportsIteration[int], v: SupportsIteration[int]) -> bool: ...
def afrievalds(A: SupportsIteration[SupportsIteration[int]], B: SupportsIteration[SupportsIteration[int]], C: SupportsIteration[SupportsIteration[int]], k: int=...) -> bool: ...
async def basic_collect[T](it: SupportsIteration[T], n: int) -> list[T]: ...
def asubstrings[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def asubstrindices[S: (str, bytes, bytearray)](seq: S, reverse: bool=...) -> AsyncGenerator[tuple[S, int, int], None]: ...
@overload
def asubstrindices[T](seq: SupportsSlicing[T], reverse: bool=...) -> AsyncGenerator[tuple[Iterable[T], int, int], None]: ...
def iter_future[T](it: SupportsIteration[T], summaryf: Callable[[SupportsIteration[T]], Awaitable]=...) -> Future[float]: ...
def agetitems_from_indices[T](it: SupportsIteration[T], indices: SupportsIteration[SupportsIndex], setatend: Future[float]|None=..., finish: bool=...) -> list[Future[T]]:
    '''Takes an (async) iterable and an (async) iterable of integers interpreted as indices, and immediately returns a list of futures whose eventual results represent
    the items of that iterable at the index, beginning consumption of the iterable in the background. Exceptions will be set in the futures that are not done if results
    are encountered during iteration or if the index is out of bounds. Supports negative indices. Do not set the result of any returned future; instead, if the result
    is no longer relevant, cancel the future. The consumption stops as soon as all the required results are pushed into the respective futures. Pass in a Future for the
    setatend parameter, which cancels the background consumption of the async iterable once it is done and cancels the undone futures.'''
def aintersend[T, R](i1: AsyncGenerator[T, R], i2: AsyncGenerator[R, T]) -> AsyncGenerator[tuple[T, R], None]: ...
def asendstream[T, R](i1: AsyncGenerator[T, R], i2: SupportsIteration[R]) -> AsyncGenerator[T, None]: ...
@overload
def acat[T](first: T) -> AsyncGenerator[T, T]: ...
@overload
def acat[T](first: None=...) -> AsyncGenerator[T|None, T|None]: ...
def aforever() -> AsyncGenerator[None, None]: ...
async def aguessmax[T](it: SupportsIteration[T], estlen: int, *, key: Callable[[T], SupportsRichComparison]|None=..., default: T=..., finish_event: Event|None=...) -> T: ...
async def aguessmin[T](it: SupportsIteration[T], estlen: int, *, key: Callable[[T], SupportsRichComparison]|None=..., default: T=..., finish_event: Event|None=...) -> T: ...
def apowersoftwo(*, init: int=..., init_shift: int=...) -> AsyncGenerator[int, None]: ...
def areversed[T](it: SupportsIteration[T]|Reversible[T], /) -> AsyncGenerator[T, None]: ...
async def to_list[T](it: SupportsIteration[T], /) -> list[T]: ...