'''Functional and chainable interface to get async generators from (async) iterables. Many of the algorithms here are taken from :mod:`more_itertools`.
However, since they must support both sync and async iterables, they are much less efficient than their sync counterparts.'''
from ._internal.types import AsyncContextManager, Exceptable, SupportsIteration, SupportsMatMul, SupportsRichComparison, SupportsSlicing, AUnzipConsumer
from _collections_abc import AsyncGenerator, Awaitable, Callable, Hashable, Iterable, Reversible
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from asyncio.locks import Event
from typing import Any, Literal, SupportsIndex, overload
__all__ = 'aaccumulate', 'aall', 'aallequal', 'aany', 'aargmax', 'aargmin', 'abeforeandafter', 'abfs', 'abrent', 'acanonical', 'acat', 'acollapse', 'acombinations', 'acombinations_with_replacement', 'acompress', 'aconsume', 'aconvolve', 'acount', 'acountdown', 'acycle', 'aderangements', 'adfs', 'adft', 'adistinctpermutations', 'adropwhile', 'afactor', 'afilter', 'afilterfalse', 'afirst', 'afirsttrue', 'aflatten', 'aflattentensor', 'aforever', 'afreivalds', 'agetitems_from_indices', 'agroupby', 'agrouper', 'aguessmax', 'aguessmin', 'ahammingdist', 'aidft', 'ailen', 'ainterleave', 'ainterleave_stopearly', 'ainterleaveevenly', 'ainterleaverandomly', 'aintersend', 'aintersperse', 'aislice', 'aisprime', 'aiterate', 'aiterexcept', 'aiterindex', 'alast', 'amap', 'amapif', 'amatmul', 'amatprod', 'amax', 'amergesortedby', 'amin', 'amultifilter', 'amultifilterfalse', 'amultimapif', 'amultinomial', 'amultistarfilter', 'amultistarfilterfalse', 'ancycles', 'anth', 'anthcombination', 'anthorlast', 'aonlinesorter', 'apadnone', 'apairwise', 'apartition', 'apermutations', 'apolynomialderivative', 'apolynomialeval', 'apolynomialfromroots', 'apowers', 'apowerset', 'apowersetofsets', 'apowersoftwo', 'aprepend', 'aprod', 'aproduct', 'aquantify', 'arandom_combination_with_replacement', 'arandomcombination', 'arandomderangement', 'arandompermutation', 'arandomproduct', 'arange', 'arepeat', 'arepeatfunc', 'areshape', 'areversed', 'aroundrobin', 'aroundrobin2', 'arunlengthdecode', 'arunlengthencode', 'arunningmean', 'arunningmedian', 'asampleweighted', 'asattolo', 'asendstream', 'aserialize', 'asideeffect', 'asieve', 'asliced', 'asorted', 'asplitat', 'aspy', 'asquaresum', 'astarfilter', 'astarfilterfalse', 'astarmap', 'asubslices', 'asubstrindices', 'asubstrings', 'asum', 'asumprod', 'atabulate', 'atail', 'atakewhile', 'atakewhile_inclusive', 'atakewhilenot', 'atakewhilenot_inclusive', 'atranspose', 'atriplewise', 'aunique', 'aunique_everseen', 'aunique_justseen', 'auniquetoeach', 'aunzip', 'azip', 'aziplongest', 'basic_collect', 'batch', 'batch2', 'batch_process', 'buffer', 'fmap', 'fmap_parallel', 'fmap_sequential', 'iter_future', 'map_on_map', 'mat_vec_mul', 'merge', 'tee', 'to_list', 'to_tuple', 'vecs_eq', 'window', 'with_aiter'
async def fmap[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs) -> list[T]: '''Return a list of the results of calling each async function in the first argument (an (async) iterable of functions), with the provided arguments.'''
def fmap_sequential[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs) -> AsyncGenerator[T]: '''Like :func:`fmap`, but only call a function after the last completes and the result is gotten.'''
def fmap_parallel[T, **P](fs: SupportsIteration[Callable[P, Awaitable[T]]], /, *a: P.args, **k: P.kwargs) -> AsyncGenerator[T]: '''Like :func:`fmap_sequential`, but starts background tasks for each call.'''
@overload
def map_on_map[T, R, V](outer: Callable[[R], V], inner: Callable[[T], SupportsIteration[R]], it: SupportsIteration[T], *, inner_await: Literal[False]=..., outer_await: Literal[False]=...) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], Awaitable[V]], inner: Callable[[T], SupportsIteration[R]], it: SupportsIteration[T], *, inner_await: Literal[False]=..., outer_await: Literal[True]) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], V], inner: Callable[[T], Awaitable[SupportsIteration[R]]], it: SupportsIteration[T], *, inner_await: Literal[True], outer_await: Literal[False]=...) -> AsyncGenerator[tuple[V, ...], None]: ...
@overload
def map_on_map[T, R, V](outer: Callable[[R], Awaitable[V]], inner: Callable[[T], Awaitable[SupportsIteration[R]]], it: SupportsIteration[T], *, inner_await: Literal[True], outer_await: Literal[True]) -> AsyncGenerator[tuple[V, ...], None]: '''Apply a transformation on an (async) iterable on top of another.'''
def tee[T](it: SupportsIteration[T], n: int=..., *, maxqsize: int=..., put_exc: bool=..., loop: AbstractEventLoop|None=...) -> tuple[AsyncGenerator[T], ...]:
    '''Create concurrent async iterators over a single (async) iterable.
    Unlike :func:`itertools.tee`, from which this obviously takes inspiration, the return values are plain async generators (not of a specialized class) and the flattening step is not applied.
    Generally, if one iterator is expected to complete much sooner than others, it is not advisable to use this function, which uses more space in that case.'''
@overload
async def aunzip[T](ait: SupportsIteration[tuple[T]], put_batch: int=...) -> tuple[AUnzipConsumer[T]]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T]]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T]]: ...
@overload
async def aunzip[T, S](ait: SupportsIteration[tuple[T, S]], put_batch: int=...) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S]]: ...
@overload
async def aunzip[T, S, R](ait: SupportsIteration[tuple[T|R, S|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S]]: ...
@overload
async def aunzip[T, S, R](ait: SupportsIteration[tuple[T|R, S|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S]]: ...
@overload
async def aunzip[T, S, V](ait: SupportsIteration[tuple[T, S, V]], put_batch: int=...) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V]]: ...
@overload
async def aunzip[T, S, V, R](ait: SupportsIteration[tuple[T|R, S|R, V|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V]]: ...
@overload
async def aunzip[T, S, V, R](ait: SupportsIteration[tuple[T|R, S|R, V|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V]]: ...
@overload
async def aunzip[T, S, V, U](ait: SupportsIteration[tuple[T, S, V, U]], put_batch: int=...) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V], AUnzipConsumer[U]]: ...
@overload
async def aunzip[T, S, V, U, R](ait: SupportsIteration[tuple[T|R, S|R, V|R, U|R]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V], AUnzipConsumer[U]]: ...
@overload
async def aunzip[T, S, V, U, R](ait: SupportsIteration[tuple[T|R, S|R, V|R, U|R]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], AUnzipConsumer[S], AUnzipConsumer[V], AUnzipConsumer[U]]: ...
@overload
async def aunzip[T](ait: SupportsIteration[tuple[T, ...]], put_batch: int=...) -> tuple[AUnzipConsumer[T], ...]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R, ...]], put_batch: int, fillvalue: R) -> tuple[AUnzipConsumer[T], ...]: ...
@overload
async def aunzip[T, R](ait: SupportsIteration[tuple[T|R, ...]], *, fillvalue: R) -> tuple[AUnzipConsumer[T], ...]: ...
@overload
async def aunzip(ait: SupportsIteration[tuple[Any, ...]], put_batch: int=..., fillvalue: Any=...) -> tuple[AUnzipConsumer[Any], ...]:
    '''Undo the effect of :class:`zip`, :class:`itertools.zip_longest`, :func:`aziplongest` or :func:`azip`.
    This function operates lazily, consuming items from the async iterable only when needed, in batches of the specified size (default :const:`context.AUNZIP_DEFAULT_PUT_BATCH`),
    caching other items. This function may thus require significant auxiliary space.'''
def merge[T](*I: SupportsIteration[T], reverse: bool=...) -> AsyncGenerator[T]: '''Merge items from the (async) iterables into a single async generator, in the order as they come (or reverse order if `reverse` is `True`).'''
def aflatten[T](it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[T]: '''Flatten one level of nesting using :class:`~iterclasses.achain` and return an async iterator over it.'''
def batch[T](it: SupportsIteration[T], n: int, *, item_timeout: float|None=..., strict: bool=...) -> AsyncGenerator[list[T]]: '''More flexible but slightly slower implementation of :func:`batch2`, supporting timeouts waiting for each item, that raises :exc:`ValueError` instead of :exc:`~exceptions.ItemsExhausted` in the case of the length of the iterable being indivisible by the batch size.'''
@overload
def batch2[T](it: SupportsIteration[T], n: int, strict: Literal[True]) -> AsyncGenerator[list[T]]: ...
@overload
def batch2[T](it: SupportsIteration[T], n: int|None, strict: Literal[False]=...) -> AsyncGenerator[list[T]]: '''Batch an (async) iterable into an async generator of lists. If `strict=True` is specified, raise :exc:`~exceptions.ItemsExhausted` on the last batch if it is discovered then that the iterable does not have enough items for a complete batch.'''
@overload
def asideeffect[T](f: Callable[[list[T]], object], it: SupportsIteration[T], /, *, size: int, before: Callable[[], object]|None=..., after: Callable[[], object]|None=...) -> AsyncGenerator[T]: ...
@overload
def asideeffect[T](f: Callable[[T], object], it: SupportsIteration[T], /, *, size: None=..., before: Callable[[], object]|None=..., after: Callable[[], object]|None=...) -> AsyncGenerator[T]:
    '''Apply a side effect function `f` to each item in an (async) iterable `it` and yield the items unchanged in an async generator.
    If `size` is specified, the side effect function is applied to batches of that size instead of individual items, but the items are still yielded separately.
    The `before` and `after` functions are called before and after the iteration, respectively.'''
def asliced[T: SupportsSlicing[Any]](seq: T, n: int, strict: bool=...) -> AsyncGenerator[T]:
    '''Slice a slicable object `seq` (so named because these are usually sequences) and yield slices of the size `n`, which should be of the same type as `seq`, from the start to the end.
    If `strict` is `True`, raise :exc:`ValueError` if the length of any slice is less than `n` (should only happen for the last slice unless the :meth:`__getitem__` method is misimplemented).'''
def buffer[T](it: SupportsIteration[T], maxsize: int=..., timeout: float|None=..., cooldown: float=..., *, loop: AbstractEventLoop|None=...) -> AsyncGenerator[T]: ...
def asplitat[T](it: SupportsIteration[T], pred: Callable[[T], bool], maxsplit: int=..., keep_sep: bool=...) -> AsyncGenerator[list[T]]: '''Split an async iterator at each item satisfying `pred`, with `keep_sep` dictating '''
def batch_process[T, R](items: SupportsIteration[T], size: int, processor: Callable[[list[T]], Awaitable[R]]) -> AsyncGenerator[R]: '''Apply `processor` to each batch of size `size` in `items` and yield the results awaited.'''
def window[T](it: SupportsIteration[T], size: int, step: int=...) -> AsyncGenerator[tuple[T, ...], tuple[int, int]|None]: '''Window an async iterable into an async generator of tuples of the specified size and step. You can send in a tuple `(size, step)` to change the behaviour of the iterator.'''
async def aall(it: SupportsIteration[Any]) -> bool: '''Async version of :func:`all`.'''
async def aany(it: SupportsIteration[Any]) -> bool: '''Async version of :func:`any`.'''
@overload
async def amax[C: SupportsRichComparison](it: SupportsIteration[C], *, default: C=...) -> C: ...
@overload
async def amax[C: SupportsRichComparison](arg1: C, arg2: C, /, *args: C, default: C=...) -> C: ...
@overload
async def amax[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], default: T=...) -> T: ...
@overload
async def amax[T](arg1: T, arg2: T, /, *args: T, key: Callable[[T], SupportsRichComparison], default: T=...) -> T: '''Async version of :func:`max`.'''
@overload
async def amin[C: SupportsRichComparison](it: SupportsIteration[C], *, default: C=...) -> C: ...
@overload
async def amin[C: SupportsRichComparison](arg1: C, arg2: C, /, *args: C, default: C=...) -> C: ...
@overload
async def amin[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], default: T=...) -> T: ...
@overload
async def amin[T](arg1: T, arg2: T, /, *args: T, key: Callable[[T], SupportsRichComparison], default: T=...) -> T: '''Async version of :func:`min`.'''
@overload
def azip[T](i1: SupportsIteration[T], /) -> AsyncGenerator[tuple[T]]: ...
@overload
def azip[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def azip[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def azip[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def azip[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def azip[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def azip[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def azip[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def azip[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: Literal[True]) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def azip[T](*I: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...], None]: '''Async version of :class:`zip` that is not a class.'''
@overload
def amap[T, R](f: Callable[[T], Awaitable[R]], it: SupportsIteration[T], /, *, await_: Literal[True], strict: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, R](f: Callable[[T], R], it: SupportsIteration[T], /, *, await_: Literal[False]=..., strict: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, R](f: Callable[[T, S], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, R](f: Callable[[T, S], R], i1: SupportsIteration[T], i2: SupportsIteration[S], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, R](f: Callable[[T, S, V], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, R](f: Callable[[T, S, V], R], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, U, R](f: Callable[[T, S, V, U], Awaitable[R]], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, S, V, U, R](f: Callable[[T, S, V, U], R], i1: SupportsIteration[T], i2: SupportsIteration[S], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, R](f: Callable[[*tuple[T, ...]], Awaitable[R]], /, *its: SupportsIteration[T], await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[T, R](f: Callable[[*tuple[T, ...]], R], /, *its: SupportsIteration[T], await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[R](f: Callable[..., Awaitable[R]], /, *its: SupportsIteration[Any], await_: Literal[True], strict: bool=...) -> AsyncGenerator[R]: ...
@overload
def amap[R](f: Callable[..., R], /, *its: SupportsIteration[Any], await_: Literal[False]=..., strict: bool=...) -> AsyncGenerator[R]: '''Async version of :class:`map` that is not a class, with `await_` dictating whether the return value of the function is to be awaited.'''
def afilter[T](f: Callable[[T], object]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: '''Async version of :class:`filter` that is not a class.'''
@overload
def amapif[T, R](f: Callable[[T], R], pred: Callable[[T], object]|None, it: SupportsIteration[T], /, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amapif[T, R](f: Callable[[T], Awaitable[R]], pred: Callable[[T], object]|None, it: SupportsIteration[T], /, await_: Literal[True]) -> AsyncGenerator[R]: '''Essentially the restriction of :func:`amultimapif` to one (async) iterable, which allows for more flexibility.'''
@overload
def amultimapif[T, R](f: Callable[[T], R], pred: Callable[[tuple[T]], bool], it: SupportsIteration[T], /, *, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, R](f: Callable[[T], Awaitable[R]], pred: Callable[[tuple[T]], bool], it: SupportsIteration[T], /, *, await_: Literal[True]) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, V, R](f: Callable[[T, V], R], pred: Callable[[tuple[T, V]], bool], i1: SupportsIteration[T], i2: SupportsIteration[V], /, *, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, V, R](f: Callable[[T, V], Awaitable[R]], pred: Callable[[tuple[T, V]], bool], i1: SupportsIteration[T], i2: SupportsIteration[V], /, *, await_: Literal[True]) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, V, S, R](f: Callable[[T, V, S], R], pred: Callable[[tuple[T, V, S]], bool], i1: SupportsIteration[T], i2: SupportsIteration[V], i3: SupportsIteration[S], /, *, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, V, S, R](f: Callable[[T, V, S], Awaitable[R]], pred: Callable[[tuple[T, V, S]], bool], i1: SupportsIteration[T], i2: SupportsIteration[V], i3: SupportsIteration[S], /, *, await_: Literal[True]) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, V, S, U, R](f: Callable[[T, V, S, U], R], pred: Callable[[tuple[T, V, S, U]], bool], i1: SupportsIteration[T], i2: SupportsIteration[V], i3: SupportsIteration[S], i4: SupportsIteration[U], /, *, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amultimapif[T, V, S, U, R](f: Callable[[T, V, S, U], Awaitable[R]], pred: Callable[[tuple[T, V, S, U]], bool], i1: SupportsIteration[T], i2: SupportsIteration[V], i3: SupportsIteration[S], i4: SupportsIteration[U], /, *, await_: Literal[True]) -> AsyncGenerator[R]: ...
@overload
def amultimapif[*Ts, R](f: Callable[[*Ts], R], pred: Callable[[tuple[*Ts]], bool], /, *its: SupportsIteration[Any], await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def amultimapif[*Ts, R](f: Callable[[*Ts], Awaitable[R]], pred: Callable[[tuple[*Ts]], bool], /, *its: SupportsIteration[Any], await_: Literal[True]) -> AsyncGenerator[R]: '''Composition of :func:`astarmap`, :func:`afilter` and :func:`azip`.'''
@overload
def arange(stop: int, /) -> AsyncGenerator[int]: ...
@overload
def arange(start: int, stop: int, /) -> AsyncGenerator[int]: ...
@overload
def arange(start: int, stop: int, step: int, /) -> AsyncGenerator[int]: '''Async version of :class:`range` that is not a class.'''
@overload
def acount(start: int=..., step: int=...) -> AsyncGenerator[int]: ...
@overload
def acount(start: float, step: int=...) -> AsyncGenerator[float]: ...
@overload
def acount(start: float, step: float) -> AsyncGenerator[float]: ...
@overload
def acount(*, step: float) -> AsyncGenerator[float]: '''Async version of :class:`itertools.count` that is not a class.'''
def acycle[T](it: SupportsIteration[T]) -> AsyncGenerator[T]: '''Async version of :class:`itertools.cycle` that is not a class.'''
def arepeat[T](elem: T, n: int=...) -> AsyncGenerator[T]: '''Async version of :class:`itertools.repeat` that is not a class.'''
def aaccumulate[T](it: SupportsIteration[T], func: Callable[[T, T], T]=..., *, initial: T|None=...) -> AsyncGenerator[T]: '''Async version of :class:`itertools.accumulate` that is not a class.'''
def acompress[T](data: SupportsIteration[T], selectors: SupportsIteration[Any]) -> AsyncGenerator[T]: '''Async version of :class:`itertools.compress` that is not a class.'''
def adropwhile[T](pred: Callable[[T], bool], it: SupportsIteration[T]) -> AsyncGenerator[T]: '''Async version of :class:`itertools.dropwhile` that is not a class.'''
def afilterfalse[T](f: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: '''Async version of :class:`itertools.filterfalse` that is not a class.'''
async def asattolo[T](it: SupportsIteration[T], /) -> list[T]: ...
@overload
def agroupby[T](it: SupportsIteration[T], key: Callable[[T], T]=...) -> AsyncGenerator[tuple[T, AsyncGenerator[T]]]: ...
@overload
def agroupby[T, R](it: SupportsIteration[T], key: Callable[[T], R]) -> AsyncGenerator[tuple[R, AsyncGenerator[T]]]: '''Async version of :class:`itertools.groupby` that is not a class.'''
@overload
def aislice[T](it: SupportsIteration[T], stop: SupportsIndex|None=..., /) -> AsyncGenerator[T]: ...
@overload
def aislice[T](it: SupportsIteration[T], start: SupportsIndex|None, stop: SupportsIndex|None, step: SupportsIndex|None=..., /) -> AsyncGenerator[T]: '''Async version of :class:`itertools.islice` that is not a class.'''
def aiterindex[T](it: SupportsIteration[T], value: T, start: int=..., stop: int|None=...) -> AsyncGenerator[int]: '''Yield the indices at which `value` occurs in `it` within `start` and `stop`.'''
def asieve(n: int) -> AsyncGenerator[int]: '''Implementation of the Sieve of Eratosthenes, yielding prime numbers strictly smaller than `n` in order in an async generator.'''
def apairwise[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, T], None]: '''Async version of :func:`itertools.pairwise` that is not a class.'''
def atriplewise[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, T, T], None]: '''Yield overlapping triples of items from an (async) iterable.'''
@overload
def aproduct[T](i1: SupportsIteration[T], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T]]: ...
@overload
def aproduct[T](i1: SupportsIteration[T], /, *, repeat: int) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def aproduct[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def aproduct[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, repeat: int) -> AsyncGenerator[tuple[T|R, ...], None]: ...
@overload
def aproduct[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def aproduct[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V, ...], None]: ...
@overload
def aproduct[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def aproduct[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V|U, ...], None]: ...
@overload
def aproduct[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, repeat: Literal[1]=...) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def aproduct[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, repeat: int) -> AsyncGenerator[tuple[T|R|V|U|S, ...], None]: ...
@overload
def aproduct(i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], repeat: int=...) -> AsyncGenerator[tuple[Any, ...], None]: ...
@overload
def aproduct[T](*its: SupportsIteration[T], repeat: int=...) -> AsyncGenerator[tuple[T, ...], None]: '''Async version of :class:`itertools.product` that is not a class.'''
@overload
def astarmap[*Ts, R](f: Callable[[*Ts], R], it: SupportsIteration[tuple[*Ts]], /, await_: Literal[False]=...) -> AsyncGenerator[R]: ...
@overload
def astarmap[*Ts, R](f: Callable[[*Ts], Awaitable[R]], it: SupportsIteration[tuple[*Ts]], /, await_: Literal[True]) -> AsyncGenerator[R]: '''Async version of :class:`itertools.starmap` that is not a class. `await_` specifies whether to await the return value of the transformation function.'''
def atakewhile[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: '''Async version of :class:`itertools.takewhile` that is not a class.'''
def atakewhilenot[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def atakewhile_inclusive[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def atakewhilenot_inclusive[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
async def asquaresum[X: (int, float, complex)](it: SupportsIteration[X]) -> X: '''Return the sum of squares of items in an (async) iterable of numbers as a number of the same type.'''
@overload
def aziplongest[T](i1: SupportsIteration[T], /) -> AsyncGenerator[tuple[T]]: ...
@overload
def aziplongest[T, R](i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R], None]: ...
@overload
def aziplongest[T, R, V](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V], None]: ...
@overload
def aziplongest[T, R, V, U](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V, U], None]: ...
@overload
def aziplongest[T, R, V, U, S](i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, fillvalue: Any=...) -> AsyncGenerator[tuple[T, R, V, U, S], None]: ...
@overload
def aziplongest[T](*its: SupportsIteration[T], fillvalue: T=...) -> AsyncGenerator[tuple[T, ...], None]: '''Async version of :class:`itertools.zip_longest` that is not a class.'''
async def asumprod[X: (int, float, complex)](p: SupportsIteration[X], q: SupportsIteration[X], /) -> X: '''Return the sum of products of items in two iterables of numbers as a number of the same type. Not as precise as :func:`math.fsumprod` for floating-point numbers, but supports async iterables.'''
def aconvolve[X: (int, float, complex)](signal: SupportsIteration[X], kernel: SupportsIteration[X]) -> AsyncGenerator[X]: '''Polynomial multiplication with coefficients from the two iterables. The first iterable is advanced on demand, meaning it may be infinite, but the second iterable is exhausted immediately, storing all its items in memory.'''
@overload
def atabulate[T](f: Callable[[int], T], start: int=..., step: int=..., /, *, await_: Literal[False]=...) -> AsyncGenerator[T]: ...
@overload
def atabulate[T](f: Callable[[int], Awaitable[T]], start: int=..., step: int=..., /, *, await_: Literal[True]) -> AsyncGenerator[T]: '''Composition of :func:`amap` and :func:`acount`.'''
async def asum[X: (int, float, complex)](it: SupportsIteration[X], start: X=...) -> X: '''Return the sum of the items in the (async) iterable, preceded by `start` if passed.'''
async def aprod[X: (int, float, complex)](it: SupportsIteration[X], start: X=...) -> X: '''Return the product of the items in the (async) iterable, preceded by `start` if passed.'''
async def amatprod[M: SupportsMatMul](it: SupportsIteration[M], start: M) -> M: '''Return the product of the matrices in the (async) iterable, preceded by `start` if passed.'''
def acountdown(n: int, step: int=..., *, include_zero: bool=...) -> AsyncGenerator[int]: ...
def atail[T](n: int, it: SupportsIteration[T], /) -> AsyncGenerator[T]: ...
def abfs[T](start: T, neighbours: Callable[[T], SupportsIteration[T]], *, include_start: bool=...) -> AsyncGenerator[T]: ...
def adfs[T](start: T, neighbours: Callable[[T], SupportsIteration[T]], *, include_start: bool=...) -> AsyncGenerator[T]: ...
async def abrent[T](next_node: Callable[[T], SupportsIteration[T]], start: T, /) -> tuple[T, int, int]: ...
async def ahammingdist[T](a: SupportsIteration[T], b: SupportsIteration[T], /, cmpeq: Callable[[T, T], bool]=...) -> int: ...
async def amultinomial(*coeff: int) -> int: ...
@overload
def amergesortedby[C: SupportsRichComparison](its: SupportsIteration[SupportsIteration[C]], *, key: Callable[[C], C]=..., await_: Literal[False]=..., reverse: bool=...) -> AsyncGenerator[C]: ...
@overload
def amergesortedby[T](its: SupportsIteration[SupportsIteration[T]], *, key: Callable[[T], SupportsRichComparison], await_: Literal[False]=..., reverse: bool=...) -> AsyncGenerator[T]: ...
@overload
def amergesortedby[T](its: SupportsIteration[SupportsIteration[T]], *, key: Callable[[T], Awaitable[SupportsRichComparison]], await_: Literal[True], reverse: bool=...) -> AsyncGenerator[T]: ...
@overload
def amultifilter[T](pred: Callable[[tuple[T]], object], it: SupportsIteration[T], /, *, strict: bool=...) -> AsyncGenerator[tuple[T]]: ...
@overload
def amultifilter[T, R](pred: Callable[[tuple[T, R]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R]]: ...
@overload
def amultifilter[T, R, V](pred: Callable[[tuple[T, R, V]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V]]: ...
@overload
def amultifilter[T, R, V, U](pred: Callable[[tuple[T, R, V, U]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U]]: ...
@overload
def amultifilter[T, R, V, U, S](pred: Callable[[tuple[T, R, V, U, S]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U, S]]: ...
@overload
def amultifilter[T](pred: Callable[[tuple[T, ...]], object], /, *its: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...]]: ...
@overload
def amultifilter(pred: Callable[[tuple[Any, ...]], object], i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], strict: bool=...) -> AsyncGenerator[tuple[Any, ...]]: '''Composition of :func:`afilter` and :func:`azip`.'''
@overload
def amultifilterfalse[T](pred: Callable[[tuple[T]], object], it: SupportsIteration[T], /, *, strict: bool=...) -> AsyncGenerator[tuple[T]]: ...
@overload
def amultifilterfalse[T, R](pred: Callable[[tuple[T, R]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R]]: ...
@overload
def amultifilterfalse[T, R, V](pred: Callable[[tuple[T, R, V]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V]]: ...
@overload
def amultifilterfalse[T, R, V, U](pred: Callable[[tuple[T, R, V, U]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U]]: ...
@overload
def amultifilterfalse[T, R, V, U, S](pred: Callable[[tuple[T, R, V, U, S]], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U, S]]: ...
@overload
def amultifilterfalse[T](pred: Callable[[tuple[T, ...]], object], /, *its: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...]]: ...
@overload
def amultifilterfalse(pred: Callable[[tuple[Any, ...]], object], i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], strict: bool=...) -> AsyncGenerator[tuple[Any, ...]]: '''Composition of :func:`afilter` and :func:`azip`.'''
@overload
def amultistarfilter[T](pred: Callable[[T], object], it: SupportsIteration[T], /, *, strict: bool=...) -> AsyncGenerator[tuple[T]]: ...
@overload
def amultistarfilter[T, R](pred: Callable[[T, R], object], i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R]]: ...
@overload
def amultistarfilter[T, R, V](pred: Callable[[T, R, V], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V]]: ...
@overload
def amultistarfilter[T, R, V, U](pred: Callable[[T, R, V, U], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U]]: ...
@overload
def amultistarfilter[T, R, V, U, S](pred: Callable[[T, R, V, U, S], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U, S]]: ...
@overload
def amultistarfilter[T](pred: Callable[[*tuple[T, ...]], object], /, *its: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...]]: ...
@overload
def amultistarfilter(pred: Callable[[*tuple[Any, ...]], object], i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], strict: bool=...) -> AsyncGenerator[tuple[Any, ...]]: '''Composition of :func:`afilter` and :func:`azip`.'''
@overload
def amultistarfilterfalse[T](pred: Callable[[T], object], it: SupportsIteration[T], /, *, strict: bool=...) -> AsyncGenerator[tuple[T]]: ...
@overload
def amultistarfilterfalse[T, R](pred: Callable[[T, R], object], i1: SupportsIteration[T], i2: SupportsIteration[R], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R]]: ...
@overload
def amultistarfilterfalse[T, R, V](pred: Callable[[T, R, V], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V]]: ...
@overload
def amultistarfilterfalse[T, R, V, U](pred: Callable[[T, R, V, U], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U]]: ...
@overload
def amultistarfilterfalse[T, R, V, U, S](pred: Callable[[T, R, V, U, S], object], i1: SupportsIteration[T], i2: SupportsIteration[R], i3: SupportsIteration[V], i4: SupportsIteration[U], i5: SupportsIteration[S], /, *, strict: bool=...) -> AsyncGenerator[tuple[T, R, V, U, S]]: ...
@overload
def amultistarfilterfalse[T](pred: Callable[[*tuple[T, ...]], object], /, *its: SupportsIteration[T], strict: bool=...) -> AsyncGenerator[tuple[T, ...]]: ...
@overload
def amultistarfilterfalse(pred: Callable[[*tuple[Any, ...]], object], i1: SupportsIteration[Any], i2: SupportsIteration[Any], i3: SupportsIteration[Any], i4: SupportsIteration[Any], i5: SupportsIteration[Any], /, *its: SupportsIteration[Any], strict: bool=...) -> AsyncGenerator[tuple[Any, ...]]: '''Composition of :func:`afilter` and :func:`azip`.'''
async def asampleweighted[T](it: SupportsIteration[tuple[T, float]], k: int, *, rrange: Callable[[int], int]=..., rand: Callable[[], float]=...) -> list[T]: ...
def astarfilter[T](pred: Callable[[*tuple[T, ...]], object], it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[tuple[T, ...]]: ...
def astarfilterfalse[T](pred: Callable[[*tuple[T, ...]], object], it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[tuple[T, ...]]: ...
async def to_tuple[T](it: SupportsIteration[T], /) -> tuple[T, ...]: ...
async def aconsume[T](it: SupportsIteration[T], n: int|None=...) -> T|None: ...
async def anth[T](it: SupportsIteration[T], n: int, default: T=...) -> T: ...
async def aallequal[T](it: SupportsIteration[T], key: Callable[[T], Any]=..., strict: bool=...) -> bool: ...
def acombinations[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[tuple[T, ...], None]: ...
def acombinations_with_replacement[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[tuple[T, ...], None]: ...
def apermutations[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[tuple[T, ...], None]: ...
def apowerset[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
async def aquantify[T](it: SupportsIteration[T], pred: Callable[[T], bool]=...) -> int: ...
def apadnone[T](it: SupportsIteration[T]) -> AsyncGenerator[T|None]: ...
def agrouper[T](it: SupportsIteration[T], n: int, fillvalue: T=...) -> AsyncGenerator[tuple[T|None, ...], None]: ...
def aroundrobin[T](*its: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def aroundrobin2[T](*its: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def aunique_everseen[T](it: SupportsIteration[T], key: Callable[[T], Any]=...) -> AsyncGenerator[T]: ...
def aunique_justseen[T](it: SupportsIteration[T], key: Callable[[T], Any]=...) -> AsyncGenerator[T]: ...
def aunique[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison]|None=..., reverse: bool=...) -> AsyncGenerator[T]: ...
def ancycles[T](it: SupportsIteration[T], n: int) -> AsyncGenerator[T]: ...
def apartition[T](pred: Callable[[T], bool]|None, it: SupportsIteration[T]) -> tuple[AsyncGenerator[T], AsyncGenerator[T]]: ...
def aiterexcept[T](f: Callable[[], Awaitable[T]], exc: Exceptable, first: Callable[[], Awaitable[T]]=...) -> AsyncGenerator[T]: ...
async def ailen(it: SupportsIteration[Any]) -> int: ...
def aiterate[T](f: Callable[[T], Awaitable[T]], start: T) -> AsyncGenerator[T]: ...
def with_aiter[T](actxmgr: AsyncContextManager[SupportsIteration[T]]) -> AsyncGenerator[T]: ...
@overload
def asorted[C: SupportsRichComparison](it: SupportsIteration[C], *, reverse: bool=...) -> list[C]: ...
@overload
def asorted[T](it: SupportsIteration[T], *, key: Callable[[T], SupportsRichComparison], reverse: bool=...) -> list[T]: ...
def acanonical[T](it: SupportsIteration[T]) -> list[T]: ...
def adistinctpermutations[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[tuple[T, ...], None]: ...
def auniquetoeach[H: Hashable](*its: SupportsIteration[H]) -> AsyncGenerator[AsyncGenerator[H]]: ...
def aderangements[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[T]: ...
def aintersperse[T](e: T, it: SupportsIteration[T], n: int=...) -> AsyncGenerator[T]: ...
def ainterleave_stopearly[T](*it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def ainterleave[T](*it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def aspy[T](it: SupportsIteration[T], n: int=...) -> tuple[AsyncGenerator[T], AsyncGenerator[T]]: ...
def ainterleaveevenly[T](its: SupportsIteration[SupportsIteration[T]], lengths: SupportsIteration[int]|None=...) -> AsyncGenerator[T]: ...
def ainterleaverandomly[T](its: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[T]: ...
def acollapse(it: SupportsIteration[Any], base_typ: tuple[type, ...]|type=..., levels: int|None=...) -> AsyncGenerator[Any]: ...
async def afirsttrue[T](it: SupportsIteration[T], default: T=..., pred: Callable[[T], Any]=...) -> T: ...
def aprepend[T](val: T, it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
def arandomproduct[T](*a: SupportsIteration[T], n: int=...) -> AsyncGenerator[T]: ...
def arandomcombination[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[T]: ...
def arandom_combination_with_replacement[T](it: SupportsIteration[T], r: int) -> AsyncGenerator[T]: ...
def arandompermutation[T](it: SupportsIteration[T], r: int|None=...) -> AsyncGenerator[T]: ...
async def afirst[T](it: SupportsIteration[T], default: T=...) -> T: ...
async def alast[T](it: SupportsIteration[T], default: T=...) -> T: ...
async def anthorlast[T](it: SupportsIteration[T], n: int, default: T=...) -> T: ...
def abeforeandafter[T](pred: Callable[[T], bool], it: SupportsIteration[T]) -> tuple[AsyncGenerator[T], AsyncGenerator[T]]: ...
def anthcombination[T](it: SupportsIteration[T], r: int, idx: int) -> AsyncGenerator[T]: ...
def asubslices[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
def arepeatfunc[T, *Ts](f: Callable[[*Ts], Awaitable[T]], times: int|None=..., *a: *Ts) -> AsyncGenerator[T]: ...
def apolynomialfromroots[X: (int, float, complex)](roots: SupportsIteration[X]) -> AsyncGenerator[X]: ...
def atranspose[T](it: SupportsIteration[SupportsIteration[T]]) -> AsyncGenerator[tuple[T, ...], None]: ...
def aflattentensor(tensor: SupportsIteration[Any], base_typ: tuple[type, ...]|type=...) -> AsyncGenerator[Any]: ...
def apolynomialderivative[X: (int, float, complex)](coeff: SupportsIteration[X]) -> AsyncGenerator[X]: ...
async def apolynomialeval[X: (int, float, complex)](coeff: SupportsIteration[X], x: X) -> X: ...
@overload
def areshape[T](mat: SupportsIteration[SupportsIteration[T]], shape: int) -> AsyncGenerator[list[T]]: ...
@overload
def areshape(mat: SupportsIteration[Any], shape: SupportsIteration[int]) -> AsyncGenerator[list[Any]]: ...
def afactor(n: int) -> AsyncGenerator[int]: ...
@overload
def arunningmedian(it: SupportsIteration[int], *, maxlen: SupportsIndex|None=...) -> AsyncGenerator[int]: ...
@overload
def arunningmedian(it: SupportsIteration[float], *, maxlen: SupportsIndex|None=...) -> AsyncGenerator[float]: ...
async def arandomderangement[T](it: SupportsIteration[T]) -> tuple[T, ...]: ...
def amatmul[X: (int, float, complex)](M: SupportsIteration[SupportsIteration[X]], N: SupportsIteration[SupportsIteration[X]]) -> AsyncGenerator[tuple[X, ...], None]: '''Matrix multiplication of `M` and `N`. O(n^3) time, since this library does not specialize in these operations.'''
def mat_vec_mul(M: SupportsIteration[SupportsIteration[int]], V: SupportsIteration[int]) -> AsyncGenerator[int]: ...
async def vecs_eq[T](u: SupportsIteration[T], v: SupportsIteration[T], cmpeq: Callable[[T, T], bool]=..., *, strict: bool=...) -> bool: ...
async def afreivalds(A: SupportsIteration[SupportsIteration[int]], B: SupportsIteration[SupportsIteration[int]], C: SupportsIteration[SupportsIteration[int]], k: int=...) -> bool: '''The probabilistic Freivalds algorithm to determine if the matrix product of `A` and `B` equals `C`. O(kn^2) time, with a false positive rate of at most 2^(-k) and no false negatives.'''
async def basic_collect[T](it: SupportsIteration[T], n: int) -> list[T]: ...
def asubstrings[T](it: SupportsIteration[T]) -> AsyncGenerator[tuple[T, ...], None]: ...
@overload
def asubstrindices[S: (str, bytes, bytearray)](seq: S, reverse: bool=...) -> AsyncGenerator[tuple[S, int, int], None]: ...
@overload
def asubstrindices[T](seq: SupportsSlicing[T], reverse: bool=...) -> AsyncGenerator[tuple[Iterable[T], int, int], None]: '''Yield tuples of the form `(substr, start, end)`, where `substr` is a contiguous subsequence of `seq` starting at index `start` and ending at index `end-1` (such that its length is `end-start`).'''
def iter_future[T](it: SupportsIteration[T], summaryf: Callable[[SupportsIteration[T]], Awaitable[Any]]=...) -> Future[float]: ...
def agetitems_from_indices[T](it: SupportsIteration[T], indices: SupportsIteration[SupportsIndex], setatend: Future[float]|None=..., finish: bool=...) -> list[Future[T]]:
    '''Takes an (async) iterable and an (async) iterable of integers interpreted as indices, and immediately returns a list of futures whose eventual results represent
    the items of that iterable at the index, beginning consumption of the iterable in the background. Exceptions will be set in the futures that are not done if results
    are encountered during iteration or if the index is out of bounds. Supports negative indices. Do not set the result of any returned future; instead, if the result
    is no longer relevant, cancel the future. The consumption stops as soon as all the required results are pushed into the respective futures. Pass in a Future for the
    setatend parameter, which cancels the background consumption of the async iterable once it is done and cancels the undone futures.'''
def aintersend[T, R](i1: AsyncGenerator[T, R], i2: AsyncGenerator[R, T]) -> AsyncGenerator[tuple[T, R], None]: '''Feed `i1` and `i2` into each other and yield tuples of the form `(yielded_from_i1, yielded_from_i2)`.'''
def asendstream[T, R](i1: AsyncGenerator[T, R], i2: SupportsIteration[R]) -> AsyncGenerator[T]: '''Feed `i2` into `i1` and yield the results.'''
@overload
def acat[T](first: T) -> AsyncGenerator[T, T]: ...
@overload
def acat[T](first: None=...) -> AsyncGenerator[T|None, T|None]: '''An async generator that yields the sent value, starting with `first` (default `None`).'''
def aforever() -> AsyncGenerator[None]: '''An async generator that yields `None` forever.'''
async def aguessmax[T](it: SupportsIteration[T], estlen: int, *, key: Callable[[T], SupportsRichComparison]=..., default: T=..., finish_event: Event|None=...) -> T: ...
async def aguessmin[T](it: SupportsIteration[T], estlen: int, *, key: Callable[[T], SupportsRichComparison]=..., default: T=..., finish_event: Event|None=...) -> T: ...
def apowersoftwo(*, init: int=..., init_shift: int=...) -> AsyncGenerator[int]: '''Optimized version of :func:`apowers` using bit shift operations for powers of two. First shifts `init` left by `init_shift` bits.'''
def areversed[T](it: SupportsIteration[T]|Reversible[T], /) -> AsyncGenerator[T]: '''Reverse an (async) iterable, calling its :meth:`__reversed__` method if present, falling back to consuming all the items and yielding them in reverse order.'''
async def to_list[T](it: SupportsIteration[T], /) -> list[T]: '''Collect all items of an async iterable into a list. Faster than :func:`base.collect`.'''
async def aisprime(n: int) -> bool: '''Probabilistically test for primality of `n`. O(log^3 n), with false-positive rate below 2^(-128) for integers above 10^24.'''
def adft(xarr: SupportsIteration[complex], /) -> AsyncGenerator[complex]: '''The discrete Fourier transform. O(n^2), since this library does not specialize in these operations.'''
def aidft(Xarr: SupportsIteration[complex], /) -> AsyncGenerator[complex]: '''The inverse discrete Fourier transform; above remark applies.'''
def apowers[X: (int, float, complex)](base: X, start: X=...) -> AsyncGenerator[X]: '''Yield `start`, `start*base`, `start*base*base`, ...'''
def arunlengthencode[T](it: SupportsIteration[T], /) -> AsyncGenerator[tuple[T, int], None]: '''Compress a possibly repetitive (async) iterable into an async generator of pairs with run-length encoding.'''
def arunlengthdecode[T](it: SupportsIteration[tuple[T, int]], /) -> AsyncGenerator[T]: '''Inverse of the above.'''
@overload
async def aargmin[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison], default: int=...) -> int: ...
@overload
async def aargmin[C: SupportsRichComparison](it: SupportsIteration[C], *, default: int=...) -> int: '''Return the index of the first occurrence of the minimum element in the (async) iterable `it` according to `key`, or `default` if empty.'''
@overload
async def aargmax[T](it: SupportsIteration[T], key: Callable[[T], SupportsRichComparison], default: int=...) -> int: ...
@overload
async def aargmax[C: SupportsRichComparison](it: SupportsIteration[C], *, default: int=...) -> int: '''Return the index of the first occurrence of the maximum element in the (async) iterable `it` according to `key`, or `default` if empty.'''
def arunningmean[X: (int|float, complex)](it: SupportsIteration[X]) -> AsyncGenerator[X]: '''Repeatedly yield the mean of the items in the iterable so far, and advance the iterable.'''
@overload
def apowersetofsets[T: Hashable](it: SupportsIteration[T], *, frozen: Literal[True]=...) -> AsyncGenerator[frozenset[T]]: ...
@overload
def apowersetofsets[T: Hashable](it: SupportsIteration[T], *, frozen: Literal[False]) -> AsyncGenerator[set[T]]: '''Yield all the subsets of the items in the (async) iterable after consuming it at once, as :class:`frozenset`'s if `frozen` is `True` (the default) and :class:`set`'s otherwise.'''
def aserialize[T](it: SupportsIteration[T]) -> AsyncGenerator[T]: ...
@overload
def aonlinesorter[T](it: SupportsIteration[T]) -> AsyncGenerator[T, T|None]: ...
@overload
def aonlinesorter[T]() -> AsyncGenerator[T, T|None]: '''Sort items from an async iterable and those sent in on the fly in the async generator interface. Does not work well with items that are `None`.'''