from ._internal.protocols import AsyncLockLike
from .mixins import EventualLoopMixin, LockMixin, LoopContextMixin, AwaitableMixin, LockWithOwnerMixin
from asyncio.events import AbstractEventLoop
from asyncio.locks import Lock
from asyncio.tasks import Task
from _collections_abc import Callable, Awaitable, Coroutine
from typing import Literal, ClassVar, Any, final
__all__ = 'AdvancedRateLimit', 'PrioritySemaphore', 'KeyedCondition', 'RLock', 'PriorityLock', 'PriorityRLock'
class AdvancedRateLimit(EventualLoopMixin, LockMixin[None, Coroutine[Any, Any, None]]):
    def __init__(self, rate: float, capacity: float=..., fair: bool=...):
        '''`rate`: The initial rate at which tokens refill.
        `capacity`: The maximum rate, defaulting to the current rate.
        `fair`: Whether to maintain FIFO for waiters; default `True`.'''
    async def acquire(self, tokens: float=...) -> Literal[True]: ...
    async def release(self, tokens: float=...) -> None: ...
    async def set_rate(self, new: float) -> None: ...
    def locked(self) -> bool: ...
    def update_tokens(self) -> None: ...
    @property
    def rate(self) -> float: ...
    @property
    def tokens(self) -> float: ...
    @property
    def capacity(self) -> float: ...
class PrioritySemaphore(LockMixin):
    def __init__(self, value: int=...): ...
    async def acquire(self, priority: int=...) -> Literal[True]: ...
    def release(self, strict: bool=...) -> None: ...
    def locked(self) -> bool: ...
    def reset(self) -> None: ...
class KeyedCondition(LockMixin, LoopContextMixin, AwaitableMixin):
    def __init__(self, lock: Lock|LockMixin|None=...): ...
    async def acquire(self) -> Literal[True]: ...
    async def release(self) -> None: ...
    def locked(self) -> bool: ...
    async def wait(self, key: str|None=..., timeout: float|None=...) -> None: ...
    async def notify(self, n: int=..., key: str|None=..., strict: bool=...) -> None: ...
    async def notify_all(self, key: str|None=...) -> int: ...
class RLock(LockWithOwnerMixin):
    def __init__(self, lock: AsyncLockLike|None=...): ...
    async def acquire(self) -> Literal[True]: ...
    def _release(self) -> None: ...
    def locked(self) -> bool: ...
    @property
    def is_owner(self) -> bool: ...
class PriorityLock(EventualLoopMixin, LockWithOwnerMixin):
    async def acquire(self, priority: int=..., timeout: float|None=...) -> bool: ...
    def _release(self, raise_: bool=...) -> None: ...
    def locked(self) -> bool: ...
    @property
    def is_owner(self) -> bool: ...
class PriorityRLock(RLock):
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def owner(self) -> Task|None: ...
    async def acquire(self, priority: int=..., timeout: float|None=...) -> bool: ... # type: ignore[override]
class LocksmithBase:
    handlers: ClassVar[dict[type[AsyncLockLike], Callable[[AsyncLockLike], Any]]]
    def __init__(self, loop: AbstractEventLoop, ltyp: type[AsyncLockLike]=...): ...
    @property
    def currently_recognized(self) -> frozenset[AsyncLockLike]: ...
    @classmethod
    def register_handler[T: AsyncLockLike](cls, h: Callable[[T], Any], /, *, shadow: bool=...) -> Callable[[type[T]], type[T]]: ...
    async def recognize_lock(self, lock: AsyncLockLike, /) -> bool: ...
    @final
    async def force(self, lock: AsyncLockLike, /, info: str=..., *, purge_waiters: bool=...) -> bool: ...
    async def host[T](self, task: Awaitable[T], lock: AsyncLockLike, /, *, timeout1: float|None=..., timeout2: float|None=..., timeout3: float|None) -> T: ...
    async def _wait_on[T](self, task: Awaitable[T], lock: AsyncLockLike, /) -> T: ...
    async def get_info(self, lock: AsyncLockLike, /) -> Any: ...
    async def lock_busy(self, lock: AsyncLockLike, requester: LocksmithBase, /) -> None: ...
    async def purge_waiters(self, lock: AsyncLockLike, /) -> None: ...
    async def task_reraised_request(self, lock: AsyncLockLike, /) -> None: ...
    def wrap_task[T](self, task: Awaitable[T], /) -> Task[T]: ...
    def find_owner(self, lock: AsyncLockLike, /) -> Task|None: ...
    def throw_fallback(self, lock: AsyncLockLike, /) -> bool: ...
    def eager_fallback(self, lock: AsyncLockLike, /) -> bool: ...
    def release_returned_false(self, lock: AsyncLockLike) -> bool: ...
    def preliminary_check_lock(self, lock: Any, /) -> bool: ...
    def can_force_lock_held(self, lock: AsyncLockLike, /) -> bool: ...
    def patch_owner(self, task: Task, lock: AsyncLockLike, /) -> None: ...
    def answer_received(self, lock: AsyncLockLike, answer: Any, /) -> None: ...
    def raised_other(self, lock: AsyncLockLike, exc: BaseException, /) -> None: ...
    def task_raised_critical(self, lock: AsyncLockLike, exc: BaseException, /) -> None: ...