'''Locking primitives, more advanced than or supplementing the functionality of those in :mod:`asyncio`.
All classes strictly follow the asynchronous lock interface as defined by `asyncio.Lock` and made explicit in the `_internal.types.AsyncLockLike` protocol, besides
:class:`MultiCountDownLatch`, since it uses :class:`KeyedCondition` internally and it is not desired for :mod:`altlocks` to import :mod:`locks` as well.'''
from ._internal.types import AsyncLockLike
from .mixins import LoopBoundMixin, LockMixin, LockWithOwnerMixin, LoopContextMixin
from _collections_abc import Awaitable, Callable, Hashable, Mapping
from asyncio.events import AbstractEventLoop
from asyncio.locks import BoundedSemaphore, Lock
from asyncio.tasks import Task
from typing import Any, ClassVar, Literal, final
__all__ = 'AdvancedRateLimit', 'DynamicBoundedSemaphore', 'KeyedCondition', 'MultiCountDownLatch', 'PriorityLock', 'PriorityRLock', 'PrioritySemaphore', 'RLock'
class DynamicBoundedSemaphore(BoundedSemaphore):
    '''A subclass of :class:`asyncio.BoundedSemaphore` whose bound can be set by the user via the `bound` property.'''
    def __init__(self, value: int=...): '''`value`, the initial value of the semaphore, defaults to :const:`context.DYNAMIC_BOUNDED_SEMAPHORE_DEFAULT_VALUE`.'''
    @property
    def bound(self) -> int: ...
    @bound.setter
    def bound(self, value: int, /) -> None: ...
class AdvancedRateLimit(LoopBoundMixin, LockMixin[None]):
    '''A rate limiter that supports a mode in which waiters can cut the queue.'''
    def __init__(self, rate: float, capacity: float=..., fair: bool=...):
        '''`rate` (required): The initial rate at which tokens refill.
        `capacity`: The maximum rate, defaulting to the current rate.
        `fair`: Whether to maintain FIFO for waiters; default `True`.'''
    async def acquire(self, tokens: float=..., timeout: float|None=...) -> Literal[True]: '''Acquire the specified number of tokens from the rate limiter (default :const:`context.ADVANCED_RATE_LIMIT_DEFAULT_TOKENS`), waiting until the timeout expires and signalling :exc:`TimeoutError` if necessary.'''
    async def release(self, tokens: float=...) -> None: ...
    async def set_rate(self, new: float) -> None: ...
    def locked(self) -> bool: ...
    def update_tokens_lock_held(self) -> None: ...
    @property
    def rate(self) -> float: ...
    @property
    def tokens(self) -> float: ...
    @property
    def capacity(self) -> float: ...
class PrioritySemaphore(LoopBoundMixin, LockMixin[None]):
    '''A semaphore that allows waiters with a lower priority value to enter first.'''
    def __init__(self, value: int=...): '''`value`, the initial value as an integer, defaults to :const:`context.PRIORITY_SEMAPHORE_DEFAULT_VALUE`.'''
    async def acquire(self, priority: int=...) -> Literal[True]: ...
    def release(self, strict: bool=...) -> None: ...
    def locked(self) -> bool: ...
    def reset(self) -> None: ...
class KeyedCondition[T](LockMixin[KeyedCondition[T]], LoopContextMixin):
    def __init__(self, lock: Lock|LockMixin[Any]|None=...): ...
    async def acquire(self) -> Literal[True]: ...
    async def release(self) -> None: ...
    async def wait_all(self, timeout: float|None=...) -> None: ...
    def locked(self) -> bool: ...
    def assert_locked(self) -> None: ...
    async def wait(self, key: T, timeout: float|None=...) -> None: ...
    async def wait_for(self, key: T, pred: Callable[[], bool], per_wait_timeout: float|None=...) -> None: ...
    def notify(self, key: T, n: int=..., strict: bool=...) -> None: ...
    def notify_all(self, key: T|None=...) -> int: ...
class MultiCountDownLatch[T: Hashable]:
    '''A collection of count-down latches, each identified by a key, supporting waiting on individual latches or on all of them at once.'''
    def __init__(self, counts: Mapping[T, int]): '''Initialize the latch with the given mapping of keys to counts. No more keys can be added after this stage.'''
    async def count_down(self, key: T, strict: bool=...) -> None: '''Decrement the count of the latch with the given key by one. If it reaches zero, wake up all waiters. If `strict` is `True`, the key must exist, and a :exc:`KeyError` is raised otherwise.'''
    async def count_down_all(self) -> None: '''Decrement the count of each latch by one.'''
    async def wait(self, key: T, strict: bool=...) -> None: '''Wait for the latch with the given key to reach zero. If `strict` is `True`, the key must exist, and a :exc:`KeyError` is raised otherwise.'''
    async def wait_all(self, timeout: float|None=...) -> None: '''Wait for the count of all latches to reach zero.'''
    @property
    def broken(self) -> bool: '''If this returns `True`, it means that :meth:`wait_all` will return immediately.'''
class RLock(LockWithOwnerMixin[None]):
    '''An async reentrant lock that is somehow missing from :mod:`asyncio`.'''
    def __init__(self, lock: AsyncLockLike[Any]|None=...): ...
    async def acquire(self) -> Literal[True]: ...
    def _release(self) -> None: ...
    def locked(self) -> bool: ...
    @property
    def is_owner(self) -> bool: ...
class PriorityLock(LoopBoundMixin, LockWithOwnerMixin[None]):
    '''A lock allowing waiters with a lower priority value to enter first.'''
    async def acquire(self, priority: int=..., timeout: float|None=...) -> bool: ...
    def _release(self, raise_: bool=...) -> None: ...
    def locked(self) -> bool: ...
    @property
    def is_owner(self) -> bool: ...
class PriorityRLock(RLock):
    def __init__(self) -> None: ...
    @property
    def owner(self) -> Task[Any]|None: ...
    async def acquire(self, priority: int=..., timeout: float|None=...) -> bool: ... # type: ignore[override]
class LocksmithBase:
    handlers: ClassVar[dict[type[AsyncLockLike[Any]], Callable[[AsyncLockLike[Any]], Any]]]
    def __init__(self, loop: AbstractEventLoop, ltyp: type[AsyncLockLike[Any]]=...): ...
    @property
    def currently_recognized(self) -> frozenset[AsyncLockLike[Any]]: ...
    @classmethod
    def register_handler[T: AsyncLockLike[Any]](cls, h: Callable[[T], object], /, *, shadow: bool=...) -> Callable[[type[T]], type[T]]: ...
    async def recognize_lock(self, lock: AsyncLockLike[Any], /) -> bool: ...
    @final
    async def force(self, lock: AsyncLockLike[Any], /, info: str=..., *, purge_waiters: bool=...) -> bool: ...
    async def host[T](self, task: Awaitable[T], lock: AsyncLockLike[Any], /, *, timeout1: float|None=..., timeout2: float|None=..., timeout3: float|None=...) -> T: '''Run `task` with `lock` after forcing it. The default values of the timeouts are taken from :const:`context.LOCKSMITH_DEFAULT_TIMEOUTS`.'''
    async def _wait_on[T](self, task: Awaitable[T], lock: AsyncLockLike[Any], /) -> T: ...
    async def get_info(self, lock: AsyncLockLike[Any], /) -> Any: ...
    async def lock_busy(self, lock: AsyncLockLike[Any], requester: LocksmithBase, /) -> None: ...
    async def purge_waiters(self, lock: AsyncLockLike[Any], /) -> None: ...
    async def task_reraised_request(self, lock: AsyncLockLike[Any], /) -> None: ...
    def wrap_task[T](self, aw: Awaitable[T], /) -> Task[T]: ...
    def find_owner(self, lock: AsyncLockLike[Any], /) -> Task[Any]|None: ...
    def throw_fallback(self, lock: AsyncLockLike[Any], /) -> bool: ...
    def eager_fallback(self, lock: AsyncLockLike[Any], /) -> bool: ...
    def release_returned_false(self, lock: AsyncLockLike[Any], /) -> bool: ...
    def preliminary_check_lock(self, lock: AsyncLockLike[Any], /) -> bool: ...
    def can_force_lock_held(self, lock: AsyncLockLike[Any], /) -> bool: ...
    def patch_owner(self, task: Task[Any], lock: AsyncLockLike[Any], /) -> None: ...
    def answer_received(self, lock: AsyncLockLike[Any], answer: Any, /) -> None: ...
    def raised_other(self, lock: AsyncLockLike[Any], exc: BaseException, /) -> None: ...
    def task_raised_critical(self, lock: AsyncLockLike[Any], exc: BaseException, /) -> None: ...