'''Utilities that cannot be easily classified into any submodule.'''
from _collections_abc import Awaitable, Callable
from typing import Any, Literal, overload
__all__ = 'StateMachine', 'gather_with_limited_concurrency'
class StateMachine:
    def __init__(self, state: str, /): ...
    def add(self, from_state: str, to_state: str, condition: Callable[[], Awaitable[Any]]|None=...) -> None: ...
    def on_enter(self, state: str, handler: Callable[[], Awaitable[Any]]) -> None: ...
    def on_exit(self, state: str, handler: Callable[[], Awaitable[Any]]) -> None: ...
    async def transition(self, state: str, /) -> bool: ...
@overload
async def gather_with_limited_concurrency[T](n: int=..., /, *coros: Awaitable[T], ret_exc: Literal[False]=...) -> list[T]: ...
@overload
async def gather_with_limited_concurrency[T](n: int=..., /, *coros: Awaitable[T], ret_exc: Literal[True]) -> list[T|BaseException]: ...