'''Mixins classes for some common or specialized patterns that provide methods based on some abstract methods.'''
from ._internal.helpers import LoopMixinBase
from ._internal.types import ExcType
from .locks import LocksmithBase
from _collections_abc import AsyncGenerator, Awaitable, Callable, Coroutine, Generator
from abc import ABC, abstractmethod
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from asyncio.tasks import Task
from functools import cached_property
from types import TracebackType
from typing import Any, Literal, Self, overload
__all__ = 'AsyncContextMixin', 'AwaitableMixin', 'EventMixin', 'ExecutorRequiredAsyncContextMixin', 'LockMixin', 'LockWithOwnerMixin', 'LoopBoundMixin', 'LoopContextMixin'
class LoopContextMixin(LoopMixinBase):
    ''':meth:`__setup__` will be called when the context is entered and :meth:`__cleanup__` when it is exited.'''
    @property
    def running_tasks(self) -> set[Task[Any]]: '''A set of all tasks currently running in the underlying loop.'''
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    @overload
    async def __aexit__(self, exc_typ: ExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
class AwaitableMixin[T](ABC):
    '''A subclass that implements the async :meth:`wait` method automatically becomes awaitable, resolving to the return value of that method.'''
    def __await__(self) -> Generator[Any, None, T]: ...
    @abstractmethod
    def wait(self) -> Awaitable[T]: ...
class AsyncContextMixin[T](ABC):
    '''A mixin to derive :meth:`__aenter__` and :meth:`__aexit__` from :meth:`__enter__` (optional; returns self by default, but that cannot be typed accurately) and :meth:`__exit__` of subclasses.'''
    def __enter__(self) -> T: ...
    @overload
    @abstractmethod
    def __exit__(self, exc_typ: ExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> bool|None: ...
    @overload
    @abstractmethod
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> Literal[False]|None: ...
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> bool|None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> Literal[False]|None: ...
class ExecutorRequiredAsyncContextMixin[T](ABC):
    '''The above, but using an executor to convert the sync context manager methods to async in an event loop.'''
    @cached_property
    def runner[R, *Ts](self) -> Callable[[Callable[[*Ts], R], *Ts], Future[R]]: ...
    def __enter__(self) -> T: ...
    @overload
    @abstractmethod
    def __exit__(self, exc_typ: ExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> bool|None: ...
    @overload
    @abstractmethod
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> Literal[False]|None: ...
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> bool|None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> Literal[False]|None: ...
class LockMixin[T](ABC):
    '''A mixin to derive :meth:`__aenter__` and :meth:`__aexit__` from :meth:`acquire` and :meth:`release` of subclasses.'''
    def __init_subclass__(cls, *, _lock_factory: Callable[[Self], T]=..., **k: Any) -> None: ...
    @abstractmethod
    async def acquire(self) -> bool: ...
    @abstractmethod
    def release(self) -> Coroutine[Any, Any, None]|None: ...
    @abstractmethod
    def locked(self) -> bool: ...
    def acknowledge_locksmith_lock_held(self, smith: LocksmithBase, /) -> bool|Coroutine[Any, Any, bool]: ...
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
class LockWithOwnerMixin[T: (None, Coroutine[Any, Any, None])](LockMixin[None]):
    '''Mixin for locks that can report their owner (the task currently holding it).
    :meth:`is_owner` should return True if the current task is the owner of the lock, and :meth:`release` will wrap :meth:`_release` to throw :exc:`RuntimeError` if the current task is not the owner.'''
    @property
    @abstractmethod
    def is_owner(self) -> bool: ...
    @abstractmethod
    def _release(self) -> T: ...
    def release(self) -> T: ...
class LoopBoundMixin(LoopMixinBase):
    '''Mixin to bind event loops lazily for classes that need to create futures.'''
    @property
    def loop(self) -> AbstractEventLoop: ...
class EventMixin[T](AwaitableMixin[T], LoopBoundMixin, ABC):
    @abstractmethod
    async def wait_for_next(self, timeout: float|None=..., **k: Any) -> T: ...
    @abstractmethod
    def is_set(self) -> bool: ...
    @abstractmethod
    def get(self) -> T: ...
    @abstractmethod
    def set(self, value: T) -> None: ...
    @abstractmethod
    def clear(self) -> None: ...
    async def wait(self, timeout: float|None=..., **k: Any) -> T: ...
    async def wait_for_value(self, val: T, timeout: float|None=..., *, set_at_timeout: bool=...) -> None: ...
    def stream_history_for(self, duration: float|None=...) -> AsyncGenerator[T]: ...