from ._internal.helpers import _LoopMixinBase
from ._internal.protocols import ValidExcType
from .locks import LocksmithBase
from abc import ABCMeta, abstractmethod
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from _collections_abc import Generator, Callable, Coroutine, AsyncGenerator, Awaitable
from functools import cached_property
from types import TracebackType
from typing import Self, Literal, Any, overload
__all__ = 'EventualLoopMixin', 'LoopContextMixin', 'AwaitableMixin', 'AsyncContextMixin', 'LockMixin', 'LockWithOwnerMixin', 'EventMixin'
class EventualLoopMixin(_LoopMixinBase): '''An alternative to LoopContextMixin when __aenter__ and __aexit__ are used for other purposes (e.g. lock-like objects such as RLock, KeyedCondition)'''
class LoopContextMixin(_LoopMixinBase):
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
class AwaitableMixin[T](metaclass=ABCMeta):
    '''A subclass that implements the `wait` async method automatically becomes awaitable, resolving to the return value of that method.'''
    def __await__(self) -> Generator[Any, None, T]: ...
    @abstractmethod
    def wait(self) -> Awaitable[T]: ...
class AsyncContextMixin[T](metaclass=ABCMeta):
    '''`__exit__` is the only abstract method (`__enter__` returns self by default).'''
    @cached_property
    def runner[R, *Ts](self) -> Callable[[Callable[[*Ts], R], *Ts], Future[R]]: ...
    def __enter__(self) -> T: ...
    @overload
    def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> bool|None: ...
    @overload
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> Literal[False]|None: ...
    @abstractmethod
    def __exit__(self, /, *_): ...
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> bool|None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> bool|None: ...
class LockMixin[T=None, R: (None, Coroutine[Any, Any, None])=None](metaclass=ABCMeta):
    def __init_subclass__(cls, *, _lock_factory: Callable[[LockMixin], T]=..., **k) -> None: ...
    @abstractmethod
    async def acquire(self) -> bool: ...
    @abstractmethod
    def release(self) -> R: ...
    @abstractmethod
    def locked(self) -> bool: ...
    def acknowledge_locksmith_lock_held(self, smith: LocksmithBase, /) -> bool|Coroutine[Any, Any, bool]: ...
    async def __aenter__(self) -> T: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType|None, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
class LockWithOwnerMixin[T: (None, Coroutine[Any, Any, None])](LockMixin[None, T]):
    @property
    @abstractmethod
    def is_owner(self) -> bool: ...
    @abstractmethod
    def _release(self) -> T: ...
    def release(self) -> T: ...
class EventMixin[T](AwaitableMixin, metaclass=ABCMeta):
    @cached_property
    def loop(self) -> AbstractEventLoop: ...
    @abstractmethod
    async def wait_for_next(self, timeout: float|None=..., **k) -> T: ...
    @abstractmethod
    def is_set(self) -> bool: ...
    @abstractmethod
    def get(self) -> T: ...
    @abstractmethod
    def set(self, value: T) -> None: ...
    async def wait(self, timeout: float|None=..., **k) -> T: ...
    async def wait_for_value(self, val: T, timeout: float|None=..., *, set_at_timeout: bool=...) -> None: ...
    def stream_history_for(self, duration: float|None=...) -> AsyncGenerator[T, None]: ...