from .mixins import EventualLoopMixin
from asyncio.events import AbstractEventLoop
from asyncio.protocols import Protocol
from asyncio.transports import Transport, WriteTransport
from contextlib import _GeneratorContextManager
from socket import socket
from typing import Literal, ClassVar
__all__ = 'LineProtocol', 'LFProtocol', 'CRLFProtocol', 'CRProtocol', 'SocketTransport'
class LineProtocol(Protocol, EventualLoopMixin):
    NEWLINE: ClassVar[bytes]
    CARRIAGE_RETURN: ClassVar[bytes]
    @property
    def transport(self): ...
    @property
    def connected_transport(self) -> WriteTransport|None: ...
    def connection_made(self, transport: WriteTransport) -> None: ...
    def connection_lost(self, exc) -> None: ...
    def close(self) -> bool: ...
    def data_received(self, data: bytes, bufsize: int=...) -> None: ...
    def flush(self) -> None: ...
    def signal_eof(self) -> None: ...
    def pause_writing(self) -> None: ...
    def resume_writing(self) -> None: ...
    def _put_line(self, data: bytes) -> None: ...
    def write_line(self, line: str) -> None: ...
    def write_literal(self, data: bytes) -> None: ...
    def eof_received(self) -> None: ...
    async def read_line(self) -> str|None: ...
    async def drain(self) -> None: ...
    async def write_line_with_backpressure(self, line: str) -> None: ...
    async def write_literal_with_backpressure(self, data: bytes) -> None: ...
class LFProtocol(LineProtocol): ...
class CRLFProtocol(LineProtocol): ...
class CRProtocol(LineProtocol): ...
class SocketTransport(Transport):
    @classmethod
    def make_protocol(cls) -> Protocol: ...
    @property
    def loop(self) -> AbstractEventLoop: ...
    def __init__(self, sock: socket|None=...): ...
    def _reset_extra(self) -> None: ...
    def connect_sock(self, sock: socket) -> None: ...
    def disconnect_sock(self) -> socket|None: ...
    def sock_context(self, sock: socket) -> _GeneratorContextManager[None, None, None]: ...
    def write(self, data: bytes) -> None: ...
    def get_write_buffer_size(self) -> int: ...
    def get_write_buffer_limits(self) -> tuple[int, int]: ...
    def set_write_buffer_limits(self, high: int|None=..., low: int|None=...) -> None: ...
    def write_eof(self) -> None: ...
    def can_write_eof(self) -> Literal[True]: ...
    def is_closing(self) -> bool: ...
    def close(self, e=None) -> None: ...
    def get_protocol(self) -> LineProtocol: ...
    def abort(self) -> None: ...