from .mixins import EventualLoopMixin
from asyncio.events import AbstractEventLoop
from asyncio.protocols import Protocol
from asyncio.transports import Transport, WriteTransport
from contextlib import _GeneratorContextManager
from socket import socket
from typing import Literal, ClassVar
__all__ = 'CRLFProtocol', 'CRProtocol', 'LFProtocol', 'LineProtocol', 'SocketTransport'
class LineProtocol(Protocol, EventualLoopMixin):
    '''An implementation of asyncio.protocols.Protocol providing line-based buffering and writing.
    The idea was originally introduced in PEP 3153, but did not see eventual adaptation in the standard library.
    This particular implementation is designed to be used with SocketTransport, though other transports can enforce it too.
    Instantiating this class will give an LFProtocol or CRLFProtocol depending on os.linesep.'''
    NEWLINE: ClassVar[bytes]
    '''The newline sequence used by this protocol as bytes.'''
    CARRIAGE_RETURN: ClassVar[bytes]
    '''The carriage return sequence used by this protocol as bytes.'''
    @property
    def transport(self) -> WriteTransport|None: '''The transport associated with this protocol, or None if not connected.'''
    @property
    def connected_transport(self) -> WriteTransport: '''The transport associated with this protocol; raises ConnectionError if not connected.'''
    def connection_made(self, transport: WriteTransport) -> None: ... # type: ignore[override]
    def connection_lost(self, exc: Exception|None) -> None: ...
    def close(self) -> bool: '''Close the transport and return success.'''
    def data_received(self, data: bytes, bufsize: int=...) -> None: ...
    def flush(self) -> None: '''Flush the internal buffer and put in remaining data as a single line.'''
    def signal_eof(self) -> None: '''Signal that the stream is at EOF.'''
    def pause_writing(self) -> None: ...
    def resume_writing(self) -> None: ...
    def _put_line(self, data: bytes) -> None: '''Put the given data into the buffer as a single line.'''
    def write_line(self, line: str) -> None: '''Write the string `line` to the transport, followed by the newline sequence.'''
    def write_literal(self, data: bytes) -> None: '''Write the given bytes into the transport without appending a newline.'''
    def eof_received(self) -> None: ...
    async def read_line(self) -> str|None: ...
    async def drain(self) -> None: ...
    async def write_line_with_backpressure(self, line: str) -> None: ...
    async def write_literal_with_backpressure(self, data: bytes) -> None: ...
class LFProtocol(LineProtocol): '''Line Feed protocol for Unix-like systems.'''
class CRLFProtocol(LineProtocol): '''Carriage Return + Line Feed protocol for Windows.'''
class CRProtocol(LineProtocol): '''Carriage Return protocol. For legacy systems no longer officially supported by python, such as Mac OS 9.'''
class SocketTransport(Transport):
    @classmethod
    def make_protocol(cls) -> Protocol: ...
    @property
    def loop(self) -> AbstractEventLoop: ...
    def __init__(self, sock: socket|None=...): ...
    def _reset_extra(self) -> None: ...
    def connect_sock(self, sock: socket) -> None: ...
    def disconnect_sock(self) -> socket|None: ...
    def sock_context(self, sock: socket) -> _GeneratorContextManager[None, None, None]: ...
    def write(self, data: bytes) -> None: ...
    def get_write_buffer_size(self) -> int: ...
    def get_write_buffer_limits(self) -> tuple[int, int]: ...
    def set_write_buffer_limits(self, high: int|None=..., low: int|None=...) -> None: ...
    def write_eof(self) -> None: ...
    def can_write_eof(self) -> Literal[True]: ...
    def is_closing(self) -> bool: ...
    def close(self, e: Exception|None=...) -> None: ...
    def get_protocol(self) -> LineProtocol: ...
    def abort(self) -> None: ...