from .config import Executor
from ._internal.protocols import SupportsIteration, ValidExcType
from .mixins import LoopContextMixin, AsyncContextMixin
from asyncio.events import AbstractEventLoop
from asyncio.futures import Future
from asyncio.tasks import Task
from _collections_abc import Mapping, Callable, Iterable, Generator
from types import TracebackType
from typing import Any, Self, overload
__all__ = 'AdvancedPool', 'CallbackAccumulator', 'ConnectionPool', 'Pool'
class Pool[T, R](LoopContextMixin):
    def __init__(self, func: Callable[[T], R], it: SupportsIteration[T], workers: int=..., bounded: bool=...): ...
    async def process(self, item: T) -> None: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> R: ...
    async def __aenter__(self) -> Self: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    async def aclose(self) -> None: ...
class AdvancedPool(LoopContextMixin):
    '''Use instances of this class as async context managers only.'''
    def __init__(self, max_workers: int=..., min_workers: int=..., qsize: int=..., scaling: bool=..., kill_at_exit: bool=...): ...
    def set_adjuster(self, raising: bool=...) -> None: ...
    def raise_for_shutdown(self) -> None: ...
    @overload
    def submit_nowait[T, **P](self, f: Callable[P, T], *a: P.args, **k: P.kwargs) -> Future[T]: ...
    @overload
    def submit_nowait[T](self, f: Callable[..., T], *a: Any, _priority_: int, **k: Any) -> Future[T]: ... # type: ignore[overload-cannot-match]
    def dead(self, worker: Task[Any]) -> bool: ...
    def revive(self) -> None: ...
    @overload
    async def submit[T, **P](self, f: Callable[P, T], *a: P.args, **k: P.kwargs) -> Future[T]: ...
    @overload
    async def submit[T](self, f: Callable[..., T], *a: Any, _priority_: int, **k: Any) -> Future[T]: ... # type: ignore[overload-cannot-match]
    async def shutdown(self, cancel_pending: bool=..., idle_timeout: float|None=..., total_timeout: float|None=...) -> float: ...
    async def gather(self, ret_exc: bool=...) -> list[Any]: ...
    @overload
    async def map[R, T](self, f: Callable[[R], T], it: Iterable[R], /, *, priority: int=...) -> list[T]: ...
    @overload
    async def map[R, V, T](self, f: Callable[[R, V], T], i1: Iterable[R], i2: Iterable[V], /, *, priority: int=...) -> list[T]: ...
    @overload
    async def map[R, V, U, T](self, f: Callable[[R, V, U], T], i1: Iterable[R], i2: Iterable[V], i3: Iterable[U], /, *, priority: int=...) -> list[T]: ...
    @overload
    async def map[R, V, U, S, T](self, f: Callable[[R, V, U, S], T], i1: Iterable[R], i2: Iterable[V], i3: Iterable[U], i4: Iterable[S], /, *, priority: int=...) -> list[T]: ...
    async def starmap[T, *Ts](self, f: Callable[[*Ts], T], it: Iterable[tuple[*Ts]], priority: int=...) -> list[T]: ...
    async def doublestarmap[T](self, f: Callable[..., T], it: Iterable[Mapping[str, Any]], priority: int=...) -> list[T]: ...
    async def starmap_withkwds[T](self, f: Callable[..., T], it: Iterable[tuple[Iterable[Any], Mapping[str, Any]]], priority: int=...) -> list[T]: ...
    async def resize(self, min: int, max: int) -> None: ... # noqa: A002
    async def drain(self) -> None: ...
    def restart_worker[T: Task[Any]](self, worker: T) -> T: ...
    async def health_check(self) -> bool: ...
    async def wait_for_slot(self, timeout: float|None=...) -> float: ...
    async def __cleanup__(self) -> None: ...
    @property
    def full(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    @property
    def qsize(self) -> int: ...
    @property
    def idle(self) -> bool: ...
    @property
    def uptime(self) -> float: ...
    @property
    def completed(self) -> int: ...
class ConnectionPool[T, **P]:
    def __init__(self, factory: Callable[P, T], maxsize: int=..., minsize: int=..., maxlife: float=..., healthchecker: Callable[[T], bool]|None=..., cleaner: Callable[[T], None]|None=...): ...
    def _is_healthy(self, conn: T, /) -> bool: ...
    @overload
    async def create_connection(self, *a: P.args, **k: P.kwargs) -> T: ...
    @overload
    async def create_connection(self, *a: Any, _executor_: Executor|None, **k: Any) -> T: ...
    async def acquire(self, *a: P.args, **k: P.kwargs) -> T: ...
    async def release(self, conn: T, /, *a: P.args, **k: P.kwargs) -> None: ...
    async def _maintain(self, intvl: float=...) -> None: ...
    async def start(self, akgen: SupportsIteration[tuple[Iterable[Any], Mapping[str, Any]]]|None=..., executor: Executor|None=...) -> None: ...
    async def stop(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    @property
    def loop(self) -> AbstractEventLoop: ...
    @loop.setter
    def loop(self, val: AbstractEventLoop, /) -> None: ...
    @loop.deleter
    def loop(self) -> None: ...
    @property
    def currsize(self) -> int: ...
    @property
    def available(self) -> int: ...
    @property
    def in_use(self) -> int: ...
    @property
    def maxsize(self) -> int: ...
    @property
    def minsize(self) -> int: ...
    @property
    def maxlife(self) -> float: ...
class CallbackAccumulator[T, **P](AsyncContextMixin[CallbackAccumulator[T, P]]):
    '''A utility `collections.deque` subclass to store callbacks and call them at once when the context manager exits.
    To iterate through the callbacks at this moment safely, use the `callbacks` attribute.'''
    @overload
    def __init__(self, name: str, it: SupportsIteration[Callable[P, T]], maxlen: int|None=..., default: Any=..., call_once: bool=..., default_getter: Callable[[], tuple[Iterable[Any], Mapping[str, Any]]]=...): ...
    @overload
    def __init__(self, name: str, *, maxlen: int|None=..., default: Any=..., call_once: bool=..., default_getter: Callable[[], tuple[Iterable[Any], Mapping[str, Any]]]=...): ...
    def __call__(self, *a: P.args, **k: P.kwargs) -> None: ...
    def _call_default(self) -> None: ...
    @overload
    def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    def add(self, o: Any, /) -> None: ...
    def offer_last(self, o: Any, /) -> None: ...
    @property
    def callbacks(self) -> Self: ...
    def __iter__(self) -> Generator[T, None, None]: ...