'''This module provides various pool implementations for concurrent execution and resource management in asynchronous contexts.'''
from ._internal.types import SupportsIteration, ValidExcType
from .config import Executor
from .mixins import AsyncContextMixin, LoopBoundMixin, LoopContextMixin
from _collections_abc import Callable, Generator, Iterable, Mapping
from asyncio.futures import Future
from collections import deque
from types import TracebackType
from typing import Any, Self, overload
__all__ = 'AdvancedPool', 'CallbackAccumulator', 'ConnectionPool', 'Pool'
class Pool[T, R](LoopContextMixin):
    '''Maps a function over an (async) iterable. Use instances of this class as async context managers only.'''
    def __init__(self, func: Callable[[T], R], it: SupportsIteration[T], /, workers: int=...): '''Apply `func` to each item in `it` with limited concurrency and yield results as they come.'''
    async def process(self, item: T) -> None: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> R: ...
    async def __aenter__(self) -> Self: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    async def aclose(self) -> None: ...
class AdvancedPool(LoopContextMixin):
    '''A pool implementation used to call sync functions concurrently in an async-first interface, managing event loop and threading resource shenanigans internally.
    Use instances of this class as async context managers only.'''
    def __init__(self, max_workers: int=..., min_workers: int=..., qsize: int=..., scaling: bool=..., kill_at_exit: bool=...): ...
    def set_adjuster(self, raising: bool=...) -> None: ...
    def raise_for_shutdown(self) -> None: ...
    @overload
    def submit_nowait[T, **P](self, f: Callable[P, T], *a: P.args, **k: P.kwargs) -> Future[T]: ...
    @overload
    def submit_nowait[T](self, f: Callable[..., T], *a: Any, _priority_: int, **k: Any) -> Future[T]: ... # type: ignore[overload-cannot-match]
    def revive(self) -> None: ...
    @overload
    async def submit[T, **P](self, f: Callable[P, T], *a: P.args, **k: P.kwargs) -> Future[T]: ...
    @overload
    async def submit[T](self, f: Callable[..., T], *a: Any, _priority_: int, **k: Any) -> Future[T]: ... # type: ignore[overload-cannot-match]
    @overload
    async def complete[T, **P](self, f: Callable[P, T], *a: P.args, **k: P.kwargs) -> T: ...
    @overload
    async def complete[T](self, f: Callable[..., T], *a: Any, _priority_: int, **k: Any) -> T: ... # type: ignore[overload-cannot-match]
    async def shutdown(self, cancel_pending: bool=..., idle_timeout: float|None=..., total_timeout: float|None=...) -> float: ...
    async def join(self) -> list[int|BaseException]: ...
    @overload
    async def map[R, T](self, f: Callable[[R], T], it: Iterable[R], /, *, priority: int=..., strict: bool=...) -> list[T]: ...
    @overload
    async def map[R, V, T](self, f: Callable[[R, V], T], i1: Iterable[R], i2: Iterable[V], /, *, priority: int=..., strict: bool=...) -> list[T]: ...
    @overload
    async def map[R, V, U, T](self, f: Callable[[R, V, U], T], i1: Iterable[R], i2: Iterable[V], i3: Iterable[U], /, *, priority: int=..., strict: bool=...) -> list[T]: ...
    @overload
    async def map[R, V, U, S, T](self, f: Callable[[R, V, U, S], T], i1: Iterable[R], i2: Iterable[V], i3: Iterable[U], i4: Iterable[S], /, *, priority: int=..., strict: bool=...) -> list[T]: ...
    async def starmap[T, *Ts](self, f: Callable[[*Ts], T], it: Iterable[tuple[*Ts]], /, priority: int=...) -> list[T]: ...
    async def doublestarmap[T](self, f: Callable[..., T], it: Iterable[Mapping[str, Any]], /, priority: int=...) -> list[T]: ...
    async def starmap_withkwds[T](self, f: Callable[..., T], it: Iterable[tuple[Iterable[Any], Mapping[str, Any]]], /, priority: int=...) -> list[T]: ...
    async def resize(self, min: int, max: int) -> None: ... # noqa: A002
    async def drain(self) -> None: ...
    async def wait_for_slot(self, timeout: float|None=...) -> float: ...
    async def __cleanup__(self) -> None: ...
    @property
    def full(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    @property
    def qsize(self) -> int: ...
    @property
    def idle(self) -> bool: ...
    @property
    def uptime(self) -> float: ...
    @property
    def completed(self) -> int: ...
class ConnectionPool[T, **P](LoopBoundMixin):
    '''A pool managing resources in a simple and intuitive lock interface, with support for health checking, auto-recycling and dynamic rescaling.
    Use instances of this class as async context managers only.'''
    def __init__(self, factory: Callable[P, T], maxsize: int=..., minsize: int=..., maxlife: float=..., healthchecker: Callable[[T], bool]|None=..., cleaner: Callable[[T], None]|None=...): ...
    def _is_healthy(self, conn: T, /) -> bool: ...
    @overload
    async def create_connection(self, *a: P.args, **k: P.kwargs) -> T: ...
    @overload
    async def create_connection(self, *a: Any, _executor_: Executor|None, **k: Any) -> T: ...
    async def acquire(self, *a: P.args, **k: P.kwargs) -> T: ...
    async def release(self, conn: T, /, *a: P.args, **k: P.kwargs) -> None: ...
    async def _maintain(self) -> None: ...
    async def start(self, akgen: SupportsIteration[tuple[Iterable[Any], Mapping[str, Any]]]|None=..., executor: Executor|None=...) -> None: ...
    async def stop(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    @overload
    async def __aexit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    async def __aexit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    @property
    def currsize(self) -> int: ...
    @property
    def available(self) -> int: ...
    @property
    def in_use(self) -> int: ...
    @property
    def maxsize(self) -> int: ...
    @property
    def minsize(self) -> int: ...
    @property
    def maxlife(self) -> float: ...
class CallbackAccumulator[T, **P](deque, AsyncContextMixin[CallbackAccumulator[T, P]]):
    '''A utility class store callbacks and call them at once when the context manager exits.
    To iterate through the callbacks at this moment safely, use the :attr:`callbacks` attribute.
    The behaviour of this class as a :class:`~collections.deque` is an implementation detail.
    This class is no longer used by the pools after a massive rewrite, and only remains here for backwards compatibility.'''
    @overload
    def __init__(self, name: str, it: SupportsIteration[Callable[P, T]], maxlen: int|None=..., default: object=..., call_once: bool=..., default_getter: Callable[[], tuple[Iterable[object], Mapping[str, object]]]=...): ...
    @overload
    def __init__(self, name: str, *, maxlen: int|None=..., default: object=..., call_once: bool=..., default_getter: Callable[[], tuple[Iterable[object], Mapping[str, object]]]=...): ...
    def __call__(self, *a: P.args, **k: P.kwargs) -> None: ...
    def __enter__(self) -> Self: ...
    @overload
    def __exit__(self, exc_typ: ValidExcType, exc_val: BaseException, exc_tb: TracebackType, /) -> None: ...
    @overload
    def __exit__(self, exc_typ: None, exc_val: None, exc_tb: None, /) -> None: ...
    def add(self, o: object, /) -> None: ...
    def offer_last(self, o: object, /) -> None: ...
    @property
    def callbacks(self) -> Self: ...
    def __iter__(self) -> Generator[T]: ...