from ._internal.protocols import SupportsIteration
from .mixins import LoopContextMixin, AsyncContextMixin
from .config import Executor
from typing import Any, Self
from _collections_abc import Mapping, AsyncIterable, Callable, Iterable, Generator
from asyncio.events import AbstractEventLoop
from asyncio.tasks import Task
from asyncio.futures import Future
__all__ = 'Pool', 'AdvancedPool', 'ConnectionPool', 'CallbackAccumulator'
class Pool[T, R]:
    def __init__(self, func: Callable[[T], R], it: SupportsIteration[T], workers: int=..., bounded: bool=...): ...
    async def process(self, item: T) -> None: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> R: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, /, *_) -> None: ...
    async def aclose(self) -> None: ...
class AdvancedPool(LoopContextMixin):
    '''Use instances of this class as async context managers only.'''
    def __init__(self, max_workers: int=..., min_workers: int=..., qsize: int=..., scaling: bool=..., kill_at_exit: bool=...): ...
    def __repr__(self) -> str: ...
    def set_adjuster(self, raising: bool=...) -> None: ...
    def raise_for_shutdown(self) -> None: ...
    def submit_nowait(self, f: Callable, *a, _priority: int=..., **k) -> Future[Any]: ...
    def dead(self, worker: Task) -> bool: ...
    def revive(self) -> None: ...
    async def submit(self, f: Callable, *a, _priority: int=..., **k) -> Future[Any]: ...
    async def shutdown(self, cancel_pending: bool=..., idle_timeout: float|None=..., total_timeout: float|None=...) -> float: ...
    async def gather(self, ret_exc: bool=...) -> list[Any]: ...
    async def map(self, f: Callable, it: Iterable, priority: int=...) -> list[Any]: ...
    async def starmap(self, f: Callable, it: Iterable[Iterable], priority: int=...) -> list[Any]: ...
    async def doublestarmap(self, f: Callable, it: Iterable[Mapping[str, Any]], priority: int=...) -> list[Any]: ...
    async def starmap_withkwds(self, f: Callable, it: Iterable[tuple[Iterable, Mapping[str, Any]]], priority: int=...) -> list[Any]: ...
    async def resize(self, _min: int, _max: int) -> None: ...
    async def drain(self) -> None: ...
    async def restart_worker(self, worker: Task) -> Task: ...
    async def health_check(self) -> bool: ...
    async def wait_for_slot(self, timeout: float|None=...) -> float: ...
    async def wait_until_idle(self, timeout: float|None=...) -> None: ...
    async def __cleanup__(self) -> None: ...
    @property
    def full(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    @property
    def qsize(self) -> int: ...
    @property
    def idle(self) -> bool: ...
    @property
    def uptime(self) -> float: ...
    @property
    def completed(self) -> int: ...
class ConnectionPool[T]:
    def __init__(self, factory: Callable[..., T], maxsize: int=..., minsize: int=..., maxlife: float=3600, healthchecker: Callable[[T], bool]|None=..., cleaner: Callable[[T], None]|None=...): ...
    def _is_healthy(self, conn: T, /) -> bool: ...
    async def create_connection(self, *a, _executor_: Executor|None=..., **k) -> T: ...
    async def acquire(self, *a, **k) -> T: ...
    async def release(self, conn, /, *a, **k) -> None: ...
    async def _maintain(self, intvl: float=...) -> None: ...
    async def start(self, akgen: AsyncIterable[tuple[tuple, dict[str, Any]]]|None=..., executor: Executor|None=...) -> None: ...
    async def stop(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, /, *_) -> None: ...
    @property
    def loop(self) -> AbstractEventLoop: ...
    @loop.setter
    def loop(self, val: AbstractEventLoop, /) -> None: ...
    @loop.deleter
    def loop(self) -> None: ...
    @property
    def currsize(self) -> int: ...
    @property
    def available(self) -> int: ...
    @property
    def in_use(self) -> int: ...
    @property
    def maxsize(self) -> int: ...
    @property
    def minsize(self) -> int: ...
    @property
    def maxlife(self) -> float: ...
class CallbackAccumulator[T, **P](AsyncContextMixin):
    '''A utility `collections.deque` subclass to store callbacks and call them at once when the context manager exits.
    To iterate through the callbacks at this moment safely, use the callbacks attribute.'''
    def __init__(self, name: str, it: SupportsIteration[Callable[P, T]]=..., maxlen: int|None=..., default: Any=..., call_once: bool=..., default_getter: Callable[[], tuple[Iterable, Mapping[str, Any]]]|None=...): ...
    def __call__(self, *a: P.args, **k: P.kwargs) -> None: ...
    def _call_default(self) -> None: ...
    def __exit__(self, /, *_) -> None: ...
    def add(self, o, /) -> None: ...
    def offer_last(self, o, /) -> None: ...
    @property
    def callbacks(self) -> Self: ...
    def __iter__(self) -> Generator[T, None, None]: ...