from .mixins import LoopContextMixin
from ._internal.protocols import Exceptable, Timer, SupportsIteration
from typing import Literal
from _collections_abc import Awaitable, Callable, AsyncGenerator, Coroutine
__all__ = 'SemBatchProcessor', 'BatchProcessor', 'Bulkhead'
class SemBatchProcessor[T, R]:
    def __init__(self, processor: Callable[[list[T]], Awaitable[R]], batch: int=..., max_concurrent: int=..., bounded: bool=...): ...
    def process(self, items: SupportsIteration[T]) -> AsyncGenerator[R, None]: ...
class BatchProcessor[T](LoopContextMixin):
    def __init__(self, processor: Callable[[list], Awaitable[T]], *, maxsize: int=..., maxtime: float=..., timer: Timer=...): ...
    async def add(self, item) -> T: ...
    async def _schedule_flush(self) -> None: ...
    async def _process(self) -> None: ...
    async def __call__(self, b: list, /) -> T: ...
    async def flush(self) -> None: ...
    @property
    def time_since_last_process(self) -> float: ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
class Bulkhead(LoopContextMixin):
    def __init__(self, max_concurrent: int, max_queue: int=..., bounded: bool=..., max_rej: int=..., exc: Exceptable=..., processor: Callable[[BaseException], Awaitable[None]]=...): ...
    async def __cleanup__(self) -> None: ...
    async def execute(self, coro: Coroutine) -> None: ...
    @property
    def available_slots(self) -> int: ...
    @property
    def active_tasks(self) -> int: ...
    @property
    def curr_qsize(self) -> int: ...
    @property
    def max_qsize(self) -> int: ...
    @property
    def available_qslots(self) -> int: ...
    @property
    def is_available(self) -> bool: ...
    @property
    def is_shutdown(self) -> bool: ...
    @property
    def rejected(self) -> int: ...
    async def wait_until_idle(self, timeout: float|None=None) -> Literal[True]: ...
    async def shutdown(self, timeout: float|None=None) -> list[Coroutine]: ...