'''Processors for asynchronous tasks.'''
from ._internal.types import Exceptable, SupportsIteration, Timer
from .mixins import LoopContextMixin
from _collections_abc import AsyncGenerator, Awaitable, Callable, Coroutine
from typing import Any, Literal
__all__ = 'BatchProcessor', 'BoundedBatchProcessor', 'Bulkhead'
class BoundedBatchProcessor[T, R]:
    '''Call a processor with items batched to a certain size from different sources with bounded concurrency.'''
    def __init__(self, processor: Callable[[list[T]], Awaitable[R]], batch: int=..., max_concurrent: int=...) -> None: ...
    def process(self, items: SupportsIteration[T]) -> AsyncGenerator[R]: ...
class BatchProcessor[T](LoopContextMixin):
    '''Call a processor with items batched to a certain size from different sources, with an optional time limit for batches.
    Use instances of this class as async context managers to ensure proper cleanup.'''
    def __init__(self, processor: Callable[[list[T]], Awaitable[None]], *, maxsize: int=..., maxtime: float=..., timer: Timer=...) -> None: ...
    async def add(self, item: T) -> None: '''Add an item to the current batch. If the batch is full, process it asynchronously before returning.'''
    async def flush(self) -> None: ...
    @property
    def time_since_last_process(self) -> float: ...
    async def __setup__(self) -> None: ...
    async def __cleanup__(self) -> None: ...
class Bulkhead(LoopContextMixin):
    '''Limit the number of concurrent executions of a processor, with an optional queue for pending executions and an optional callback for handling exceptions raised by the processor.
    Use instances of this class as async context managers to ensure proper cleanup.'''
    def __init__(self, max_concurrent: int, *, max_queue: int=..., max_rej: int=..., exc: Exceptable=..., processor: Callable[[BaseException], Awaitable[None]]=...) -> None: ...
    async def __cleanup__(self) -> None: ...
    async def execute(self, coro: Coroutine[Any, Any, Any]) -> None: ...
    @property
    def available_slots(self) -> int: ...
    @property
    def active_tasks(self) -> int: ...
    @property
    def curr_qsize(self) -> int: ...
    @property
    def max_qsize(self) -> int: ...
    @property
    def available_qslots(self) -> int: ...
    @property
    def is_available(self) -> bool: ...
    @property
    def is_shutdown(self) -> bool: ...
    @property
    def rejected(self) -> int: ...
    async def wait_until_idle(self, timeout: float|None=...) -> Literal[True]: ...
    async def shutdown(self, timeout: float|None=...) -> list[Coroutine[Any, Any, Any]]: ...