from ._internal.protocols import AsyncLockLike
from _collections_abc import Awaitable, Callable
from asyncio.events import AbstractEventLoop
from asyncio.locks import Lock
from typing import Any, Concatenate, Self, final, overload
__all__ = 'AsyncLockProperty', 'AsyncProperty', 'coercedmethod'
class AsyncProperty[T, R]:
    @overload
    def __new__(cls, *, doc: str|None=..., strict: bool=..., loop: AbstractEventLoop|None=...) -> Callable[[Callable[[R], Awaitable[T]]], Self]: ... # type: ignore[misc]
    @overload
    def __new__(cls, fget: Callable[[R], Awaitable[T]]|None, fset: Callable[[R, T], Awaitable[None]]|None=..., fdel: Callable[[R], Awaitable[None]]|None=..., *, doc: str|None=..., strict: bool=..., loop: AbstractEventLoop|None=..., lock_getter: Callable[[R], AsyncLockLike[Any]]|None=...) -> Self: ...
    def __init__(self, fget: Callable[[R], Awaitable[T]]|None, fset: Callable[[R, T], Awaitable[None]]|None=..., fdel: Callable[[R], Awaitable[None]]|None=..., *, doc: str|None=..., strict: bool=..., loop: AbstractEventLoop|None=..., lock_getter: Callable[[R], AsyncLockLike[Any]]|None=...): ...
    @overload
    def __get__(self, instance: R, owner: type[R]|None=..., /) -> Self|T: ...
    @overload
    def __get__(self, instance: None, owner: type, /) -> Self: ...
    def __set__(self, instance: R, value: T, /) -> None: ...
    def __delete__(self, instance: R, /) -> None: ...
    def __set_name__(self, typ: type[R], name: str, /) -> None: ...
    def getter(self, fget: Callable[[R], Awaitable[T]], /) -> Self: ...
    def setter(self, fset: Callable[[R, T], Awaitable[None]], /) -> Self: ...
    def deleter(self, fdel: Callable[[R], Awaitable[None]], /) -> Self: ...
class AsyncLockProperty[T, R](AsyncProperty[T, R]):
    @overload
    @staticmethod
    def _new_lock[L: AsyncLockLike[Any]](_: R, *, lock_impl: type[L]) -> L: '''Create a new lock for the given object. The implementation should not cache the locks for each instance, since that is done by this class already.'''
    @overload
    @staticmethod
    def _new_lock(_: R) -> Lock: '''Create a new lock for the given object. The implementation can refer to the properties of the object, but should not cache the locks for each instance, since that is done by this class already.'''
    @overload
    def __new__(cls, *, doc: str|None=..., strict: bool=..., loop: AbstractEventLoop|None=..., lock_getter: Callable[[R], AsyncLockLike[Any]]|None=...) -> Callable[[Callable[[R], Awaitable[T]]], Self]: ... # type: ignore[misc]
    @overload
    def __new__(cls, fget: Callable[[R], Awaitable[T]]|None, fset: Callable[[R, T], Awaitable[None]]|None=..., fdel: Callable[[R], Awaitable[None]]|None=..., *, doc: str|None=..., strict: bool=..., loop: AbstractEventLoop|None=..., lock_getter: Callable[[R], AsyncLockLike[Any]]|None=...) -> Self: ...
    def get_lock(self, obj: R) -> AsyncLockLike[Any]: ...
@final
class coercedmethod[T, R, **P]: # noqa: N801
    def __init__(self, func: Callable[Concatenate[R, P], T], /): ...
    def __getattr__(self, name: str, /) -> Any: ...
    def __set_name__(self, owner: type[R], name: str, /) -> None: ...
    def __get__(self, instance: R, owner: type[R]|None=..., /) -> Callable[P, T]: ...