from .exceptions import IgnoreErrors, PasswordQueueError as PasswordQueueError, PasswordRetrievalError as PasswordRetrievalError, GetPasswordRetrievalError as GetPasswordRetrievalError, PutPasswordRetrievalError as PutPasswordRetrievalError, ForbiddenOperation as ForbiddenOperation, PasswordError as PasswordError, WrongPassword as WrongPassword, WrongPasswordType as WrongPasswordType
from .mixins import EventualLoopMixin
from ._internal.protocols import SupportsIteration
from abc import ABCMeta, abstractmethod
from typing import Any, Protocol, Literal, Self, ClassVar, overload, type_check_only
from _collections_abc import Callable, Generator, AsyncGenerator, Awaitable, Coroutine
from contextlib import _AsyncGeneratorContextManager
from asyncio.queues import Queue
from asyncio.futures import Future
__all__ = 'ignore_qempty', 'ignore_qfull', 'ignore_qshutdown', 'ignore_qerrs', 'ignore_valerrs', 'GetPasswordRetrievalError', 'PutPasswordRetrievalError', 'ForbiddenOperation', 'WrongPassword', 'WrongPasswordType', 'password_queue', 'PotentQueueBase', 'SmartQueue', 'SmartLifoQueue', 'SmartPriorityQueue', 'UserPriorityQueue'
ignore_qshutdown: IgnoreErrors
ignore_qempty: IgnoreErrors
ignore_qfull: IgnoreErrors
ignore_qerrs: IgnoreErrors
ignore_valerrs: IgnoreErrors
@type_check_only
class _Q[R, T](Protocol):
    '''A protocol for password-protected queues. Does not exist at runtime.'''
    async def get(self) -> T: ...
    async def put(self, item: T) -> None: ...
    def get_nowait(self) -> T: ...
    def put_nowait(self, item: T) -> None: ...
    def qsize(self) -> int: ...
    def task_done(self) -> None: ...
    @property
    def maxsize(self) -> int: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    async def join(self) -> None: ...
    def shutdown(self, immediate: bool=...) -> None: ...
    def change_get_password(self, old_pwd: R, new_pwd: R) -> bool: '''Attempts to change the get password of the password-protected queue to new_pwd; returns success.'''
    def change_put_password(self, old_pwd: R, new_pwd: R) -> bool: '''Attempts to change the put password of the password-protected queue to new_pwd; returns success.'''
    handle: ClassVar[Future|None]
@type_check_only
class _G[R, T](_Q[R, T], Protocol):
    '''Does not exist at runtime.'''
    async def get(self, pwd: R) -> T:
        '''Removes and returns an item from the password-protected queue, if the password provided was correct; raises WrongPassword otherwise.
        If the queue is empty, waits until an item is available.'''
    def get_nowait(self, pwd: R) -> T:        
        '''Removes and returns an item from the password-protected queue, if the password provided was correct; raises WrongPassword otherwise.
        If the queue is empty, raises asyncio.QueueEmpty.'''
@type_check_only
class _P[R, T](_Q[R, T], Protocol):
    '''Does not exist at runtime.'''
    async def put(self, item: T, pwd: R) -> None:
        '''Puts an item into the password-protected queue, if the password provided was correct; raises WrongPassword otherwise.
        If the queue is full, waits until a free slot is available.'''
    def put_nowait(self, item: T, pwd: R) -> None:
        '''Puts an item into the password-protected queue, if the password provided was correct; raises WrongPassword otherwise.
        If the queue is full, raises asyncio.QueueFull.'''
@type_check_only
class _B[R, V, T](_G[R, T], _P[V, T], Protocol): '''Does not exist at runtime.'''
@overload
def password_queue[T, R](password_put: R, *, maxsize: int=..., protect_get: Literal[False]=..., protect_put: Literal[True]=..., can_change_put: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., put_from: str=..., puttyp: type[R]=..., init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[False], Literal[True], str, str], None]=...) -> _P[R, T]:
    '''Returns a password-protected queue, inheriting from asyncio.Queue, with maximum size maxsize. priority and lifo parameters determine if the queue is a priority queue and last-in-first-out.
    If protect_get is True, get and get_nowait will require a password, specified by password_get or retrieved from a variable in the caller's scope with name get_from (default 'password').
    If protect_put is True, put and put_nowait will require a password, specified by password_put or retrieved from a variable in the caller's scope with name put_from (default 'password').
    If init_items is specified, the items in that (async) iterable will be put into the queue immediately. If there are too many items in the (async) iterable, parameters wait and raising determine the behaviour; log is a function used to emit warnings in that case.
    auditf (default sys.audit) is an audit function that takes the event name ('asyncutils.queues.password_queue'), protect_get, protect_put, get_from, put_from and returns None; note that the passwords are not passed to the audit function.'''
@overload
def password_queue[T, R](*, maxsize: int=..., protect_get: Literal[False]=..., protect_put: Literal[True]=..., can_change_put: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., put_from: str=..., puttyp: type[R]=object, init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[False], Literal[True], str, str], None]=...) -> _P[R, T]: ...
@overload
def password_queue[T, R](*, password_get: R, maxsize: int=..., protect_get: Literal[True], protect_put: Literal[False], can_change_get: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., get_from: str=..., gettyp: type[R]=..., init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[True], Literal[False], str, str], None]=...) -> _G[R, T]: ...
@overload
def password_queue[T, R](*, maxsize: int=..., protect_get: Literal[True], protect_put: Literal[False], can_change_get: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., get_from: str=..., gettyp: type[R]=object, init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[True], Literal[False], str, str], None]=...) -> _G[R, T]: ...
@overload
def password_queue[T, R, V](password_put: V, password_get: R, maxsize: int=..., *, protect_get: Literal[True], protect_put: Literal[True]=..., can_change_get: bool=..., can_change_put: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., get_from: str=..., put_from: str=..., gettyp: type[R]=..., puttyp: type[V]=..., init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[True], Literal[True], str, str], None]=...) -> _B[R, V, T]: ...
@overload
def password_queue[T, R, V](password_put: V, *, maxsize: int=..., protect_get: Literal[True], protect_put: Literal[True]=..., can_change_get: bool=..., can_change_put: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., get_from: str=..., put_from: str=..., gettyp: type[R]=object, puttyp: type[V]=..., init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[True], Literal[True], str, str], None]=...) -> _B[R, V, T]: ...
@overload
def password_queue[T, R, V](*, password_get: R, maxsize: int=..., protect_get: Literal[True], protect_put: Literal[True]=..., can_change_get: bool=..., can_change_put: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., get_from: str=..., put_from: str=..., gettyp: type[R]=..., puttyp: type[V]=object, init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[True], Literal[True], str, str], None]=...) -> _B[R, V, T]: ...
@overload
def password_queue[T, R, V](*, maxsize: int=..., protect_get: Literal[True], protect_put: Literal[True]=..., can_change_get: bool=..., can_change_put: bool=..., wait: bool=..., priority: bool=..., lifo: bool=..., raising: bool=..., get_from: str=..., put_from: str=..., gettyp: type[R]=object, puttyp: type[V]=object, init_items: SupportsIteration[T]=[], log: Callable[[str], None]=..., auditf: Callable[[Literal['asyncutils.queues.password_queue'], Literal[True], Literal[True], str, str], None]=...) -> _B[R, V, T]: ...
class PotentQueueBase[T](Queue[T], EventualLoopMixin, metaclass=ABCMeta):
    @abstractmethod
    def _init(self, maxsize: int) -> None: ...
    @abstractmethod
    def _get(self) -> T: ...
    @abstractmethod
    def _put(self, item: T) -> None: ...
    @abstractmethod
    def peek_all(self) -> list[T]: ...
    @abstractmethod
    def qsize(self) -> int: ...
    def __init__(self, maxsize: int=...): ...
    async def smart_put(self, item: T, *, timeout: float|None=..., raising: bool=...) -> bool|None: ...
    @overload
    async def smart_get(self, *, timeout: float|None=...) -> T: '''Calls get_nowait if an item is immediately available, waits for a item with timeout equal to timeout otherwise; if the timeout expires and a default is provided, return that default.'''
    @overload
    async def smart_get(self, *, timeout: float|None=..., default: T) -> T: ...
    async def extend(self, it: SupportsIteration[T], timeout: float|None=...) -> None: ...
    def sync_put(self, item: T, *, timeout: float|None=...) -> bool|None: ...
    @overload
    def sync_get(self, *, timeout: float|None=...) -> T: ...
    @overload
    def sync_get(self, *, timeout: float|None=..., default: T) -> T: ...
    def push(self, item: T) -> bool: '''Put an item into the queue immediately, popping if necessary; returns success.'''
    def drain_persistent(self, max: int|None=None, timeout: float|None=None) -> AsyncGenerator[T, None]: ...
    def drain_until_empty(self, max: int|None=...) -> Generator[T, None, None]: ...
    def drain_retlist(self, max: int|None=...) -> list[T]: ...
    def empty(self) -> bool: ...
    def __iter__(self): return self.drain_until_empty()
    def __aiter__(self): return self.drain_persistent()
    def shutdown(self, immediate: bool=False) -> None: ...
    @property
    def is_shutdown(self) -> bool: ...
    @is_shutdown.setter
    def is_shutdown(self, val: bool, /): ...
    @property
    def can_put_now(self) -> bool: ...
    @property
    def can_get_now(self) -> bool: ...
    @property
    def fully_functional(self) -> bool: ...
    @property
    def capacity(self) -> int|float: ...
    @property
    def remaining_capacity(self) -> int|float: ...
    @property
    def utilization_rate(self) -> float: ...
    def pushpop_nowait(self, item: T, raising: bool=...) -> T: ...
    def poppush_nowait(self, item: T, raising: bool=...) -> T: ...
    async def pushpop(self, item: T) -> T: ...
    async def poppush(self, item: T) -> T: ...
    def clear(self) -> None: ...
    def transaction(self) -> _AsyncGeneratorContextManager[Self]: ...
    @overload
    def map[R](self, f: Callable[[T], Awaitable[R]], stop_when: Future[None]|None=..., *, lifo: Literal[False]=...) -> SmartQueue[R]: ...
    @overload
    def map[R](self, f: Callable[[T], Awaitable[R]], stop_when: Future[None]|None=..., *, lifo: Literal[True]) -> SmartLifoQueue[R]: ...
    @overload
    def starmap[R, *Ts](self: PotentQueueBase[tuple[*Ts]], f: Callable[[*Ts], Awaitable[R]], stop_when: Future|None=..., *, lifo: Literal[False]=...) -> SmartQueue[R]: ...
    @overload
    def starmap[R, *Ts](self: PotentQueueBase[tuple[*Ts]], f: Callable[[*Ts], Awaitable[R]], stop_when: Future|None=..., *, lifo: Literal[True]) -> SmartLifoQueue[R]: ...
    @overload
    def filter(self, pred: Callable[[T], bool]=..., *, lifo: Literal[False]=...) -> SmartQueue[T]: '''Returns a new queue from which getters can get the items in this queue that satisfy the predicate; items remaining in the original queue did not satisfy the predicate.'''
    @overload
    def filter(self, pred: Callable[[T], bool]=..., *, lifo: Literal[True]) -> SmartLifoQueue[T]: ...
    @overload
    def enumerate(self, *, lifo: Literal[False]=...) -> SmartQueue[tuple[int, T]]: ...
    @overload
    def enumerate(self, *, lifo: Literal[True]) -> SmartLifoQueue[tuple[int, T]]: ...
    def map_nowait[R](self, f: Callable[[T], Coroutine[Any, Any, R]]) -> list[R]: ...
    def starmap_nowait[R](self, f: Callable[..., Coroutine[Any, Any, R]]) -> list[R]: ...
    def filter_nowait(self, pred: Callable[[T], bool]=...) -> tuple[list[T], int]: '''Filter items in the queue by a predicate and return a list of removed items and an integer; the items in the returned list after the index corresponding to that integer were items rejected from the queue due to the queue being full.'''
    def enumerate_nowait(self) -> Generator[tuple[int, T], None, None]: ...
class SmartQueue[T](PotentQueueBase[T]):
    def _init(self, maxsize: int) -> None: ...
    def _get(self) -> T: ...
    def _put(self, item: T) -> None: ...
    def peek(self) -> T: ...
    def peek_all(self) -> list[T]: ...
    def qsize(self) -> int: ...
    def rotate(self, n: int=..., /) -> None: ...
class SmartLifoQueue[T](PotentQueueBase[T]):
    def _init(self, maxsize: int) -> None: ...
    def _get(self) -> T: ...
    def _put(self, item: T) -> None: ...
    def peek(self, i: int=..., /) -> T: ...
    def peek_all(self) -> list[T]: ...
    def qsize(self) -> int: ...
class SmartPriorityQueue[T](PotentQueueBase[T]):
    def __init__(self, maxsize: int=..., *, init_items: SupportsIteration[T]=[]): ...
    def _init(self, maxsize: int) -> None: ...
    def _get(self) -> T: ...
    def _put(self, item: T) -> None: ...
    def peek(self) -> T: ...
    def peek_all(self) -> list[T]: ...
    def qsize(self) -> int: ...
class UserPriorityQueue[T](SmartPriorityQueue[tuple[int, int, T]]):
    @classmethod
    def from_iter_of_tuples(cls, items: SupportsIteration[tuple[int, int, T]], maxsize: int=...) -> Self: ...
    def __init__(self, maxsize: int=..., *, init_priority: int=..., init_items: SupportsIteration[T]=[]): ...