'''Readers-writer locks with different fairness policies, applicable in different situations.'''
from ._internal.prots import RWLockCM, RWLockRV
from abc import ABC, abstractmethod
from collections.abc import Awaitable, Callable
from typing import Any, Concatenate, Literal, Self, final, overload
__all__ = 'AgingRWLock', 'CoercedMethod', 'FairPriorityRWLock', 'FairRWLock', 'PriorityRWLock', 'RWLock', 'ReadPreferredRWLock', 'WritePreferredPriorityRWLock', 'WritePreferredRWLock'
class RWLock(ABC):
    '''Common base class for all readers-writer locks.'''
    @overload
    def __new__(cls, /, prefer_writers: Literal[True]) -> WritePreferredRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: Literal[False]) -> ReadPreferredRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: bool=...) -> ReadPreferredRWLock|WritePreferredRWLock: '''Return a :class:`WritePreferredRWLock` if ``prefer_writers`` is ``True``, otherwise a :class:`ReadPreferredRWLock`. :const:`~asyncutils.context.Context.RWLOCK_DEFAULT_PREFER_WRITERS` becomes the value of ``prefer_writers`` when it is not passed.'''
    def reader[T, **P](self, f: Callable[P, Awaitable[T]], /) -> RWLockRV[T, P]: '''A decorator wrapping a function returning an awaitable in an async reading context. :meth:`reader` and :meth:`writer` methods are attached to the returned async callable.'''
    def writer[T, **P](self, f: Callable[P, Awaitable[T]], /) -> RWLockRV[T, P]: '''A decorator wrapping a function returning an awaitable in an async writing context. :meth:`reader` and :meth:`writer` methods are attached to the returned async callable.'''
    @abstractmethod
    def reading(self) -> RWLockCM: '''Return an async context manager for reading access. It is recommended to implement this by decorating an async generator function with :func:`contextlib.asynccontextmanager`.'''
    @abstractmethod
    def writing(self) -> RWLockCM: '''Return an async context manager for writing access. It is recommended to implement this by decorating an async generator function with :func:`contextlib.asynccontextmanager`.'''
    def locked(self) -> bool: '''Whether the lock is currently held by a writer.'''
    @abstractmethod
    def setup(self) -> None: '''Set up the internal state of the lock.'''
    @classmethod
    def lock[T, **P](cls, f: Callable[P, Awaitable[T]], /) -> RWLockRV[T, P]: '''Create a lock and register a reader.'''
class ReadPreferredRWLock(RWLock):
    '''Readers-writer lock preferring readers, which risks writer starvation.'''
    def __new__(cls, /) -> Self: ...
    def locked(self) -> bool: ...
    def setup(self) -> None: ...
    def reading(self) -> RWLockCM: ...
    def writing(self) -> RWLockCM: ...
class WritePreferredRWLock(RWLock):
    '''Readers-writer lock preferring writers, which risks reader starvation.'''
    def __new__(cls, /) -> Self: ...
    def setup(self) -> None: ...
    def reading(self) -> RWLockCM: ...
    def writing(self) -> RWLockCM: ...
class FairRWLock(RWLock):
    '''Readers-writer lock that maintains FIFO order for both readers and writers indiscriminately.'''
    def __new__(cls, /) -> Self: ...
    def setup(self) -> None: ...
    def reading(self) -> RWLockCM: ...
    def writing(self) -> RWLockCM: ...
class PriorityRWLock(RWLock):
    '''| Common base class of :class:`FairPriorityRWLock` and :class:`WritePreferredPriorityRWLock`.
    | Lower priority levels are preferred, and the default priority is 0, as in other patterns in this module related to priority.'''
    @overload
    def __new__(cls, /, prefer_writers: Literal[True]) -> WritePreferredPriorityRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: Literal[False]) -> FairPriorityRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: bool=...) -> FairPriorityRWLock|WritePreferredPriorityRWLock: '''Whether instantiating this class gives a :class:`PriorityRWLock` unfair to readers by default depends on :const:`~asyncutils.context.Context.RWLOCK_DEFAULT_PREFER_WRITERS`.'''
    def reading(self, priority: int=...) -> RWLockCM: ...
    def writing(self, priority: int=...) -> RWLockCM: ...
    def setup(self) -> None: ...
class FairPriorityRWLock(PriorityRWLock):
    '''At the same priority level, writers are preferred over readers.'''
    def __new__(cls, /) -> Self: ...
class WritePreferredPriorityRWLock(PriorityRWLock):
    '''Writers at any priority level are preferred over readers at any priority level.'''
    def __new__(cls, /) -> Self: ...
class AgingRWLock(PriorityRWLock):
    '''| A readers-writer lock with a priority policy multiplying the current number of attempts to acquire the reading or writing lock,
    | counted per corresponding task, by the respective factor given at construction, to obtain the priority.'''
    def __new__(cls, /, rf: float=..., wf: float=...) -> Self:
        '''* ``rf``, the read priority factor, defaults to :const:`~asyncutils.context.Context.AGING_RWLOCK_DEFAULT_READ_PRIORITY_FACTOR`.
        * ``wf``, the write priority factor, defaults to :const:`~asyncutils.context.Context.AGING_RWLOCK_DEFAULT_WRITE_PRIORITY_FACTOR`.'''
    def reading(self, priority: int=...) -> RWLockCM: ...
    def writing(self, priority: int=...) -> RWLockCM: ...
    def setup(self) -> None: ...
    @property
    def cur_unsuccessful_reads(self) -> int: '''The current number of unsuccessful attempts to acquire the reading lock, counted across all tasks.'''
    @property
    def cur_unsuccessful_writes(self) -> int: '''The current number of unsuccessful attempts to acquire the writing lock, counted across all tasks.'''
@final
class CoercedMethod[T, R, **P]:
    '''Interpret any callable as a regular function in a class body so that access on instance returns something like a bound method.'''
    def __init__(self, func: Callable[Concatenate[R, P], T], /): ...
    def __getattr__(self, name: str, /) -> Any: ... # noqa: ANN401
    def __set_name__(self, owner: type[R], name: str, /) -> None: ...
    def __get__(self, instance: R, owner: type[R]|None=..., /) -> Callable[P, T]: '''Return the 'bound method'. The descriptor itself is hidden and cannot be accessed on the class it is defined in, only instances of.'''
