'''Readers-writer locks with different fairness policies, applicable in different situations.'''
from ._internal.types import RWLockRV
from _collections_abc import Awaitable, Callable
from abc import ABC, abstractmethod
from contextlib import AbstractAsyncContextManager
from typing import Literal, Self, overload
__all__ = 'FairRWLock', 'PriorityRWLock', 'RWLock', 'ReadPreferredPriorityRWLock', 'ReadPreferredRWLock', 'WritePreferredPriorityRWLock', 'WritePreferredRWLock'
class RWLock(ABC):
    '''Base class for readers-writer locks.'''
    @overload
    def __new__(cls, /, prefer_writers: Literal[True]) -> WritePreferredRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: Literal[False]) -> ReadPreferredRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: bool=...) -> ReadPreferredRWLock|WritePreferredRWLock: '''Whether instantiating this class gives a writer-preferring :class:`RWLock` by default depends on :const:`context.RWLOCK_DEFAULT_PREFER_WRITERS`.''' # type: ignore[misc]
    def reader[T, **P](self, f: Callable[P, Awaitable[T]], /) -> RWLockRV[T, P]: '''A decorator wrapping a function returning an awaitable in an async reading context. :meth:`reader` and :meth:`writer` methods are attached to the returned async callable.'''
    def writer[T, **P](self, f: Callable[P, Awaitable[T]], /) -> RWLockRV[T, P]: '''A decorator wrapping a function returning an awaitable in an async writing context. :meth:`reader` and :meth:`writer` methods are attached to the returned async callable.'''
    @abstractmethod
    def reading(self) -> AbstractAsyncContextManager[None, None]: '''Return an async context manager for reading access. It is recommended to implement this by decorating an async generator function with :deco:`contextlib.asynccontextmanager`.'''
    @abstractmethod
    def writing(self) -> AbstractAsyncContextManager[None, None]: '''Return an async context manager for writing access. It is recommended to implement this by decorating an async generator function with :deco:`contextlib.asynccontextmanager`.'''
    def locked(self) -> bool: '''Whether the lock is currently held by a writer.'''
    @abstractmethod
    def setup(self) -> None: '''Set up the internal state of the lock.'''
class ReadPreferredRWLock(RWLock):
    def __new__(cls, /) -> Self: ...
    def locked(self) -> bool: ...
    def setup(self) -> None: ...
    def reading(self) -> AbstractAsyncContextManager[None, None]: ...
    def writing(self) -> AbstractAsyncContextManager[None, None]: ...
class WritePreferredRWLock(RWLock):
    def __new__(cls, /) -> Self: ...
    def setup(self) -> None: ...
    def reading(self) -> AbstractAsyncContextManager[None, None]: ...
    def writing(self) -> AbstractAsyncContextManager[None, None]: ...
class FairRWLock(RWLock):
    def __new__(cls, /) -> Self: ...
    def setup(self) -> None: ...
    def reading(self) -> AbstractAsyncContextManager[None, None]: ...
    def writing(self) -> AbstractAsyncContextManager[None, None]: ...
class PriorityRWLock(RWLock):
    '''Lower priority levels are preferred.'''
    @overload
    def __new__(cls, /, prefer_writers: Literal[True]) -> WritePreferredPriorityRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: Literal[False]) -> ReadPreferredPriorityRWLock: ...
    @overload
    def __new__(cls, /, prefer_writers: bool=...) -> ReadPreferredPriorityRWLock|WritePreferredPriorityRWLock: '''Whether instantiating this class gives a writer-preferring :class:`PriorityRWLock` by default depends on :const:`context.RWLOCK_DEFAULT_PREFER_WRITERS`.''' # type: ignore[misc]
    def reading(self, priority: int=...) -> AbstractAsyncContextManager[None, None]: ...
    def writing(self, priority: int=...) -> AbstractAsyncContextManager[None, None]: ...
    def setup(self) -> None: ...
class ReadPreferredPriorityRWLock(PriorityRWLock):
    '''At the same priority level, writers are preferred over readers.'''
    def __new__(cls, /) -> Self: ...
class WritePreferredPriorityRWLock(PriorityRWLock):
    '''Writers at any priority level are preferred over readers at any priority level.'''
    def __new__(cls, /) -> Self: ...