from .exceptions import IgnoreErrors
from ._internal.protocols import AsyncLockLike
from typing import Any, Literal, Concatenate, overload
from _collections_abc import Awaitable, Coroutine, Callable, Generator, AsyncGenerator
from asyncio.events import AbstractEventLoop
from asyncio.tasks import Task
from asyncio.locks import Semaphore, BoundedSemaphore, Lock
from asyncio.futures import Future
__all__ = 'get_future', 'new_tasks', 'to_sync', 'to_sync_from_loop', 'sync_await', 'semaphore', 'lockf', 'sync_lock', 'sync_lock_from_binder', 'to_async', 'get_aiter_fromf', 'safe_cancel'
_ignore_cancellation: IgnoreErrors
def get_future[T](aw: Awaitable[T], loop: AbstractEventLoop|None=...) -> Future[T]: ...
def new_tasks[T](*coro: Coroutine[Any, Any, T]) -> Generator[Task[T], None, None]: ...
def to_sync[R, **P](f: Callable[P, Awaitable[R]], timeout: float|None=..., loop: AbstractEventLoop|None=...) -> Callable[P, R]: ...
class to_sync_from_loop:
    '''Not a class at runtime.'''
    def __init__(self, loop: AbstractEventLoop): ...
    def __call__[R, **P](self, f: Callable[P, Awaitable[R]], timeout: float|None=...) -> Callable[P, R]: ...
def sync_await[T](aw: Awaitable[T], *, timeout: float|None=..., loop: AbstractEventLoop|None=...) -> T: ...
@overload
def semaphore(bounded: Literal[False]=..., workers: int=...) -> Semaphore: ...
@overload
def semaphore(bounded: Literal[True], workers: int=...) -> BoundedSemaphore: ...
def lockf[T, **P](f: Callable[P, Awaitable[T]], /, lf: type[AsyncLockLike]=Lock) -> Callable[P, Coroutine[Any, Any, T]]: ...
def sync_lock[R, **P](l: Lock, timeout: float|None=...) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
def sync_lock_from_binder[T, R, **P](f: Callable[[T], Lock], timeout: float|None=...) -> Callable[[Callable[Concatenate[T, P], R]], Callable[Concatenate[T, P], R]]: ...
def to_async[T, **P](func: Callable[P, T], loop: AbstractEventLoop|None=...) -> tuple[Callable[P, Coroutine[Any, Any, T]], Callable[[], None]]: ...
def get_aiter_fromf[T](f: Callable[[], Awaitable[T]], sentinel: T=..., /) -> AsyncGenerator[T, None]: '''Emulates the second form of the builtin iter function in async, which the aiter function does not have.'''
async def safe_cancel(t: Future) -> None: ...