'''A versioning scheme for asyncutils. Inspired by torch/torch_version.py, but with quite some differences.'''
from _collections_abc import Callable, Iterable
from typing import Any, Self, Literal, Iterator, final, overload
from ._internal.protocols import IntCompatible
__all__ = 'VersionInfo', 'VersionDelta', 'normalize', 'register_normalizer', 'unregister_normalizer', 'dispatch_normalizer', 'autogenerate_normalizers'
@final
class VersionInfo(str):
    def __new__(cls, /, *a: IntCompatible) -> Self: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> Literal[3]: ...
    def __getitem__(self, idx: int, /) -> int: ...
    def __lt__(self, other: Any, /) -> bool: ...
    def __le__(self, other: Any, /) -> bool: ...
    def __gt__(self, other: Any, /) -> bool: ...
    def __ge__(self, other: Any, /) -> bool: ...
    def __eq__(self, other: Any, /) -> bool: ...
    def __ne__(self, other: Any, /) -> bool: ...
    def __reduce__(self) -> tuple[type[Self], tuple[int, int, int]]: ...
    def __repr__(self) -> str: '''`version == eval(repr(version))` holds.'''
    @overload
    def __add__(self, other: int, /) -> Self: ...
    @overload
    def __add__(self, other: VersionDelta, /) -> Self: ...
    @overload
    def __sub__(self, other: int, /) -> Self: ...
    @overload
    def __sub__(self, other: VersionDelta, /) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> VersionDelta: ...
    def __format__(self, format_spec: str, /) -> str: ...
    def __int__(self) -> int: '''Assumes minor and patch are less than 256.'''
    def __floor__(self) -> int: '''Returns the major version.'''
    def __ceil__(self) -> int: '''Returns the major version, adding one if there is a minor or patch version.'''
    def __bytes__(self) -> bytes: '''Assumes major, minor, and patch are all less than 256.'''
    def __float__(self) -> float: '''Assumes minor and patch are less than 100.'''
    def __complex__(self) -> complex: '''Loses the patch version.'''
    def replace_parts(self, *, major: int=..., minor: int=..., patch: int=...) -> Self: ...
    def change_sep(self, sep: str) -> str: ...
    def compatible(self, other: Self, /, majtol: int|None=..., mintol: int|None=...) -> bool: ...
    def next_patch(self) -> Self: ...
    def next_minor(self) -> Self: ...
    def next_major(self) -> Self: ...
    @classmethod
    def get_current_version(cls) -> Self: '''Return the current version number of asyncutils; equivalent to asyncutils.__version__.'''
    @classmethod
    def to_version(cls, o: Any, /) -> Self: '''Builds an instance from any normalizable object; throws an exception if not possible.'''
    @property
    def is_valid(self) -> Literal[True]: '''If this returns False, the user must have messed something up intentionally.'''
    @property
    def representation(self) -> str:
        """>>> print(VersionInfo(4, 2).representation)
        asyncutils v4.2.0"""
    @property
    def is_unstable(self) -> Literal[False]: '''True only in development, so should be considered always False.'''
    @property
    def parts(self) -> tuple[int, int, int]: '''The tuple (major, minor, patch); all integers.'''
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def patch(self) -> int: ...
    __index__, __trunc__ = __int__, __floor__
class VersionDelta(tuple[int, int, int]):
    def __new__(cls, major: int=..., minor: int=..., patch: int=...) -> Self: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def patch(self) -> int: ...
def normalize(o: Any, /) -> tuple[int, int, int]|None:
    '''Returns a tuple of three integers: major, minor, patch, from the information provided by the object, to be extracted by registered normalizers.
    Normalization is hardcoded for str, complex, int, float. For iterables, the default is to take the first three items and pad zeros behind if necessary.
    Register normalizers using register_normalizer, which returns False if there is already a normalizer registered.
    Unregister normalizers using unregister_normalizer, which returns the previous normalizer (if any) and None otherwise.
    Get the normalizer to be used to normalize an object using dispatch_normalizer.
    A normalizer can return None for unnormalizable objects, in which case the comparison operators against instances of VersionInfo will delegate to that object.
    If there is fault in the normalizer (it raises an exception or returns a non-iterable), the normalizer is removed and the error propagated.
    Returns None if a normalizer is not found.
    >>> normalize('1.2.3')
    (1, 2, 3)
    >>> normalize(19.0203)
    (19, 2, 3)
    >>> normalize(0x10F0203)
    (271, 2, 3)
    >>> normalize((1, 3, 5, 7))
    (1, 3, 5)
    >>> normalize(1.2+2.3j)
    (1, 2, 0)
    >>> autogenerate_normalizers()
    True
    >>> normalize(Decimal('1.2345'))
    (1, 23, 45)
    >>> normalize(Fraction(1, 3))
    (1, 3, 0)'''
@overload
def register_normalizer[T](o: T, f: Callable[[T], Iterable[int]], /) -> bool: ...
@overload
def register_normalizer[T](o: type[T], f: Callable[[T], Iterable[int]], /) -> bool: ...
@overload
def unregister_normalizer[T](o: T, /) -> Callable[[T], Iterable[int]]|None: ...
@overload
def unregister_normalizer[T](o: type[T], /) -> Callable[[T], Iterable[int]]|None: ...
@overload
def dispatch_normalizer[T](o: T, /) -> Callable[[T], Iterable[int]]|None: ...
@overload
def dispatch_normalizer[T](o: type[T], /) -> Callable[[T], Iterable[int]]|None: ...
def autogenerate_normalizers() -> bool: '''Registers normalizers for decimal.Decimal and fractions.Fraction. Returns if both normalizers were successfully registered (including re-registration of the same normalizer).'''