name: GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency: {group: pages}
jobs:
  build:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          python-version: "3.14"
          activate-environment: true
      - run: uv pip install ".[themes]"
      - run: . scripts/generate.sh
      - run: make -C docs html
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: docs/build/html
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
        id: deploy
    timeout-minutes: 5
