name: CI
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
      with:
        ref: ${{github.event.pull_request.head.sha || github.sha}}
    - uses: astral-sh/setup-uv@v10.0.0
      with:
        activate-environment: true
        python-version: "3.15"
    - run: uv pip install -e ".[test]"
    - run: uvx ruff check --output-format=github
    - run: uvx ty check --output-format=github
    - run: pytest -vv -p asyncio -p no:asyncio-cooperative --no-local-badge --tb long --cov-report xml
    - uses: codecov/codecov-action@v7.0.0
      with:
        flags: unittests
        name: codecov-umbrella
        token: ${{secrets.CODECOV_TOKEN}}
        verbose: true
    timeout-minutes: 5
  secondary:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.12", "3.15"]
        include: # TODO: macos-latest graalpy build blocked until Aug 25 release
          - os: ubuntu-latest
            python-version: 3.14t
    steps:
    - uses: actions/checkout@v7.0.1
    - uses: astral-sh/setup-uv@v10.0.0
      with:
        python-version: ${{matrix.python-version}}
    - run: uv run --with ".[test]" pytest -vv -p asyncio --no-cov -p no:asyncio-cooperative --no-local-badge --tb long
    timeout-minutes: 5
