name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint-and-test-with-cov:
    runs-on: ubuntu-latest
    permissions:
      code-quality: write
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        ref: ${{github.event.pull_request.head.sha || github.sha}}
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        cache-python: true
    - run: uvx ruff check --output-format=github
    - run: uvx ty check --output-format=github
    - run: uv run --with ".[test]" --python 3.15 pytest -vv -p asyncio -p no:asyncio-cooperative --no-local-badge --maxfail 0 --tb long --cov-report xml
    - if: ${{github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository}}
      uses: actions/upload-code-coverage@v1.2.0
      with:
        fail-on-error: false
        file: coverage.xml
        language: Python
        label: code-coverage/pytest
  cross-platform-tests:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.15"]
        include:
          - os: ubuntu-latest
            python-version: gp312
          - os: ubuntu-latest
            python-version: 3.14t
        exclude:
          - os: ubuntu-latest
            python-version: "3.15"
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        python-version: ${{matrix.python-version}}
        cache-python: true
    - run: uv run --with ".[test]" pytest -vv -p asyncio --no-cov -p no:asyncio-cooperative --no-local-badge --maxfail 0 --tb long
