name: Python package
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        python-version: 3.12
        cache-python: true
        activate-environment: true
    - name: Install dependencies
      run: uv pip install -U mypy -e . && uv pip check
    - name: Lint with ruff
      run: uvx ruff check --output-format=github
    - name: Run mypy and stubtest
      run: mypy asyncutils && stubtest asyncutils --strict-type-check-only --allowlist=allowlist.txt
  test:
    needs: lint
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.15.0-beta.1"]
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        python-version: ${{matrix.python-version}}
    - name: Run tests
      run: uv run --with ".[test]" pytest -vv --cov-report xml
    - name: Upload results
      if: ${{matrix.os == 'ubuntu-latest' && matrix.python-version == '3.15.0-beta.1'}}
      uses: codecov/codecov-action@v6.0.0
      with:
        disable_search: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{secrets.CODECOV_TOKEN}}