name: Build and publish
env:
  RELEASE: ${{github.event.release.tag_name}}
on:
  release:
    types: [published]
jobs:
  pub:
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/py-asyncutils/${{env.RELEASE}}
    steps:
      - run: if [[ ! $RELEASE =~ ^[0-9]+\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$ ]]; then echo "Release name '$RELEASE' does not match the expected format 'X.Y.Z', with both Y and Z between 0 and 255" && exit 1; fi
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
        with:
          enable-cache: false
      - run: uv build
      - run: uv publish
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302
        id: m
        with:
          images: ghcr.io/${{github.repository}}
          tags: type=semver,pattern={{version}},value=${{env.RELEASE}}
      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: .
          push: true
          tags: ${{steps.m.outputs.tags}}
          labels: ${{steps.m.outputs.labels}}
    timeout-minutes: 10
